export const bulan = [
  { key: "januari", label: "Januari" },
  { key: "februari", label: "Februari" },
  { key: "maret", label: "Maret" },
  { key: "april", label: "April" },
  { key: "mei", label: "Mei" },
  { key: "juni", label: "Juni" },
  { key: "juli", label: "Juli" },
  { key: "agustus", label: "Agustus" },
  { key: "september", label: "September" },
  { key: "oktober", label: "Oktober" },
  { key: "november", label: "November" },
  { key: "desember", label: "Desember" },
];

export const tahun = [
  { key: "24", label: "2024" },
  // { key: "2", label: "Februari" },
  // { key: "3", label: "Maret" },
  // { key: "4", label: "April" },
  // { key: "5", label: "Mei" },
  // { key: "6", label: "Juni" },
  // { key: "7", label: "Juli" },
  // { key: "8", label: "Agustus" },
  // { key: "9", label: "September" },
  // { key: "10", label: "Oktober" },
  // { key: "11", label: "November" },
  // { key: "12", label: "Desember" },
];

export const rentang = [
  { key: "1-bulan", label: "1 Bulanan" },
  { key: "3-bulan", label: "3 Bulanan" },
]

export const dinamikaAtmosfir = [
  {
    key: '1-bulan-juni-24',
    title: 'The Standardized Precipitation Index 1 Bulanan Juni 2024',
    tgl: '19 Jun 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    link: "https://cdn.bmkg.go.id/Web/SPI1M_2406.jpg",
    pdfLink: "https://cdn.bmkg.go.id/web/SPI1M_2406.pdf",
  },
  {
    key: '3-bulan-juni-24',
    title: 'The Standardized Precipitation Index 3 Bulanan Juni 2024',
    tgl: '19 Jun 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    link: "https://prosesweb.bmkg.go.id/wp-content/uploads/SPI3M_2406.jpg",
    pdfLink: "https://cdn.bmkg.go.id/web/SPI3M_2406.pdf",
  },
  {
    key: '1-bulan-mei-24',
    title: 'The Standardized Precipitation Index 1 Bulanan Mei 2024',
    tgl: '17 Mei 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    link: "https://cdn.bmkg.go.id/Web/SPI1M-7.jpg",
    pdfLink: "https://cdn.bmkg.go.id/web/SPI1MCEWS-2.pdf",
  },
  {
    key: '3-bulan-mei-24',
    title: 'The Standardized Precipitation Index 3 Bulanan Mei 2024',
    tgl: '17 Mei 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    link: "https://prosesweb.bmkg.go.id/wp-content/uploads/SPI3M-8.jpg",
    pdfLink: "https://cdn.bmkg.go.id/web/SPI3M-4.pdf",
  },
  {
    key: '1-bulan-april-24',
    title: 'The Standardized Precipitation Index 1 Bulanan April 2024',
    tgl: ' 17 Apr 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    link: "https://cdn.bmkg.go.id/Web/SPI1M-6.jpg",
    pdfLink: "https://cdn.bmkg.go.id/Web/SPI1MCEWS-1.pdf",
  },
  {
    key: '3-bulan-april-24',
    title: 'The Standardized Precipitation Index 3 Bulanan April 2024',
    tgl: ' 17 Apr 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    link: "https://cdn.bmkg.go.id/Web/SPI3M-7.jpg",
    pdfLink: "https://cdn.bmkg.go.id/Web/SPI3M-3.pdf",
  },
  {
    key: '1-bulan-maret-24',
    title: 'The Standardized Precipitation Index 1 Bulanan Maret 2024',
    tgl: ' 13 Mar 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    link: "https://cdn.bmkg.go.id/Web/spi1m-5.jpg",
    pdfLink: "https://cdn.bmkg.go.id/Web/SPI1MCEWS_2403.pdf",
  },
  {
    key: '3-bulan-maret-24',
    title: 'The Standardized Precipitation Index 3 Bulanan Maret 2024',
    tgl: ' 13 Mar 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    link: "https://cdn.bmkg.go.id/Web/spi3m-6.jpg",
    pdfLink: "https://cdn.bmkg.go.id/Web/SPI3M_2403.pdf",
  },
  {
    key: '1-bulan-februari-24',
    title: 'The Standardized Precipitation Index 1 Bulanan Februari 2024',
    tgl: ' 12 Feb 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    link: "https://cdn.bmkg.go.id/Web/SPI1M-4.jpg",
    pdfLink: "https://cdn.bmkg.go.id/Web/SPI1MCEWS_2402.pdf",
  },
  {
    key: '3-bulan-februari-24',
    title: 'The Standardized Precipitation Index 3 Bulanan Februari 2024',
    tgl: ' 12 Feb 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    link: "https://cdn.bmkg.go.id/Web/SPI3M-5.jpg",
    pdfLink: "https://cdn.bmkg.go.id/Web/SPI3M_2402.pdf",
  },
  {
    key: '1-bulan-januari-24',
    title: 'The Standardized Precipitation Index 1 Bulanan Januari 2024',
    tgl: ' 31 Jan 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    link: "https://cdn.bmkg.go.id/Web/SPI1M-3.jpg",
    pdfLink: "https://cdn.bmkg.go.id/Web/SPI1MCEWS_2401.pdf",
  },
  {
    key: '3-bulan-januari-24',
    title: 'The Standardized Precipitation Index 3 Bulanan Januari 2024',
    tgl: ' 31 Jan 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    link: "https://cdn.bmkg.go.id/Web/SPI3M-4.jpg",
    pdfLink: "https://cdn.bmkg.go.id/Web/SPI3M_2401.pdf",
  },
]