export const day1 = [
    {
      kota: "Denpasar",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Berawan",
        malam: "Cerah Berawan",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 32",
      kelembapan: "60 - 85",
    },
    {
      kota: "Serang",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Hujan Ringan",
        malam: "Berawan",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 33",
      kelembapan: "60 - 90",
    },
    {
      kota: "Bengkulu",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Cerah Berawan",
        malam: "Cerah Berawan",
        diniHari: "Berawan Tebal",
      },
      suhu: "23 - 34",
      kelembapan: "65 - 85",
    },
    {
      kota: "Yogyakarta",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Berawan",
        malam: "Berawan",
        diniHari: "Berawan",
      },
      suhu: "22 - 32",
      kelembapan: "55 - 90",
    },
    {
      kota: "Jakarta Pusat",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Cerah Berawan",
        malam: "Berawan",
        diniHari: "Berawan",
      },
      suhu: "25 - 31",
      kelembapan: "65 - 85",
    },
    {
      kota: "Gorontalo",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Cerah Berawan",
        malam: "Cerah Berawan",
        diniHari: "Hujan Ringan",
      },
      suhu: "23 - 33",
      kelembapan: "65 - 95",
    },
    {
      kota: "Jambi",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Ringan",
        malam: "Berawan",
        diniHari: "Kabut",
      },
      suhu: "23 - 33",
      kelembapan: "60 - 100",
    },
    {
      kota: "Bandung",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Cerah Berawan",
        malam: "Berawan",
        diniHari: "Cerah Berawan",
      },
      suhu: "19 - 30",
      kelembapan: "70 - 95",
    },
    {
      kota: "Semarang",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Cerah Berawan",
        malam: "Berawan",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 34",
      kelembapan: "55 - 90",
    },
    {
      kota: "Surabaya",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Cerah Berawan",
        malam: "Cerah Berawan",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 34",
      kelembapan: "50 - 90",
    },
    {
      kota: "Pontianak",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Berawan",
        malam: "Cerah Berawan",
        diniHari: "Berawan",
      },
      suhu: "23 - 33",
      kelembapan: "60 - 95",
    },
    {
      kota: "Banjarmasin",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Hujan Petir",
        malam: "Berawan",
        diniHari: "Berawan",
      },
      suhu: "24 - 33",
      kelembapan: "65 - 95",
    },
    {
      kota: "Palangkaraya",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Berawan",
        malam: "Berawan",
        diniHari: "Berawan",
      },
      suhu: "24 - 31",
      kelembapan: "65 - 95",
    },
    {
      kota: "Samarinda",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Berawan Tebal",
        malam: "Berawan Tebal",
        diniHari: "Hujan Petir",
      },
      suhu: "23 - 28",
      kelembapan: "80 - 100",
    },
    {
      kota: "Tarakan",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Cerah Berawan",
        malam: "Berawan",
        diniHari: "Hujan Petir",
      },
      suhu: "24 - 30",
      kelembapan: "75 - 90",
    },
    {
      kota: "Pangkal Pinang",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Hujan Ringan",
        malam: "Hujan Ringan",
        diniHari: "Berawan",
      },
      suhu: "24 - 32",
      kelembapan: "65 - 100",
    },
    {
      kota: "Tanjung Pinang",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Ringan",
        malam: "Cerah Berawan",
        diniHari: "Berawan",
      },
      suhu: "25 - 32",
      kelembapan: "65 - 95",
    },
    {
      kota: "Bandar Lampung",
      prakiraanCuaca: {
        pagi: "Cerah",
        siang: "Cerah Berawan",
        malam: "Cerah Berawan",
        diniHari: "Kabut",
      },
      suhu: "24 - 33",
      kelembapan: "55 - 100",
    },
    {
      kota: "Ambon",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Ringan",
        malam: "Berawan Tebal",
        diniHari: "Hujan Ringan",
      },
      suhu: "24 - 30",
      kelembapan: "70 - 95",
    },
    {
      kota: "Ternate",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Hujan Sedang",
        malam: "Hujan Ringan",
        diniHari: "Hujan Ringan",
      },
      suhu: "23 - 32",
      kelembapan: "65 - 100",
    },
    {
      kota: "Mataram",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Berawan",
        malam: "Cerah Berawan",
        diniHari: "Cerah Berawan",
      },
      suhu: "21 - 32",
      kelembapan: "55 - 95",
    },
    {
      kota: "Kupang",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Cerah Berawan",
        malam: "Cerah Berawan",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 33",
      kelembapan: "50 - 90",
    },
    {
      kota: "Kota Jayapura",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Hujan Ringan",
        malam: "Berawan",
        diniHari: "Berawan",
      },
      suhu: "23 - 31",
      kelembapan: "65 - 95",
    },
    {
      kota: "Manokwari",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Hujan Ringan",
        malam: "Hujan Petir",
        diniHari: "Berawan",
      },
      suhu: "24 - 32",
      kelembapan: "70 - 95",
    },
    {
      kota: "Pekanbaru",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Cerah Berawan",
        malam: "Cerah Berawan",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 31",
      kelembapan: "65 - 95",
    },
    {
      kota: "Mamuju",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Hujan Ringan",
        malam: "Berawan",
        diniHari: "Berawan",
      },
      suhu: "25 - 31",
      kelembapan: "70 - 95",
    },
    {
      kota: "Makassar",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Berawan",
        malam: "Berawan",
        diniHari: "Berawan",
      },
      suhu: "25 - 33",
      kelembapan: "70 - 90",
    },
    {
      kota: "Kendari",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Hujan Sedang",
        malam: "Berawan",
        diniHari: "Hujan Ringan",
      },
      suhu: "24 - 31",
      kelembapan: "70 - 95",
    },
    {
      kota: "Manado",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Hujan Ringan",
        malam: "Berawan",
        diniHari: "Berawan",
      },
      suhu: "23 - 31",
      kelembapan: "70 - 95",
    },
    {
      kota: "Padang",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Cerah Berawan",
        malam: "Cerah Berawan",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 31",
      kelembapan: "80 - 90",
    },
    {
      kota: "Palembang",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Sedang",
        malam: "Hujan Ringan",
        diniHari: "Kabut",
      },
      suhu: "24 - 30",
      kelembapan: "80 - 100",
    },
    {
      kota: "Medan",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Sedang",
        malam: "Hujan Ringan",
        diniHari: "Berawan",
      },
      suhu: "24 - 33",
      kelembapan: "65 - 95",
    },
  ];

  export const day2 = [
    {
      kota: "Denpasar",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Cerah Berawan",
        malam: "Berawan",
        diniHari: "Berawan Tebal",
      },
      suhu: "25 - 31",
      kelembapan: "70 - 85",
    },
    {
      kota: "Serang",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Berawan",
        malam: "Berawan Tebal",
        diniHari: "Cerah Berawan",
      },
      suhu: "23 - 32",
      kelembapan: "65 - 90",
    },
    {
      kota: "Bengkulu",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Sedang",
        malam: "Hujan Petir",
        diniHari: "Cerah Berawan",
      },
      suhu: "22 - 30",
      kelembapan: "75 - 95",
    },
    {
      kota: "Yogyakarta",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Berawan",
        malam: "Cerah Berawan",
        diniHari: "Hujan Ringan",
      },
      suhu: "24 - 31",
      kelembapan: "60 - 85",
    },
    {
      kota: "Jakarta Pusat",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Hujan Petir",
        malam: "Hujan Ringan",
        diniHari: "Berawan Tebal",
      },
      suhu: "25 - 32",
      kelembapan: "70 - 90",
    },
    {
      kota: "Gorontalo",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Berawan",
        malam: "Hujan Ringan",
        diniHari: "Hujan Sedang",
      },
      suhu: "24 - 33",
      kelembapan: "65 - 95",
    },
    {
      kota: "Jambi",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Petir",
        malam: "Hujan Sedang",
        diniHari: "Kabut",
      },
      suhu: "23 - 32",
      kelembapan: "70 - 100",
    },
    {
      kota: "Bandung",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Berawan Tebal",
        malam: "Hujan Sedang",
        diniHari: "Cerah Berawan",
      },
      suhu: "19 - 28",
      kelembapan: "75 - 95",
    },
    {
      kota: "Semarang",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Cerah Berawan",
        malam: "Berawan Tebal",
        diniHari: "Cerah Berawan",
      },
      suhu: "25 - 34",
      kelembapan: "55 - 85",
    },
    {
      kota: "Surabaya",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Sedang",
        malam: "Cerah Berawan",
        diniHari: "Berawan Tebal",
      },
      suhu: "24 - 33",
      kelembapan: "50 - 85",
    },
    {
      kota: "Pontianak",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Hujan Sedang",
        malam: "Hujan Petir",
        diniHari: "Berawan Tebal",
      },
      suhu: "23 - 32",
      kelembapan: "60 - 95",
    },
    {
      kota: "Banjarmasin",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Ringan",
        malam: "Berawan",
        diniHari: "Hujan Sedang",
      },
      suhu: "24 - 32",
      kelembapan: "70 - 95",
    },
    {
      kota: "Palangkaraya",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Berawan Tebal",
        malam: "Hujan Ringan",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 30",
      kelembapan: "65 - 90",
    },
    {
      kota: "Samarinda",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Petir",
        malam: "Hujan Sedang",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 29",
      kelembapan: "80 - 100",
    },
    {
      kota: "Tarakan",
      prakiraanCuaca: {
        pagi: "Hujan Sedang",
        siang: "Cerah Berawan",
        malam: "Hujan Ringan",
        diniHari: "Berawan Tebal",
      },
      suhu: "24 - 31",
      kelembapan: "75 - 90",
    },
    {
      kota: "Pangkal Pinang",
      prakiraanCuaca: {
        pagi: "Hujan Petir",
        siang: "Hujan Sedang",
        malam: "Hujan Ringan",
        diniHari: "Berawan Tebal",
      },
      suhu: "24 - 31",
      kelembapan: "65 - 100",
    },
    {
      kota: "Tanjung Pinang",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Petir",
        malam: "Cerah Berawan",
        diniHari: "Hujan Ringan",
      },
      suhu: "25 - 31",
      kelembapan: "65 - 95",
    },
    {
      kota: "Bandar Lampung",
      prakiraanCuaca: {
        pagi: "Cerah",
        siang: "Hujan Ringan",
        malam: "Cerah Berawan",
        diniHari: "Kabut",
      },
      suhu: "25 - 32",
      kelembapan: "55 - 100",
    },
    {
      kota: "Ambon",
      prakiraanCuaca: {
        pagi: "Hujan Sedang",
        siang: "Hujan Petir",
        malam: "Hujan Ringan",
        diniHari: "Berawan Tebal",
      },
      suhu: "25 - 29",
      kelembapan: "70 - 95",
    },
    {
      kota: "Ternate",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Sedang",
        malam: "Hujan Ringan",
        diniHari: "Hujan Sedang",
      },
      suhu: "24 - 31",
      kelembapan: "65 - 100",
    },
    {
      kota: "Mataram",
      prakiraanCuaca: {
        pagi: "Cerah",
        siang: "Cerah Berawan",
        malam: "Berawan Tebal",
        diniHari: "Hujan Ringan",
      },
      suhu: "21 - 31",
      kelembapan: "55 - 95",
    },
    {
      kota: "Kupang",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Petir",
        malam: "Hujan Ringan",
        diniHari: "Berawan Tebal",
      },
      suhu: "24 - 32",
      kelembapan: "50 - 90",
    },
    {
      kota: "Kota Jayapura",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Ringan",
        malam: "Berawan",
        diniHari: "Hujan Sedang",
      },
      suhu: "24 - 30",
      kelembapan: "65 - 95",
    },
    {
      kota: "Manokwari",
      prakiraanCuaca: {
        pagi: "Hujan Sedang",
        siang: "Berawan Tebal",
        malam: "Hujan Ringan",
        diniHari: "Cerah Berawan",
      },
      suhu: "25 - 31",
      kelembapan: "70 - 95",
    },
    {
      kota: "Pekanbaru",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Petir",
        malam: "Hujan Sedang",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 30",
      kelembapan: "65 - 95",
    },
    {
      kota: "Mamuju",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Ringan",
        malam: "Berawan",
        diniHari: "Hujan Petir",
      },
      suhu: "25 - 31",
      kelembapan: "70 - 95",
    },
    {
      kota: "Makassar",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Ringan",
        malam: "Hujan Sedang",
        diniHari: "Cerah Berawan",
      },
      suhu: "25 - 32",
      kelembapan: "70 - 90",
    },
    {
      kota: "Kendari",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Ringan",
        malam: "Berawan Tebal",
        diniHari: "Hujan Petir",
      },
      suhu: "24 - 30",
      kelembapan: "70 - 95",
    },
    {
      kota: "Manado",
      prakiraanCuaca: {
        pagi: "Berawan",
        siang: "Hujan Ringan",
        malam: "Berawan Tebal",
        diniHari: "Cerah Berawan",
      },
      suhu: "23 - 31",
      kelembapan: "70 - 95",
    },
    {
      kota: "Padang",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Cerah Berawan",
        malam: "Berawan Tebal",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 30",
      kelembapan: "80 - 90",
    },
    {
      kota: "Palembang",
      prakiraanCuaca: {
        pagi: "Hujan Sedang",
        siang: "Hujan Petir",
        malam: "Hujan Ringan",
        diniHari: "Kabut",
      },
      suhu: "24 - 30",
      kelembapan: "80 - 100",
    },
    {
      kota: "Medan",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Hujan Sedang",
        malam: "Hujan Petir",
        diniHari: "Berawan Tebal",
      },
      suhu: "24 - 33",
      kelembapan: "65 - 95",
    },
  ];
  
  export const day3 = [
    {
      kota: "Denpasar",
      prakiraanCuaca: {
        pagi: "Cerah",
        siang: "Berawan Tebal",
        malam: "Hujan Ringan",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 31",
      kelembapan: "70 - 90",
    },
    {
      kota: "Serang",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Sedang",
        malam: "Hujan Ringan",
        diniHari: "Cerah Berawan",
      },
      suhu: "23 - 31",
      kelembapan: "65 - 90",
    },
    {
      kota: "Bengkulu",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Berawan Tebal",
        malam: "Hujan Petir",
        diniHari: "Cerah Berawan",
      },
      suhu: "22 - 30",
      kelembapan: "75 - 95",
    },
    {
      kota: "Yogyakarta",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Ringan",
        malam: "Hujan Sedang",
        diniHari: "Berawan Tebal",
      },
      suhu: "24 - 31",
      kelembapan: "60 - 85",
    },
    {
      kota: "Jakarta Pusat",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Hujan Sedang",
        malam: "Hujan Petir",
        diniHari: "Cerah Berawan",
      },
      suhu: "25 - 32",
      kelembapan: "70 - 90",
    },
    {
      kota: "Gorontalo",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Petir",
        malam: "Hujan Ringan",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 32",
      kelembapan: "65 - 95",
    },
    {
      kota: "Jambi",
      prakiraanCuaca: {
        pagi: "Cerah",
        siang: "Hujan Ringan",
        malam: "Hujan Sedang",
        diniHari: "Kabut",
      },
      suhu: "23 - 32",
      kelembapan: "70 - 100",
    },
    {
      kota: "Bandung",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Sedang",
        malam: "Hujan Ringan",
        diniHari: "Berawan Tebal",
      },
      suhu: "19 - 28",
      kelembapan: "75 - 95",
    },
    {
      kota: "Semarang",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Ringan",
        malam: "Cerah Berawan",
        diniHari: "Berawan Tebal",
      },
      suhu: "25 - 34",
      kelembapan: "55 - 85",
    },
    {
      kota: "Surabaya",
      prakiraanCuaca: {
        pagi: "Cerah",
        siang: "Hujan Ringan",
        malam: "Hujan Sedang",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 33",
      kelembapan: "50 - 85",
    },
    {
      kota: "Pontianak",
      prakiraanCuaca: {
        pagi: "Hujan Sedang",
        siang: "Berawan Tebal",
        malam: "Hujan Ringan",
        diniHari: "Cerah Berawan",
      },
      suhu: "23 - 32",
      kelembapan: "60 - 95",
    },
    {
      kota: "Banjarmasin",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Sedang",
        malam: "Hujan Petir",
        diniHari: "Berawan Tebal",
      },
      suhu: "24 - 32",
      kelembapan: "70 - 95",
    },
    {
      kota: "Palangkaraya",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Berawan Tebal",
        malam: "Hujan Sedang",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 30",
      kelembapan: "65 - 90",
    },
    {
      kota: "Samarinda",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Sedang",
        malam: "Hujan Ringan",
        diniHari: "Berawan Tebal",
      },
      suhu: "24 - 29",
      kelembapan: "80 - 100",
    },
    {
      kota: "Tarakan",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Berawan Tebal",
        malam: "Hujan Sedang",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 31",
      kelembapan: "75 - 90",
    },
    {
      kota: "Pangkal Pinang",
      prakiraanCuaca: {
        pagi: "Hujan Petir",
        siang: "Berawan Tebal",
        malam: "Hujan Ringan",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 31",
      kelembapan: "65 - 100",
    },
    {
      kota: "Tanjung Pinang",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Sedang",
        malam: "Cerah Berawan",
        diniHari: "Hujan Ringan",
      },
      suhu: "25 - 31",
      kelembapan: "65 - 95",
    },
    {
      kota: "Bandar Lampung",
      prakiraanCuaca: {
        pagi: "Cerah",
        siang: "Hujan Ringan",
        malam: "Berawan Tebal",
        diniHari: "Kabut",
      },
      suhu: "25 - 32",
      kelembapan: "55 - 100",
    },
    {
      kota: "Ambon",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Hujan Sedang",
        malam: "Hujan Petir",
        diniHari: "Berawan Tebal",
      },
      suhu: "25 - 29",
      kelembapan: "70 - 95",
    },
    {
      kota: "Ternate",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Ringan",
        malam: "Hujan Sedang",
        diniHari: "Hujan Petir",
      },
      suhu: "24 - 31",
      kelembapan: "65 - 100",
    },
    {
      kota: "Mataram",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Ringan",
        malam: "Berawan Tebal",
        diniHari: "Cerah Berawan",
      },
      suhu: "21 - 31",
      kelembapan: "55 - 95",
    },
    {
      kota: "Kupang",
      prakiraanCuaca: {
        pagi: "Hujan Sedang",
        siang: "Berawan Tebal",
        malam: "Hujan Ringan",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 32",
      kelembapan: "50 - 90",
    },
    {
      kota: "Kota Jayapura",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Hujan Sedang",
        malam: "Berawan Tebal",
        diniHari: "Hujan Petir",
      },
      suhu: "24 - 30",
      kelembapan: "65 - 95",
    },
    {
      kota: "Manokwari",
      prakiraanCuaca: {
        pagi: "Hujan Sedang",
        siang: "Hujan Ringan",
        malam: "Berawan Tebal",
        diniHari: "Cerah Berawan",
      },
      suhu: "25 - 31",
      kelembapan: "70 - 95",
    },
    {
      kota: "Pekanbaru",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Petir",
        malam: "Hujan Ringan",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 30",
      kelembapan: "65 - 95",
    },
    {
      kota: "Mamuju",
      prakiraanCuaca: {
        pagi: "Cerah Berawan",
        siang: "Hujan Sedang",
        malam: "Berawan Tebal",
        diniHari: "Hujan Ringan",
      },
      suhu: "25 - 32",
      kelembapan: "70 - 95",
    },
    {
      kota: "Makassar",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Ringan",
        malam: "Hujan Sedang",
        diniHari: "Berawan Tebal",
      },
      suhu: "25 - 32",
      kelembapan: "70 - 90",
    },
    {
      kota: "Kendari",
      prakiraanCuaca: {
        pagi: "Cerah",
        siang: "Hujan Ringan",
        malam: "Hujan Sedang",
        diniHari: "Cerah Berawan",
      },
      suhu: "24 - 30",
      kelembapan: "70 - 95",
    },
    {
      kota: "Manado",
      prakiraanCuaca: {
        pagi: "Hujan Sedang",
        siang: "Hujan Ringan",
        malam: "Hujan Petir",
        diniHari: "Berawan Tebal",
      },
      suhu: "23 - 30",
      kelembapan: "70 - 95",
    },
    {
      kota: "Padang",
      prakiraanCuaca: {
        pagi: "Berawan Tebal",
        siang: "Hujan Ringan",
        malam: "Cerah Berawan",
        diniHari: "Hujan Sedang",
      },
      suhu: "24 - 30",
      kelembapan: "80 - 90",
    },
    {
      kota: "Palembang",
      prakiraanCuaca: {
        pagi: "Hujan Ringan",
        siang: "Hujan Sedang",
        malam: "Hujan Petir",
        diniHari: "Kabut",
      },
      suhu: "24 - 29",
      kelembapan: "80 - 100",
    },
    {
      kota: "Medan",
      prakiraanCuaca: {
        pagi: "Hujan Sedang",
        siang: "Hujan Ringan",
        malam: "Hujan Petir",
        diniHari: "Berawan Tebal",
      },
      suhu: "24 - 32",
      kelembapan: "65 - 95",
    },
  ];
  