export const dataAktual = [
    {
      no: 1,
      bandaraStasiun: "Maimun Saleh - Sabang",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Barat Daya",
      kecepatanAngin: 18.5,
      jarakPandang: 8.0,
      cuaca: "Berawan",
      suhu: 28,
      titikEmbun: 23,
      tekananUdara: 1008,
    },
    {
      no: 2,
      bandaraStasiun: "Sultan Iskandar Muda - Banda Aceh",
      waktuPengamatan: "2024-06-22 17:30:00 WIB",
      arahAngin: "Tenggara",
      kecepatanAngin: 20.4,
      jarakPandang: 10,
      cuaca: "Hujan ringan",
      suhu: 28,
      titikEmbun: 22,
      tekananUdara: 1006,
    },
    {
      no: 3,
      bandaraStasiun: "Cut Nyak Dien Nagan Raya - Meulaboh, NAD",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Barat",
      kecepatanAngin: 24.1,
      jarakPandang: 6.0,
      cuaca: "Berawan",
      suhu: 28,
      titikEmbun: 26,
      tekananUdara: 1009,
    },
    {
      no: 4,
      bandaraStasiun: "Malikus Saleh - Lhokseumawe",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Timur Laut",
      kecepatanAngin: 9.3,
      jarakPandang: 9.0,
      cuaca: "Cerah - berawan",
      suhu: 31,
      titikEmbun: 24,
      tekananUdara: 1006,
    },
    {
      no: 5,
      bandaraStasiun: "Binaka - Gunung Sitoli",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Tenang",
      kecepatanAngin: 0.0,
      jarakPandang: 9.0,
      cuaca: "Berawan",
      suhu: 30,
      titikEmbun: 24,
      tekananUdara: 1008,
    },
    {
      no: 6,
      bandaraStasiun: "Kualanamu International Airport - Deli Serdang",
      waktuPengamatan: "2024-06-22 17:30:00 WIB",
      arahAngin: "Tenggara",
      kecepatanAngin: 9.3,
      jarakPandang: 10,
      cuaca: "Berawan",
      suhu: 30,
      titikEmbun: 26,
      tekananUdara: 1007,
    },
    {
      no: 7,
      bandaraStasiun: "Dr. Ferdinand Lumban Tobing - Pinangsori (Sibolga)",
      waktuPengamatan: "2024-06-22 16:00:00 WIB",
      arahAngin: "Barat Laut",
      kecepatanAngin: 7.4,
      jarakPandang: 10,
      cuaca: "Cerah - berawan",
      suhu: 30,
      titikEmbun: 23,
      tekananUdara: 1007,
    },
    {
      no: 8,
      bandaraStasiun: "Soekarno-Hatta - Tangerang",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Timur",
      kecepatanAngin: 12.3,
      jarakPandang: 10,
      cuaca: "Berawan",
      suhu: 31,
      titikEmbun: 25,
      tekananUdara: 1006,
    },
    {
      no: 9,
      bandaraStasiun: "Halim Perdanakusuma - Jakarta",
      waktuPengamatan: "2024-06-22 17:30:00 WIB",
      arahAngin: "Timur Laut",
      kecepatanAngin: 15.6,
      jarakPandang: 9,
      cuaca: "Cerah",
      suhu: 30,
      titikEmbun: 24,
      tekananUdara: 1007,
    },
    {
      no: 10,
      bandaraStasiun: "Husein Sastranegara - Bandung",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Selatan",
      kecepatanAngin: 10.2,
      jarakPandang: 8,
      cuaca: "Berawan",
      suhu: 28,
      titikEmbun: 22,
      tekananUdara: 1010,
    },
    {
      no: 11,
      bandaraStasiun: "Adi Sucipto - Yogyakarta",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Barat",
      kecepatanAngin: 14.8,
      jarakPandang: 7,
      cuaca: "Hujan",
      suhu: 27,
      titikEmbun: 24,
      tekananUdara: 1009,
    },
    {
      no: 12,
      bandaraStasiun: "Juanda - Surabaya",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Utara",
      kecepatanAngin: 20.5,
      jarakPandang: 10,
      cuaca: "Cerah",
      suhu: 32,
      titikEmbun: 26,
      tekananUdara: 1005,
    },
    {
      no: 13,
      bandaraStasiun: "Ngurah Rai - Bali",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Barat Laut",
      kecepatanAngin: 18.1,
      jarakPandang: 8,
      cuaca: "Berawan",
      suhu: 29,
      titikEmbun: 25,
      tekananUdara: 1008,
    },
    {
      no: 14,
      bandaraStasiun: "Lombok International Airport - Lombok",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Timur",
      kecepatanAngin: 17.6,
      jarakPandang: 10,
      cuaca: "Hujan ringan",
      suhu: 30,
      titikEmbun: 24,
      tekananUdara: 1006,
    },
    {
      no: 15,
      bandaraStasiun: "Sultan Hasanuddin - Makassar",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Selatan",
      kecepatanAngin: 22.3,
      jarakPandang: 9,
      cuaca: "Berawan",
      suhu: 31,
      titikEmbun: 26,
      tekananUdara: 1007,
    },
    {
      no: 16,
      bandaraStasiun: "Sam Ratulangi - Manado",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Utara",
      kecepatanAngin: 12.9,
      jarakPandang: 10,
      cuaca: "Cerah",
      suhu: 32,
      titikEmbun: 24,
      tekananUdara: 1005,
    },
    {
      no: 17,
      bandaraStasiun: "Pattimura - Ambon",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Barat",
      kecepatanAngin: 16.4,
      jarakPandang: 9,
      cuaca: "Berawan",
      suhu: 29,
      titikEmbun: 25,
      tekananUdara: 1008,
    },
    {
      no: 18,
      bandaraStasiun: "Frans Kaisiepo - Biak",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Timur",
      kecepatanAngin: 13.2,
      jarakPandang: 8,
      cuaca: "Berawan",
      suhu: 28,
      titikEmbun: 24,
      tekananUdara: 1010,
    },
    {
      no: 19,
      bandaraStasiun: "Sentani - Jayapura",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Barat",
      kecepatanAngin: 14.7,
      jarakPandang: 7,
      cuaca: "Hujan",
      suhu: 27,
      titikEmbun: 24,
      tekananUdara: 1009,
    },
    {
      no: 20,
      bandaraStasiun: "Tjilik Riwut - Palangkaraya",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Timur",
      kecepatanAngin: 15.3,
      jarakPandang: 9,
      cuaca: "Berawan",
      suhu: 30,
      titikEmbun: 26,
      tekananUdara: 1006,
    },
    {
      no: 21,
      bandaraStasiun: "Supadio - Pontianak",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Selatan",
      kecepatanAngin: 16.8,
      jarakPandang: 10,
      cuaca: "Cerah",
      suhu: 31,
      titikEmbun: 25,
      tekananUdara: 1007,
    },
    {
      no: 22,
      bandaraStasiun: "Syamsudin Noor - Banjarmasin",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Barat Daya",
      kecepatanAngin: 18.5,
      jarakPandang: 8,
      cuaca: "Berawan",
      suhu: 29,
      titikEmbun: 23,
      tekananUdara: 1008,
    },
    {
      no: 23,
      bandaraStasiun: "Sepinggan - Balikpapan",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Tenggara",
      kecepatanAngin: 20.4,
      jarakPandang: 10,
      cuaca: "Hujan ringan",
      suhu: 28,
      titikEmbun: 22,
      tekananUdara: 1006,
    },
    {
      no: 24,
      bandaraStasiun: "Juwata - Tarakan",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Barat",
      kecepatanAngin: 24.1,
      jarakPandang: 6,
      cuaca: "Berawan",
      suhu: 28,
      titikEmbun: 26,
      tekananUdara: 1009,
    },
    {
      no: 25,
      bandaraStasiun: "Tanjung Harapan - Tanjung Selor",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Timur Laut",
      kecepatanAngin: 9.3,
      jarakPandang: 9,
      cuaca: "Cerah - berawan",
      suhu: 31,
      titikEmbun: 24,
      tekananUdara: 1006,
    },
    {
      no: 26,
      bandaraStasiun: "Batu Licin - Tanah Bumbu",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Tenang",
      kecepatanAngin: 0.0,
      jarakPandang: 9,
      cuaca: "Berawan",
      suhu: 30,
      titikEmbun: 24,
      tekananUdara: 1008,
    },
    {
      no: 27,
      bandaraStasiun: "Beringin - Muara Teweh",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Tenggara",
      kecepatanAngin: 9.3,
      jarakPandang: 10,
      cuaca: "Berawan",
      suhu: 30,
      titikEmbun: 26,
      tekananUdara: 1007,
    },
    {
      no: 28,
      bandaraStasiun: "Iskandar - Pangkalan Bun",
      waktuPengamatan: "2024-06-22 17:00:00 WIB",
      arahAngin: "Barat Laut",
      kecepatanAngin: 7.4,
      jarakPandang: 10,
      cuaca: "Cerah - berawan",
      suhu: 30,
      titikEmbun: 23,
      tekananUdara: 1007,
    },
    {
      no: 29,
      bandaraStasiun: "Halim Perdanakusuma - Jakarta",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Timur Laut",
      kecepatanAngin: 15.6,
      jarakPandang: 9,
      cuaca: "Cerah",
      suhu: 30,
      titikEmbun: 24,
      tekananUdara: 1007,
    },
    {
      no: 30,
      bandaraStasiun: "Husein Sastranegara - Bandung",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Selatan",
      kecepatanAngin: 10.2,
      jarakPandang: 8,
      cuaca: "Berawan",
      suhu: 28,
      titikEmbun: 22,
      tekananUdara: 1010,
    },
    {
      no: 31,
      bandaraStasiun: "Adi Sucipto - Yogyakarta",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat",
      kecepatanAngin: 14.8,
      jarakPandang: 7,
      cuaca: "Hujan",
      suhu: 27,
      titikEmbun: 24,
      tekananUdara: 1009,
    },
    {
      no: 32,
      bandaraStasiun: "Juanda - Surabaya",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Utara",
      kecepatanAngin: 20.5,
      jarakPandang: 10,
      cuaca: "Cerah",
      suhu: 32,
      titikEmbun: 26,
      tekananUdara: 1005,
    },
    {
      no: 33,
      bandaraStasiun: "Ngurah Rai - Bali",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat Laut",
      kecepatanAngin: 18.1,
      jarakPandang: 8,
      cuaca: "Berawan",
      suhu: 29,
      titikEmbun: 25,
      tekananUdara: 1008,
    },
    {
      no: 34,
      bandaraStasiun: "Lombok International Airport - Lombok",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Timur",
      kecepatanAngin: 17.6,
      jarakPandang: 10,
      cuaca: "Hujan ringan",
      suhu: 30,
      titikEmbun: 24,
      tekananUdara: 1006,
    },
    {
      no: 35,
      bandaraStasiun: "Sultan Hasanuddin - Makassar",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Selatan",
      kecepatanAngin: 22.3,
      jarakPandang: 9,
      cuaca: "Berawan",
      suhu: 31,
      titikEmbun: 26,
      tekananUdara: 1007,
    },
    {
      no: 36,
      bandaraStasiun: "Sam Ratulangi - Manado",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Utara",
      kecepatanAngin: 12.9,
      jarakPandang: 10,
      cuaca: "Cerah",
      suhu: 32,
      titikEmbun: 24,
      tekananUdara: 1005,
    },
    {
      no: 37,
      bandaraStasiun: "Pattimura - Ambon",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat",
      kecepatanAngin: 16.4,
      jarakPandang: 9,
      cuaca: "Berawan",
      suhu: 29,
      titikEmbun: 25,
      tekananUdara: 1008,
    },
    {
      no: 38,
      bandaraStasiun: "Frans Kaisiepo - Biak",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Timur",
      kecepatanAngin: 13.2,
      jarakPandang: 8,
      cuaca: "Berawan",
      suhu: 28,
      titikEmbun: 24,
      tekananUdara: 1010,
    },
    {
      no: 39,
      bandaraStasiun: "Sentani - Jayapura",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat",
      kecepatanAngin: 14.7,
      jarakPandang: 7,
      cuaca: "Hujan",
      suhu: 27,
      titikEmbun: 24,
      tekananUdara: 1009,
    },
    {
      no: 40,
      bandaraStasiun: "Tjilik Riwut - Palangkaraya",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Timur",
      kecepatanAngin: 15.3,
      jarakPandang: 9,
      cuaca: "Berawan",
      suhu: 30,
      titikEmbun: 26,
      tekananUdara: 1006,
    },
    {
      no: 41,
      bandaraStasiun: "Supadio - Pontianak",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Selatan",
      kecepatanAngin: 16.8,
      jarakPandang: 10,
      cuaca: "Cerah",
      suhu: 31,
      titikEmbun: 25,
      tekananUdara: 1007,
    },
    {
      no: 42,
      bandaraStasiun: "Syamsudin Noor - Banjarmasin",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat Daya",
      kecepatanAngin: 18.5,
      jarakPandang: 8,
      cuaca: "Berawan",
      suhu: 29,
      titikEmbun: 23,
      tekananUdara: 1008,
    },
    {
      no: 43,
      bandaraStasiun: "Sepinggan - Balikpapan",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Tenggara",
      kecepatanAngin: 20.4,
      jarakPandang: 10,
      cuaca: "Hujan ringan",
      suhu: 28,
      titikEmbun: 22,
      tekananUdara: 1006,
    },
    {
      no: 44,
      bandaraStasiun: "Juwata - Tarakan",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat",
      kecepatanAngin: 24.1,
      jarakPandang: 6,
      cuaca: "Berawan",
      suhu: 28,
      titikEmbun: 26,
      tekananUdara: 1009,
    },
    {
      no: 45,
      bandaraStasiun: "Tanjung Harapan - Tanjung Selor",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Timur Laut",
      kecepatanAngin: 9.3,
      jarakPandang: 9,
      cuaca: "Cerah - berawan",
      suhu: 31,
      titikEmbun: 24,
      tekananUdara: 1006,
    },
    {
      no: 46,
      bandaraStasiun: "Batu Licin - Tanah Bumbu",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Tenang",
      kecepatanAngin: 0.0,
      jarakPandang: 9,
      cuaca: "Berawan",
      suhu: 30,
      titikEmbun: 24,
      tekananUdara: 1008,
    },
    {
      no: 47,
      bandaraStasiun: "Beringin - Muara Teweh",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Tenggara",
      kecepatanAngin: 9.3,
      jarakPandang: 10,
      cuaca: "Berawan",
      suhu: 30,
      titikEmbun: 26,
      tekananUdara: 1007,
    },
    {
      no: 48,
      bandaraStasiun: "Iskandar - Pangkalan Bun",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat Laut",
      kecepatanAngin: 7.4,
      jarakPandang: 10,
      cuaca: "Cerah - berawan",
      suhu: 30,
      titikEmbun: 23,
      tekananUdara: 1007,
    },
    {
      no: 49,
      bandaraStasiun: "Mutiara - Palu",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Selatan",
      kecepatanAngin: 12.3,
      jarakPandang: 10,
      cuaca: "Cerah",
      suhu: 31,
      titikEmbun: 24,
      tekananUdara: 1006,
    },
    {
      no: 50,
      bandaraStasiun: "Syamsudin Noor - Banjarmasin",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat Daya",
      kecepatanAngin: 18.5,
      jarakPandang: 8,
      cuaca: "Berawan",
      suhu: 29,
      titikEmbun: 23,
      tekananUdara: 1008,
    },
    {
      no: 51,
      bandaraStasiun: "Sepinggan - Balikpapan",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Tenggara",
      kecepatanAngin: 20.4,
      jarakPandang: 10,
      cuaca: "Hujan ringan",
      suhu: 28,
      titikEmbun: 22,
      tekananUdara: 1006,
    },
    {
      no: 52,
      bandaraStasiun: "Juwata - Tarakan",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat",
      kecepatanAngin: 24.1,
      jarakPandang: 6,
      cuaca: "Berawan",
      suhu: 28,
      titikEmbun: 26,
      tekananUdara: 1009,
    },
    {
      no: 53,
      bandaraStasiun: "Tanjung Harapan - Tanjung Selor",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Timur Laut",
      kecepatanAngin: 9.3,
      jarakPandang: 9,
      cuaca: "Cerah - berawan",
      suhu: 31,
      titikEmbun: 24,
      tekananUdara: 1006,
    },
    {
      no: 54,
      bandaraStasiun: "Batu Licin - Tanah Bumbu",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Tenang",
      kecepatanAngin: 0.0,
      jarakPandang: 9,
      cuaca: "Berawan",
      suhu: 30,
      titikEmbun: 24,
      tekananUdara: 1008,
    },
    {
      no: 55,
      bandaraStasiun: "Beringin - Muara Teweh",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Tenggara",
      kecepatanAngin: 9.3,
      jarakPandang: 10,
      cuaca: "Berawan",
      suhu: 30,
      titikEmbun: 26,
      tekananUdara: 1007,
    },
    {
      no: 56,
      bandaraStasiun: "Iskandar - Pangkalan Bun",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat Laut",
      kecepatanAngin: 7.4,
      jarakPandang: 10,
      cuaca: "Cerah - berawan",
      suhu: 30,
      titikEmbun: 23,
      tekananUdara: 1007,
    },
    {
      no: 57,
      bandaraStasiun: "Mutiara - Palu",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Selatan",
      kecepatanAngin: 12.3,
      jarakPandang: 10,
      cuaca: "Cerah",
      suhu: 31,
      titikEmbun: 24,
      tekananUdara: 1006,
    },
    {
      no: 58,
      bandaraStasiun: "Syamsudin Noor - Banjarmasin",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat Daya",
      kecepatanAngin: 18.5,
      jarakPandang: 8,
      cuaca: "Berawan",
      suhu: 29,
      titikEmbun: 23,
      tekananUdara: 1008,
    },
    {
      no: 59,
      bandaraStasiun: "Sepinggan - Balikpapan",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Tenggara",
      kecepatanAngin: 20.4,
      jarakPandang: 10,
      cuaca: "Hujan ringan",
      suhu: 28,
      titikEmbun: 22,
      tekananUdara: 1006,
    },
    {
      no: 60,
      bandaraStasiun: "Juwata - Tarakan",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat",
      kecepatanAngin: 24.1,
      jarakPandang: 6,
      cuaca: "Berawan",
      suhu: 28,
      titikEmbun: 26,
      tekananUdara: 1009,
    },
    {
      no: 61,
      bandaraStasiun: "Tanjung Harapan - Tanjung Selor",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Timur Laut",
      kecepatanAngin: 9.3,
      jarakPandang: 9,
      cuaca: "Cerah - berawan",
      suhu: 31,
      titikEmbun: 24,
      tekananUdara: 1006,
    },
    {
      no: 62,
      bandaraStasiun: "Batu Licin - Tanah Bumbu",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Tenang",
      kecepatanAngin: 0.0,
      jarakPandang: 9,
      cuaca: "Berawan",
      suhu: 30,
      titikEmbun: 24,
      tekananUdara: 1008,
    },
    {
      no: 63,
      bandaraStasiun: "Beringin - Muara Teweh",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Tenggara",
      kecepatanAngin: 9.3,
      jarakPandang: 10,
      cuaca: "Berawan",
      suhu: 30,
      titikEmbun: 26,
      tekananUdara: 1007,
    },
    {
      no: 64,
      bandaraStasiun: "Iskandar - Pangkalan Bun",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat Laut",
      kecepatanAngin: 7.4,
      jarakPandang: 10,
      cuaca: "Cerah - berawan",
      suhu: 30,
      titikEmbun: 23,
      tekananUdara: 1007,
    },
    {
      no: 65,
      bandaraStasiun: "Mutiara - Palu",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Selatan",
      kecepatanAngin: 12.3,
      jarakPandang: 10,
      cuaca: "Cerah",
      suhu: 31,
      titikEmbun: 24,
      tekananUdara: 1006,
    },
    {
      no: 66,
      bandaraStasiun: "Syamsudin Noor - Banjarmasin",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat Daya",
      kecepatanAngin: 18.5,
      jarakPandang: 8,
      cuaca: "Berawan",
      suhu: 29,
      titikEmbun: 23,
      tekananUdara: 1008,
    },
    {
      no: 67,
      bandaraStasiun: "Sepinggan - Balikpapan",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Tenggara",
      kecepatanAngin: 20.4,
      jarakPandang: 10,
      cuaca: "Hujan ringan",
      suhu: 28,
      titikEmbun: 22,
      tekananUdara: 1006,
    },
    {
      no: 68,
      bandaraStasiun: "Juwata - Tarakan",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Barat",
      kecepatanAngin: 24.1,
      jarakPandang: 6,
      cuaca: "Berawan",
      suhu: 28,
      titikEmbun: 26,
      tekananUdara: 1009,
    },
    {
      no: 69,
      bandaraStasiun: "Tanjung Harapan - Tanjung Selor",
      waktuPengamatan: "2024-06-22 18:00:00 WIB",
      arahAngin: "Timur Laut",
      kecepatanAngin: 9.3,
      jarakPandang: 9,
      cuaca: "Cerah - berawan",
      suhu: 31,
      titikEmbun: 24,
      tekananUdara: 1006,
    },
];
     
  