export const times = [
  { key: "", label: "Reset filter waktu" },
  { key: "1", label: "1 jam yang akan datang" },
  { key: "2", label: "2 jam yang akan datang" },
  { key: "3", label: "3 jam yang akan datang" },
  { key: "4", label: "4 jam yang akan datang" },
  { key: "5", label: "5 jam yang akan datang" },
  { key: "6", label: "6 jam yang akan datang" },
  { key: "7", label: "7 jam yang akan datang" },
  { key: "8", label: "8 jam yang akan datang" },
  { key: "9", label: "9 jam yang akan datang" },
  { key: "10", label: "10 jam yang akan datang" },
  { key: "11", label: "11 jam yang akan datang" },
  { key: "12", label: "12 jam yang akan datang" },
];

export const prakiraanCuaca = [
  {
    key: 1,
    bandaraStasiun: "Maimun Saleh - Sabang",
    waktuPrakiraan: "00:00",
    arahAngin: "Barat Daya",
    kecepatanAnginKmJam: 13.0,
    jarakPandangKm: 7.0,
    cuaca: "Cerah - berawan",
    probabilitas: null,
  },
  {
    key: 2,
    bandaraStasiun: "Sultan Iskandar Muda - Banda Aceh",
    waktuPrakiraan: "01:00",
    arahAngin: "Tenggara",
    kecepatanAnginKmJam: 7.4,
    jarakPandangKm: 10,
    cuaca: "Cerah - berawan",
    probabilitas: null,
  },
  {
    key: 3,
    bandaraStasiun: "Cut Nyak Dien Nagan Raya - Meulaboh, NAD",
    waktuPrakiraan: "02:00",
    arahAngin: "Timur Laut",
    kecepatanAnginKmJam: 5.6,
    jarakPandangKm: 6.0,
    cuaca: "Berawan",
    probabilitas: null,
  },
  {
    key: 4,
    bandaraStasiun: "Malikus Saleh - Lhokseumawe",
    waktuPrakiraan: "03:00",
    arahAngin: "Barat Daya",
    kecepatanAnginKmJam: 5.6,
    jarakPandangKm: 6.0,
    cuaca: "Cerah - berawan",
    probabilitas: null,
  },
  {
    key: 5,
    bandaraStasiun: "Binaka - Gunung Sitoli",
    waktuPrakiraan: "04:00",
    arahAngin: "Variabel",
    kecepatanAnginKmJam: 9.3,
    jarakPandangKm: 4.0,
    cuaca: "Udara kabur",
    probabilitas: null,
  },
  {
    key: 6,
    bandaraStasiun: "Kualanamu International Airport - Deli Serdang",
    waktuPrakiraan: "05:00",
    arahAngin: "Variabel",
    kecepatanAnginKmJam: 9.3,
    jarakPandangKm: 5.0,
    cuaca: "Udara kabur",
    probabilitas: null,
  },
  {
    key: 7,
    bandaraStasiun: "Dr. Ferdinand Lumban Tobing - Pinangsori (Sibolga)",
    waktuPrakiraan: "06:00",
    arahAngin: "Variabel",
    kecepatanAnginKmJam: 9.3,
    jarakPandangKm: 4.0,
    cuaca: "Udara kabur",
    probabilitas: null,
  },
  {
    key: 8,
    bandaraStasiun: "Silangit - Tapanuli Utara",
    waktuPrakiraan: "07:00",
    arahAngin: "Variabel",
    kecepatanAnginKmJam: 7.4,
    jarakPandangKm: 3.0,
    cuaca: "Halimun",
    probabilitas: null,
  },
  {
    key: 9,
    bandaraStasiun: "Aek Godang - Padang Sidempuan",
    waktuPrakiraan: "08:00",
    arahAngin: "Barat",
    kecepatanAnginKmJam: 7.4,
    jarakPandangKm: 4.0,
    cuaca: "Udara kabur",
    probabilitas: null,
  },
  {
    key: 10,
    bandaraStasiun: "Minangkabau International Airport - Padang",
    waktuPrakiraan: "09:00",
    arahAngin: "Barat Laut",
    kecepatanAnginKmJam: 12.0,
    jarakPandangKm: 8.0,
    cuaca: "Cerah - berawan",
    probabilitas: null,
  },
  {
    key: 11,
    bandaraStasiun: "Sultan Thaha - Jambi",
    waktuPrakiraan: "10:00",
    arahAngin: "Timur",
    kecepatanAnginKmJam: 10.0,
    jarakPandangKm: 5.0,
    cuaca: "Udara kabur",
    probabilitas: null,
  },
  {
    key: 12,
    bandaraStasiun: "Sultan Mahmud Badaruddin II - Palembang",
    waktuPrakiraan: "11:00",
    arahAngin: "Selatan",
    kecepatanAnginKmJam: 8.0,
    jarakPandangKm: 7.0,
    cuaca: "Berawan",
    probabilitas: null,
  },
  {
    key: 13,
    bandaraStasiun: "Radin Inten II - Lampung",
    waktuPrakiraan: "12:00",
    arahAngin: "Barat Laut",
    kecepatanAnginKmJam: 6.0,
    jarakPandangKm: 5.0,
    cuaca: "Cerah - berawan",
    probabilitas: null,
  },
  {
    key: 14,
    bandaraStasiun: "Soekarno-Hatta International Airport - Tangerang",
    waktuPrakiraan: "13:00",
    arahAngin: "Barat",
    kecepatanAnginKmJam: 15.0,
    jarakPandangKm: 10.0,
    cuaca: "Cerah",
    probabilitas: null,
  },
  {
    key: 15,
    bandaraStasiun: "Husein Sastranegara - Bandung",
    waktuPrakiraan: "14:00",
    arahAngin: "Timur",
    kecepatanAnginKmJam: 10.0,
    jarakPandangKm: 6.0,
    cuaca: "Cerah - berawan",
    probabilitas: null,
  },
  {
    key: 16,
    bandaraStasiun: "Adisutjipto - Yogyakarta",
    waktuPrakiraan: "15:00",
    arahAngin: "Barat",
    kecepatanAnginKmJam: 12.0,
    jarakPandangKm: 8.0,
    cuaca: "Berawan",
    probabilitas: null,
  },
  {
    key: 17,
    bandaraStasiun: "Ahmad Yani - Semarang",
    waktuPrakiraan: "16:00",
    arahAngin: "Selatan",
    kecepatanAnginKmJam: 8.0,
    jarakPandangKm: 7.0,
    cuaca: "Cerah",
    probabilitas: null,
  },
  {
    key: 18,
    bandaraStasiun: "Juanda - Surabaya",
    waktuPrakiraan: "17:00",
    arahAngin: "Barat Laut",
    kecepatanAnginKmJam: 14.0,
    jarakPandangKm: 10.0,
    cuaca: "Cerah - berawan",
    probabilitas: null,
  },
  {
    key: 19,
    bandaraStasiun: "Adi Soemarmo - Solo",
    waktuPrakiraan: "18:00",
    arahAngin: "Timur Laut",
    kecepatanAnginKmJam: 9.0,
    jarakPandangKm: 6.0,
    cuaca: "Berawan",
    probabilitas: null,
  },
  {
    key: 20,
    bandaraStasiun: "Abdul Rachman Saleh - Malang",
    waktuPrakiraan: "19:00",
    arahAngin: "Barat Daya",
    kecepatanAnginKmJam: 7.0,
    jarakPandangKm: 5.0,
    cuaca: "Cerah",
    probabilitas: null,
  },
  {
    key: 21,
    bandaraStasiun: "Ngurah Rai - Denpasar",
    waktuPrakiraan: "20:00",
    arahAngin: "Selatan",
    kecepatanAnginKmJam: 10.0,
    jarakPandangKm: 9.0,
    cuaca: "Cerah - berawan",
    probabilitas: null,
  },
  {
    key: 22,
    bandaraStasiun: "Lombok International Airport - Lombok",
    waktuPrakiraan: "21:00",
    arahAngin: "Barat Laut",
    kecepatanAnginKmJam: 11.0,
    jarakPandangKm: 8.0,
    cuaca: "Berawan",
    probabilitas: null,
  },
  {
    key: 23,
    bandaraStasiun: "El Tari - Kupang",
    waktuPrakiraan: "22:00",
    arahAngin: "Timur",
    kecepatanAnginKmJam: 13.0,
    jarakPandangKm: 7.0,
    cuaca: "Cerah",
    probabilitas: null,
  },
  {
    key: 24,
    bandaraStasiun: "Sepinggan - Balikpapan",
    waktuPrakiraan: "23:00",
    arahAngin: "Barat",
    kecepatanAnginKmJam: 14.0,
    jarakPandangKm: 10.0,
    cuaca: "Cerah - berawan",
    probabilitas: null,
  },
  {
    key: 25,
    bandaraStasiun: "Sultan Aji Muhammad Sulaiman - Samarinda",
    waktuPrakiraan: "00:00",
    arahAngin: "Timur Laut",
    kecepatanAnginKmJam: 12.0,
    jarakPandangKm: 8.0,
    cuaca: "Berawan",
    probabilitas: null,
  },
  {
    key: 26,
    bandaraStasiun: "Syamsudin Noor - Banjarmasin",
    waktuPrakiraan: "01:00",
    arahAngin: "Selatan",
    kecepatanAnginKmJam: 10.0,
    jarakPandangKm: 7.0,
    cuaca: "Cerah - berawan",
    probabilitas: null,
  },
  {
    key: 27,
    bandaraStasiun: "Sultan Hasanuddin - Makassar",
    waktuPrakiraan: "02:00",
    arahAngin: "Barat Laut",
    kecepatanAnginKmJam: 13.0,
    jarakPandangKm: 9.0,
    cuaca: "Cerah",
    probabilitas: null,
  },
  {
    key: 28,
    bandaraStasiun: "Mopah - Merauke",
    waktuPrakiraan: "03:00",
    arahAngin: "Timur",
    kecepatanAnginKmJam: 15.0,
    jarakPandangKm: 10.0,
    cuaca: "Cerah - berawan",
    probabilitas: null,
  },
  {
    key: 29,
    bandaraStasiun: "Sentani - Jayapura",
    waktuPrakiraan: "04:00",
    arahAngin: "Barat",
    kecepatanAnginKmJam: 12.0,
    jarakPandangKm: 8.0,
    cuaca: "Berawan",
    probabilitas: null,
  },
  {
    key: 30,
    bandaraStasiun: "Domine Eduard Osok - Sorong",
    waktuPrakiraan: "05:00",
    arahAngin: "Selatan",
    kecepatanAnginKmJam: 10.0,
    jarakPandangKm: 7.0,
    cuaca: "Cerah",
    probabilitas: null,
  },
  {
    key: 31,
    bandaraStasiun: "Halim Perdanakusuma - Jakarta",
    waktuPrakiraan: "06:00",
    arahAngin: "Timur",
    kecepatanAnginKmJam: 12.0,
    jarakPandangKm: 10.0,
    cuaca: "Cerah",
    probabilitas: 20,
  },
  {
    key: 32,
    bandaraStasiun: "Adi Sumarmo - Solo",
    waktuPrakiraan: "07:00",
    arahAngin: "Barat Laut",
    kecepatanAnginKmJam: 14.0,
    jarakPandangKm: 9.0,
    cuaca: "Berawan",
    probabilitas: null,
  },
  {
    key: 33,
    bandaraStasiun: "Supadio - Pontianak",
    waktuPrakiraan: "08:00",
    arahAngin: "Selatan",
    kecepatanAnginKmJam: 8.0,
    jarakPandangKm: 7.0,
    cuaca: "Cerah - berawan",
    probabilitas: 50,
  },
  {
    key: 34,
    bandaraStasiun: "Sultan Syarif Kasim II - Pekanbaru",
    waktuPrakiraan: "09:00",
    arahAngin: "Timur Laut",
    kecepatanAnginKmJam: 6.0,
    jarakPandangKm: 8.0,
    cuaca: "Hujan ringan",
    probabilitas: 80,
  },
  {
    key: 35,
    bandaraStasiun: "H.A.S. Hanandjoeddin - Belitung",
    waktuPrakiraan: "10:00",
    arahAngin: "Barat",
    kecepatanAnginKmJam: 10.0,
    jarakPandangKm: 6.0,
    cuaca: "Cerah",
    probabilitas: 10,
  },
  {
    key: 36,
    bandaraStasiun: "Fatmawati Soekarno - Bengkulu",
    waktuPrakiraan: "11:00",
    arahAngin: "Barat Daya",
    kecepatanAnginKmJam: 12.0,
    jarakPandangKm: 7.0,
    cuaca: "Berawan",
    probabilitas: null,
  },
  {
    key: 37,
    bandaraStasiun: "Depati Amir - Pangkalpinang",
    waktuPrakiraan: "12:00",
    arahAngin: "Timur",
    kecepatanAnginKmJam: 14.0,
    jarakPandangKm: 9.0,
    cuaca: "Hujan ringan",
    probabilitas: 70,
  },
  {
    key: 38,
    bandaraStasiun: "Tjilik Riwut - Palangkaraya",
    waktuPrakiraan: "13:00",
    arahAngin: "Selatan",
    kecepatanAnginKmJam: 11.0,
    jarakPandangKm: 8.0,
    cuaca: "Cerah - berawan",
    probabilitas: 30,
  },
  {
    key: 39,
    bandaraStasiun: "Sultan Aji Muhammad Sulaiman - Balikpapan",
    waktuPrakiraan: "14:00",
    arahAngin: "Utara",
    kecepatanAnginKmJam: 15.0,
    jarakPandangKm: 10.0,
    cuaca: "Cerah",
    probabilitas: null,
  },
  {
    key: 40,
    bandaraStasiun: "Juwata - Tarakan",
    waktuPrakiraan: "15:00",
    arahAngin: "Barat",
    kecepatanAnginKmJam: 10.0,
    jarakPandangKm: 7.0,
    cuaca: "Cerah - berawan",
    probabilitas: 25,
  },
  {
    key: 41,
    bandaraStasiun: "Sultan Bantilan - Tolitoli",
    waktuPrakiraan: "16:00",
    arahAngin: "Timur Laut",
    kecepatanAnginKmJam: 8.0,
    jarakPandangKm: 6.0,
    cuaca: "Hujan ringan",
    probabilitas: 60,
  },
  {
    key: 42,
    bandaraStasiun: "Sam Ratulangi - Manado",
    waktuPrakiraan: "17:00",
    arahAngin: "Selatan",
    kecepatanAnginKmJam: 13.0,
    jarakPandangKm: 9.0,
    cuaca: "Cerah",
    probabilitas: null,
  },
  {
    key: 43,
    bandaraStasiun: "Frans Kaisiepo - Biak",
    waktuPrakiraan: "18:00",
    arahAngin: "Barat Laut",
    kecepatanAnginKmJam: 9.0,
    jarakPandangKm: 10.0,
    cuaca: "Berawan",
    probabilitas: 40,
  },
  {
    key: 44,
    bandaraStasiun: "Mopah - Merauke",
    waktuPrakiraan: "19:00",
    arahAngin: "Timur",
    kecepatanAnginKmJam: 11.0,
    jarakPandangKm: 8.0,
    cuaca: "Cerah - berawan",
    probabilitas: 30,
  },
  {
    key: 45,
    bandaraStasiun: "Pattimura - Ambon",
    waktuPrakiraan: "20:00",
    arahAngin: "Barat Daya",
    kecepatanAnginKmJam: 14.0,
    jarakPandangKm: 9.0,
    cuaca: "Cerah",
    probabilitas: 15,
  },
  {
    key: 46,
    bandaraStasiun: "Rendani - Manokwari",
    waktuPrakiraan: "21:00",
    arahAngin: "Barat",
    kecepatanAnginKmJam: 10.0,
    jarakPandangKm: 7.0,
    cuaca: "Berawan",
    probabilitas: null,
  },
  {
    key: 47,
    bandaraStasiun: "Dominique Edward Osok - Sorong",
    waktuPrakiraan: "22:00",
    arahAngin: "Utara",
    kecepatanAnginKmJam: 8.0,
    jarakPandangKm: 6.0,
    cuaca: "Cerah - berawan",
    probabilitas: 50,
  },
  {
    key: 48,
    bandaraStasiun: "Marinda - Raja Ampat",
    waktuPrakiraan: "23:00",
    arahAngin: "Selatan",
    kecepatanAnginKmJam: 12.0,
    jarakPandangKm: 10.0,
    cuaca: "Cerah",
    probabilitas: 20,
  },
  {
    key: 49,
    bandaraStasiun: "Sultan Iskandar Muda - Banda Aceh",
    waktuPrakiraan: "00:00",
    arahAngin: "Timur",
    kecepatanAnginKmJam: 14.0,
    jarakPandangKm: 9.0,
    cuaca: "Berawan",
    probabilitas: null,
  },
  {
    key: 50,
    bandaraStasiun: "Sultan Syarif Kasim II - Pekanbaru",
    waktuPrakiraan: "01:00",
    arahAngin: "Barat Daya",
    kecepatanAnginKmJam: 10.0,
    jarakPandangKm: 8.0,
    cuaca: "Cerah - berawan",
    probabilitas: 35,
  },
  {
    key: 51,
    bandaraStasiun: "Minangkabau - Padang",
    waktuPrakiraan: "02:00",
    arahAngin: "Timur",
    kecepatanAnginKmJam: 8.0,
    jarakPandangKm: 7.0,
    cuaca: "Hujan ringan",
    probabilitas: 70,
  },
  {
    key: 52,
    bandaraStasiun: "Mahmud Badaruddin II - Palembang",
    waktuPrakiraan: "03:00",
    arahAngin: "Barat Laut",
    kecepatanAnginKmJam: 12.0,
    jarakPandangKm: 10.0,
    cuaca: "Cerah",
    probabilitas: null,
  },
  {
    key: 53,
    bandaraStasiun: "Radin Inten II - Lampung",
    waktuPrakiraan: "04:00",
    arahAngin: "Selatan",
    kecepatanAnginKmJam: 9.0,
    jarakPandangKm: 8.0,
    cuaca: "Cerah - berawan",
    probabilitas: 45,
  },
  {
    key: 54,
    bandaraStasiun: "Adi Sutjipto - Yogyakarta",
    waktuPrakiraan: "05:00",
    arahAngin: "Barat",
    kecepatanAnginKmJam: 11.0,
    jarakPandangKm: 9.0,
    cuaca: "Cerah",
    probabilitas: 20,
  },
  {
    key: 55,
    bandaraStasiun: "Juanda - Surabaya",
    waktuPrakiraan: "06:00",
    arahAngin: "Timur Laut",
    kecepatanAnginKmJam: 10.0,
    jarakPandangKm: 10.0,
    cuaca: "Berawan",
    probabilitas: null,
  },
  {
    key: 56,
    bandaraStasiun: "Sultan Mahmud Badaruddin II - Palembang",
    waktuPrakiraan: "07:00",
    arahAngin: "Barat Daya",
    kecepatanAnginKmJam: 12.0,
    jarakPandangKm: 8.0,
    cuaca: "Hujan ringan",
    probabilitas: 75,
  },
  {
    key: 57,
    bandaraStasiun: "Husein Sastranegara - Bandung",
    waktuPrakiraan: "08:00",
    arahAngin: "Timur",
    kecepatanAnginKmJam: 10.0,
    jarakPandangKm: 7.0,
    cuaca: "Cerah",
    probabilitas: 10,
  },
  {
    key: 58,
    bandaraStasiun: "Soekarno-Hatta - Jakarta",
    waktuPrakiraan: "09:00",
    arahAngin: "Barat Laut",
    kecepatanAnginKmJam: 9.0,
    jarakPandangKm: 10.0,
    cuaca: "Berawan",
    probabilitas: null,
  },
  {
    key: 59,
    bandaraStasiun: "Ngurah Rai - Bali",
    waktuPrakiraan: "10:00",
    arahAngin: "Selatan",
    kecepatanAnginKmJam: 11.0,
    jarakPandangKm: 8.0,
    cuaca: "Cerah - berawan",
    probabilitas: 30,
  },
  {
    key: 60,
    bandaraStasiun: "Lombok International - Lombok",
    waktuPrakiraan: "11:00",
    arahAngin: "Barat",
    kecepatanAnginKmJam: 13.0,
    jarakPandangKm: 7.0,
    cuaca: "Hujan ringan",
    probabilitas: 80,
  },
];
