export const dataSiaranPers = [
    {
        id: 's1',
        image:'https://cdn.bmkg.go.id/Web/WhatsApp-Image-2024-06-20-at-09.53.57-250x150.jpeg',
        title: 'Hadapi Perubahan Iklim, Indonesia Dorong Pengamatan Sistematis',
        link: '/profil/publikasi-dan-informasi/siaran_pers/view/s1', // Contoh link
        tgl: "20 Jun 2024",
        penulis: "Dwi Herlambang Ade Putra",
        paragraf: [
            'BONN, GERMAN (20 Juni 2024)',
            '- Kepala Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) Dwikorita Karnawati menekankan pentingnya pengamatan sistem kebumian yang sistematis menghadapi perubahan iklim. Menurutnya, suhu permukaan bumi meningkat sangat cepat setiap tahunnya yang berdampak buruk pada kehidupan manusia dan seluruh mahluk hidup di Bumi.',
            'Berdasarkan laporan Organisasi Meteorologi Dunia (WMO), suhu permukaan global telah meningkat dengan cepat, dengan rata-rata tahunan mencapai 1,45 derajat Celcius pada tahun 2023 dibandingkan dengan baseline setelah era Revolusi Industri. Padahal di tahun 2020 lalu, menurut laporan WMO tentang keadaan iklim global, kenaikan rata-rata suhu global adalah 1,2 derajat celcius. Hal ini berarti hanya dalam beberapa tahun, ada peningkatan suhu permukaan yang signifikan.',
            '"Tahun 2023 tercatat sebagai tahun terpanas, dan informasi inihanya dapat diperoleh melalui pengamatan sistematis untuk fenomena kebumian. Tanpa pengamatan kebumian yang sistematis, informasi yang diberikan bisa menyesatkan atau salah. Pengamatan kebumian yang sistematis ini diperlukan baik di tingkat nasional, regional, maupun global," ungkap Dwikorita melalui sambungan online dalam Ocean and Climate Change Dialogue 2024 yang diselenggarakan oleh United Nation Framework Convention on Climate Change di Bonn, Jerman, Selasa (13/6/2024).',
            'Dwikorita mengatakan, pengataman sistematis sangat dibutuhkan untuk berbagai keperluan. Diantaranya, untuk memberikan data dukung dalam aksi adaptasi iklim, aksi mitigasi iklim, atau keputusan atau kebijakan apa pun terkait mitigasi dan adaptasi iklim. Pengamatan sistematis tersebut, lanjut dia, harus juga diikuti oleh tindakan yang sistematis di segala lini agar dampak panas ekstrem tersebut dan dampak perubahan iklim lainnya dapat ditangani secara efektif.',
            'Dicontohkan Dwikorita, informasi mengenai fenomena El Nino yang menyebabkan kenaikan panas laut yang meluas di Pasifik tropis bagian timur merupakan hasil pengamatan kebumian sistematis yang didukung juga oleh pemantauan satelit. Selain itu, prediksi Food and Agriculture Organization (FAO) mengenai ancaman krisis pangan pada tahun 2050 mendatang juga merupakan hasil dari pengamatan kebumian yang sistematis secara global, nasional, dan lokal. Singkatnya, tambah dia, pengamatan sistematis tersebut, memungkinkan seluruh negara di dunia untuk melakukan analisis dan prediksi lebih lanjut.',
            '"Analisis masa lalu merupakan cara untuk memvalidasi dampak dari peningkatan suhu yang berlangsung dan kondisi Bumi kekinian. Selanjutnya, pada analisisi lebih lanjut yang didasarkan pada data pengamatan sistematis dapat diketahui bahwa ternyata perubahan iklim memberi tekanan pada sumber daya air yang sudah langka, menghasilkan hotspot air. Nah, hal ini dapat ditangkap dan dianalisis lagi berdasarkan pengamatan sistematis," paparnya.',
            'Dwikorita menegaskan, peningkatan suhu global tidak dapat dianggap sepele. Tidak hanya berdampak pada suhu bumi yang makin panas, kondisi tersebut juga meningkatkan frekuensi bencana hidrometeorologi, kekeringan, buruknya kualitas udara, kebakaran hutan dan lahan, gelombang panas, risiko kesehatan, penurunan kualitas hidup, hingga ancaman kelangsungan hidup spesies di bumi. Situasi tersebut, lanjut Dwikorita, pada akhirnya tentu akan menganggu stabilitas perekonomian dan politik dunia.',
            'Dalam kesempatan tersebut, Dwikorita juga menyampaikan bahwa Indonesia meningkatkan jaringan pengamatan kebumian baik di laut maupun darat. Hal tersebut juga diiringi dengan peningkatan kapasitas pemrosesan data dan peningkatan penyebaran informasi kepada publik dan sektorpengguna.',
            '"Salah satu fokus pengamatan kami (Indonesia-red) terhadap dampak perubahan iklim adalah laut. Hal ini karena kunci dari perubahan iklim adalah laut, yang juga berinteraksi dengan atmosfer. Ini adalah upaya kami untuk memperkuat kapasitas prakiraan, prediksi ataupun proyeksi. Jadi ketika kita berbicara tentang dampak perubahan iklim, kita tidak bisa mengabaikan integrasi pengamatan laut dan atmosfer, mulai dari pemrosesan data, analisis, prediksi, dan proyeksinya, hingga penyebarluasan hasil analisis/ informasi utk berbagai kepentingan layanan, " paparnya.',
            'Dwikorita berharap The United Nations Framework Convention on Climate Change (UNFCC) menjadikan pengamatan sistematis untuk fenomena kebumian sebagai dasar negosiasi dan pengambilan kebijakan, guna mendukung negara-negara di dunia untuk mengambil tindakan sistematis untuk mengatasi perubahan iklim. Hal ini karena kebijakan yang dibuat tanpa mempertimbangkan pengamatan sistematis fenomena kebumian bisa menjadi sesuatu yang salah atau menyesatkan. (*)',
        ],
        dokumentasi: null
    },
    {
        id: 's2',
        image:'https://cdn.bmkg.go.id/Web/WhatsApp-Image-2024-06-17-at-14.21.44-250x150.jpeg',
        title: 'Dukung Percepatan Pembangunan Infrastruktur IKN, BMKG Gelar OMC di Kaltim',
        link: '/profil/publikasi-dan-informasi/siaran_pers/view/s2', // Contoh link
        tgl: "19 Jun 2024",
        penulis: "Dwi Herlambang Ade Putra",
        paragraf: [
            'JAKARTA (19 Juni 2024)',
            '- Kepala Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) Dwikorita Karnawati menjelaskan dalam rangka percepatan pembangunan infrastruktur penunjang Ibu Kota Negara (IKN) Nusantara, BMKG melaksanakan kegiatan Operasi Modifikasi Cuaca (OMC). Operasi ini dilakukan untuk mengurangi intensitas hujan di wilayah pembangunan IKN, Kalimantan Timur.',
            '"OMC untuk menunjang percepatan pembangunan infrastuktur seperti pembangunan Bandar Udara VVIP IKN dan jalan tol," kata Dwikorita di Jakarta, Rabu (19/6).',
            'Dwikorita menambahkan, berdasarkan hasil analisis prediksi curah hujan bulan Juni 2024, wilayah Kalimantan Timur khususnya wilayah IKN pada kategori menengah, dengan curah hujan bulanan berkisar antara 200 mm sampai 300 milimeter. Maka dalam rangka percepatan pembangunan infrastruktur, OMC bertujuan untuk memecah awan supaya meminimalisir terjadinya hujan yang dimaksimalkan antara 13-23 Juni 2024.',
            'Plt. Deputi Bidang Modifikasi Cuaca BMKG Tri Handoko Seto menambahkan hingga Rabu (19/6) telah dilaksanakan total enam hari kegiatan OMC. Dalam kurun waktu tersebut telah dilaksanakan sepuluh sorti penerbangan penyemaian awan dengan total 21 jam 25 menit penerbangan.',
            '"Total bahan semai yang telah digunakan untuk OMC adalah 8 ton NaCI powder dari total yang telah disiapkan sebanyak 16 ton," kata Seto.',
            'Selama kegiatan OMC berlangsung, penyemaian awan dilakukan pada daerah yang berpotensi menyebabkan hujan di area pembangunan infrastruktur penunjang IKN (Bandara VVIP IKN dan Jalan Tol).',
            'Pemilihan wilayah penyemaian awan setiap harinya diprioritaskan pada daerah upwind (arah datangnya angin masa udara) dengan tujuan agar awan hujan tidak masuk ke daerah target, yaitu area dilaksanakannya kegiatan pembangunan. Daerah seeding yang telah dilakukan meliputi Selat Makasar, Kabupaten Kutai Kartanegara dan Kabupaten Paser.',
            'Pelaksanaan OMC didukung oleh armada pesawat Casa 212-400 dengan registrasi A-2114 milik Skadron 4 TNI AU. "Kami berharap OMC akan memberikan dampak dan manfaat bagi masyarakat luas serta memitigasi risiko bencana yang terjadi," pungkasnya.',
        ],
        dokumentasi: null
    },
    {
        id: 's3',
        image:'https://cdn.bmkg.go.id/Web/WhatsApp-Image-2024-06-19-at-19.11.14-250x150.jpeg',
        title: 'Cegah Karhutla, BMKG Gelar Operasi Modifikasi Cuaca Serentak di 5 Provinsi',
        link: '/profil/publikasi-dan-informasi/siaran_pers/view/s3', // Contoh link
        tgl: " 19 Jun 2024",
        penulis: "Dwi Herlambang Ade Putra",
        paragraf: [
            'JAKARTA (19 Juni 2024)',
            ' - Kepala Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) Dwikorita Karnawati menjelaskan dalam rangka pengendalian Kebakaran Hutan dan Lahan (Karhutla), BMKG menggelar Operasi Modifikasi Cuaca (OMC) serentak di lima provinsi di wilayah Indonesia. Kelima provinsi tersebut ialah Riau, Jambi, Sumatra Selatan, Kalimantan Barat, dan Kalimantan Tengah.',
            '"OMC ini dilakukan dalam rangka bentuk antisipasi bencana kekeringan dan Karhutla," kata Dwikorita di Jakarta, Selasa (18/6).',
            'Adapun jadwal pelaksanaan OMC di Riau dilaksanakan pada 14 Juni-3 Juli 2024, Jambi 20 Juni-1 Juli 2024, Sumatra Selatan 3 Juli-12 Juli 2024, Kalimantan Barat 25 Juni-5 Juli 2024, dan Kalimantan Tengah tahap 5 Juli-15 Juli 2024.',
            'Lebih lanjut, berdasarkan hasil analisis dan monitoring BMKG, pada Juli hingga September pada provinsi target OMC diperkirakan mengalami kekeringan dan rawan terjadi Karhutla. Oleh karenanya OMC bertujuan untuk mengurangi dampak risiko yang dapat terjadi dan dapat menganggu kehidupan masyarakat.',
            '"OMC dilakukan untuk pembasahan lahan gambut untuk antisipasi dan mitigasi bencana Karhutla. Selain itu untuk mengisi kubah-kubah air yang berada di lahan gambut sehingga mencegah lahan gambut kering dan mudah terbakar karena telah dibasahi oleh hujan," ujarnya.',
            'Di sisi lain, Plt. Deputi Bidang Modifikasi Cuaca BMKG Tri Handoko Seto menjelaskan berdasarkan pantauan Sipongi, secara kumulatif dua hari terakhir di provinsi terkait target sudah mulai terdeteksi hotspot dengan derajat kepercayaan menengah hingga tinggi atau 2-3 titik per hari.',
            'Oleh karenanya, menurut Seto, pembasahan lahan gambut tersebut dilakukan sebelum daerah terdampak memasuki puncak musim kemarau. Pun, OMC ditujukan untuk menekan potensi lonjakan hotspot dan potensi luasan area gambut yang terbakar.',
            '"Saat ini sedang dilaksanakan OMC di Provinsi Riau sejak tanggal 14-18 Juni 2024 dan sudah menggunakan bahan semai NaCI powder sebanyak empat ton. Hingga hari ini, OMC di Riau telah dilaksanakan selama empat hari dengan rincian lima sorti penyemaian dengan total jam terbang 11 jam 35 menit," kata Seto.',
            'Kegiatan OMC di Provinsi Riau dimulai pada tanggal 14 Juni 2024 bekerjasama dengan TNI AU Lanud Sultan Syarif Kasim II dan pesawat Casa 212 registrasi A-2116 dari Skuadron Udara 4 Malang, Badan Penanggulangan Bencana Daerah (BPBD) Riau, dan PT. Riau Andalan Pulp and Paper (RAPP).',
        ],
        dokumentasi: null
    },
    {
        id: 's4',
        image:'https://cdn.bmkg.go.id/Web/H08_EH_Indonesia-14-250x150.png',
        title: 'BMKG: Waspada Potensi Cuaca Ekstrem meskipun Sebagian Besar Wilayah di Indonesia Telah Memasuki Musim Kemarau',
        link: '/profil/publikasi-dan-informasi/siaran_pers/view/s4', // Contoh link
        tgl: " 03 Jun 2024",
        penulis: "Rama Aditya",
        paragraf: [
            'JAKARTA (3 Juni 2024)',
            '- BMKG telah menyampaikan bahwa sebagian wilayah di Indonesia telah memasuki musim kemarau, serta potensi kekeringan yang dapat terjadi khususnya di wilayah Indonesia sebelah selatan Khatulistiwa paling tidak hingga akhir bulan September. Meskipun demikian dalam 24 jam terakhir tercatat adanya intensitas hujan sedang hingga lebat di beberapa wilayah di Indonesia, yakni di wilayah Semarang (104.4 mm), Sambas (103.0 mm), Sarmi (94.0 mm), Ambon (69.9 mm), Toli-Toli (61.1 mm), Silangit (57.3 mm), dan Tanjung Pinang (50.8 mm).',
            'Adanya potensi hujan sedang yang disertai kilat/petir di wilayah Jakarta dan sekitarnya sejak beberapa hari lalu telah diinformasikan kepada pihak terkait dan masyarakat melalui platform diseminasi BMKG. Kondisi ini terjadi akibat beberapa faktor dinamika atmosfer yakni aktifnya gelombang ekuator Rossby dan Kelvin di Jawa bagian barat yang meningkatkan potensi pertumbuhan awan hujan di Jawa bagian barat dan termasuk Jabodetabek, teramatinya pola pertemuan dan perlambatan kecepatan angin (konvergensi), suhu muka laut yang hangat pada perairan wilayah sekitar Selat Sunda dan Laut Jawa, labilitas atmosfer yang tinggi serta adanya indikasi adveksi dingin dari selatan Jawa sehingga menyebabkan kelembapan yang tinggi di wilayah pulau Jawa.',
            'Deputi Bidang Meteorologi, Guswanto di Jakarta (03/06/2024) menyatakan bahwa meskipun di sebagian wilayah Indonesia telah memasuki awal musim kemarau namun sebagian wilayah lainnya masih berada di masa peralihan musim di mana kandungan uap air dan labilitas atmosfer masih tinggi yang dapat memicu pertumbuhan awan-awan hujan yang signifikan. Ia menambahkan bahwa masih terdapat potensi peningkatan curah hujan di beberapa wilayah Indonesia dalam sepekan ke depan secara signifikan. Kondisi dinamika atmosfer yang dapat memicu peningkatan curah hujan tersebut antara lain aktifnya fenomena Madden Julian Oscillation (MJO), gelombang ekuatorial Rossby dan juga Kelvin, adanya pola sirkulasi siklonik, serta potensi pembentukan daerah belokan dan perlambatan angin.',
            '"Kombinasi pengaruh fenomena-fenomena tersebut diprakirakan menimbulkan potensi hujan dengan intensitas sedang-lebat yang disertai kilat/petir dan angin kencang yang dapat berlangsung di sebagian wilayah Indonesia hingga 9 Juni 2024", imbuhnya.',
            'Sementara itu, Kepala Pusat Meteorologi Publik Andri Ramdhani menambahkan bahwa potensi hujan dengan intensitas sedang-lebat yang disertai kilat/petir dan angin kencang pada periode 3 - 9 Juni 2024 dapat terjadi di sebagian Sumatra, sebagian Jawa bagian barat, sebagian besar Kalimantan, sebagian besar Sulawesi, Maluku Utara, Maluku, dan sebagian besar Papua.',
            'Andri menyampaikan juga agar masyarakat khususnya yang bertempat tinggal di daerah rawan bencana hidrometeorologi agar tetap waspada terhadap potensi cuaca ekstrem meskipun sebagain besar wilayah Indonesia saat ini sudah memasuki musim kemarau. "Dampak yang ditimbulkan dari cuaca ekstrem dapat meliputi banjir, banjir bandang, banjir lahar hujan, tanah longsor, jalan licin, pohon tumbang, dan berkurangnya jarak pandang," jelasnya.',
            'Terakhir, Andri meminta masyarakat untuk selalu memperbarui informasi melalui kanal resmi infoBMKG dan menghindari berita hoax yang tidak dapat dipertanggung jawabkan, guna memperoleh informasi cuaca yang lebih akurat dan informasi perubahan cuaca setiap saat dengan resolusi yang lebih tinggi di setiap kecamatan. (*)',
        ],
        dokumentasi: null
    },
    {
        id: 's5',
        image:'https://cdn.bmkg.go.id/Web/hilal10-1-250x150.jpg',
        title: 'Informasi Prakiraan Hilal saat Matahari Terbenam Tanggal 6 dan 7 Juni 2024 (Penentu Awal Bulan Zulhijah 1445 H)',
        link: '/profil/publikasi-dan-informasi/siaran_pers/view/s5', // Contoh link
        tgl: "  01 Jun 2024",
        penulis: " Iswanudin",
        paragraf: [
            null,
            'Salah satu kalender yang digunakan manusia dalam pengaturan waktu sehari-hari adalah Bulan Qomariyah (bulan Hijriyah) yang didasarkan pada keteraturan peredaran Bulan dalam mengelilingi Bumi, dan Bumi bersama Bulan dalam mengelilingi Matahari. Penentuan awal bulan Hijriyah ini sangat penting bagi umat Islam karena berhubungan dengan waktu ibadah, terutama bulan Ramadan, Syawal dan Zulhijah.',
            'Badan Meteorologi Klimatologi dan Geofisika (BMKG) sebagai institusi pemerintah yang salah satu tugas pokok dan fungsinya adalah memberikan pelayanan tanda waktu dan posisi bulan dan matahari. BMKG memberikan pertimbangan secara ilmiah kepada stake holder (Kementerian Agama, dll) dalam penentuan awal bulan hijriyah. Disamping memberikan informasi data-data Hilal hasil hisab (perhitungan), BMKG juga melaksanakan rukyat (observasi) hilal di 34 lokasi di Indonesia yang dapat disaksikan secara online (Live Streaming) di kanal https://hilal.bmkg.go.id/ setiap bulan.',
            'Untuk penentuan awal bulan Zulhijah 1445 H, BMKG menyampaikan informasi data-data Hilal (hasil Hisab) saat Matahari terbenam, yang dapat digunakan juga dalam pelaksanaan Rukyat (Observasi) Hilal.',
            'Informasi yang disampaikan disini meliputi : Waktu Konjungsi (Ijtima) dan Waktu Terbenam Matahari, Peta Ketinggian Hilal, Peta Elongasi, Peta Umur Bulan,  Peta Lag, Peta Fraksi Illuminasi Bulan, Objek Astronomis Lainnya yang Berpotensi Mengacaukan Rukyat Hilal, dan Data Hilal saat Matahari Terbenam untuk Kota-kota di Indonesia',
        ],
        dokumentasi: null
    },
    {
        id: 's6',
        image:'https://cdn.bmkg.go.id/Web/pch_det.2024.06.das_.1_ver_2024.05.30-250x150.png',
        title: 'Antisipasi Kekeringan, BMKG Gandeng PUPR, BRIN, dan TNI Lakukan Operasi Modifikasi Cuaca Mengisi 35 Waduk di Pulau Jawa',
        link: '/profil/publikasi-dan-informasi/siaran_pers/view/s6', // Contoh link
        tgl: "  30 Mei 2024",
        penulis: " Rama Aditya",
        paragraf: [
            'JAKARTA (30 Mei 2024)',
            '- Memasuki masa transisi dari musim hujan menuju musim kemarau, Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) telah memberikan peringatan dini perihal kondisi iklim dan kesiapsiagaan kekeringan 2024 yang perlu menjadi perhatian, baik dari Pemerintah Pusat maupun Pemerintah Daerah. Dalam rilis tersebut sejumlah wilayah di Indonesia berpotensi mengalami kekeringan pada musim kemarau terutama wilayah Jawa, Bali dan Nusa Tenggara yang sudah mengalami Hari Tanpa Hujan yang cukup panjang.',
            'Berdasarkan hasil pemantauan terhadap anomali iklim global, masih ada peluang pertumbuhan awan-awan hujan di sekitar wilayah Indonesia yang dapat dimanfaatkan sebagai upaya mitigasi dan antisipasi sebelum memasuki puncak musim kemarau. Salah satu upaya atau langkah mitigasi yang dapat dilakukan adalah dengan penerapan Operasi Modifikasi Cuaca (OMC). Kegiatan Operasi Modifikasi Cuaca perlu dilakukan untuk mengoptimalkan pertumbuhan awan hujan pada periode transisi sebelum memasuki puncak kemarau sehingga bisa mengisi tampungan air atau waduk di daerah yang berpotensi mengalami kekeringan tersebut.',
            'Kepala BMKG, Dwikorita Karnawati mengungkapkan, sebagai upaya sinergitas antar lembaga dalam upaya mitigasi bencana kekeringan, BMKG melalui Deputi Modifikasi Cuaca menggandeng Kementerian Pekerjaan Umum dan Perumahan Rakyat (PUPR), Badan Riset Inovasi Nasional (BRIN) dan TNI Angkatan Udara untuk melakukan Operasi Modifikasi Cuaca (OMC) secara serempak di Pulau Jawa. Langkah tersebut dilakukan dengan mengisi air di 35 waduk guna mengamankan pasokan air terutama pada jaringan irigasi pertanian, sehingga dapat mencukupi kebutuhan air selama musim kemarau.',
            '"Adanya unit kerja baru Deputi Bidang Modifikasi Cuaca di BMKG menjadikan BMKG akan semakin aktif menjalankan tugas aksi dini mitigasi potensi bencana hidrometeorologi termasuk kekeringan yang bisa berdampak pada berkurangnya ketersediaan air untuk kebutuhan pertanian dan air baku melalui operasi modifikasi cuaca", ungkap Dwikorita.',
            'Dwikorita menambahkan, kegiatan OMC untuk mengisi waduk-waduk di Pulau Jawa dijadwalkan mulai dilakukan pada 30 Mei 2024 hingga 10 Juni 2024 dengan 4 posko yang berlokasi di Jakarta, Bandung, Solo, dan Surabaya. Operasi ini didukung 4 pesawat jenis CASA 212 milik TNI AU dari Lanud Abd. Rahman Saleh Malang. Setiap posko akan bertanggungjawab untuk mengisi waduk/bendungan yang masuk dalam area jangkauan posko tersebut.',
            '"Posko Bandung akan ditempatkan di Lanud Husein Sastranegara dan bertanggungjawab untuk pengisian waduk di wilayah Jawa Barat. Posko Jakarta akan ditempatkan di Lanud Halim Perdana Kusuma dan bertanggungjawab terhadap pengisian waduk di Sebagian wilayah Jawa Barat dan Banten. Posko Solo akan ditempatkan di Lanud Adi Sumarmo dan bertanggungjawab terhadap pengisian waduk di wilayah Jawa Tengah. Posko Surabaya akan ditempatkan di Lanud Muljono dan bertanggungjawab untuk pengisian waduk di wilayah Jawa Timur," jelasnya.',
            'Pelaksanaan OMC ini sesuai dengan arahan dari Menteri PUPR yang akan menjadikannya sebagai Pilot Project untuk pelaksanaan operasi modifikasi cuaca lain di seluruh waduk-waduk yang ada Indonesia. Tujuan utama dilakukannya OMC di waduk-waduk ini selain untuk antisipasi kekeringan adalah untuk mendukung program ketahanan pangan dari pemerintah.',
            'Sementara itu, Plt. Deputi Modifiaksi Cuaca BMKG Dr. Tri Handoko Seto menjelaskan bahwa operasi modifikasi cuaca di pulau Jawa dilakukan secara serempak karena sempitnya window of opportunity (peluang) pertumbuhan awan yang masih memungkinkan untuk disemai agar menjadi hujan.',
        ],
        dokumentasi: null
    },
    {
        id: 's7',
        image:'https://cdn.bmkg.go.id/Web/Gambar-WhatsApp-2024-05-28-pukul-12.17.22_86693fe9-250x150.jpg',
        title: 'Waspada Kemarau! BMKG Sebut Indonesia Berpotensi Alami Kekeringan Meteorologis',
        link: '/profil/publikasi-dan-informasi/siaran_pers/view/s7', // Contoh link
        tgl: " 28 Mei 2024",
        penulis: "Akhmad Fadilah",
        paragraf: [
            'JAKARTA (29 Mei 2024)',
            ' - Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) menyebut sejumlah wilayah di Indonesia berpotensi mengalami kekeringan meteorologis pada musim kemarau sehingga membutuhkan kesiagaan dari Pemerintah Pusat dan Pemerintah Daerah.',
            '"Laporan kepada Presiden perihal kondisi iklim dan kesiap-siagaan kekeringan 2024 sudah kami sampaikan agar mendapat atensi khusus pemerintah sehingga risiko dan dampak yang ditimbulkan dapat diantisipasi dan diminimalisir sekecil mungkin," ungkap Kepala BMKG Dwikorita Karnawati di Jakarta, Selasa (28/5/2024).',
            'Dwikorita menyampaikan bahwa mayoritas wilayah Jawa, Bali, dan Nusa Tenggara sudah mengalami Hari Tanpa Hujan (HTH) sepanjang 21-30 hari atau lebih panjang. Selain itu, berdasarkan analisis curah hujan dan sifat hujan yang dilakukan BMKG, menunjukkan bahwa kondisi kering sudah mulai memasuki wilayah Indonesia, khususnya di bagian Selatan Khatulistiwa.',
            '"Sebagian wilayah Indonesia sebanyak 19% dari Zona Musim sudah masuk Musim Kemarau, dan diprediksi sebagian besar wilayah Jawa, Bali dan Nusa Tenggara segera menyusul memasuki musim kemarau dalam tiga dasarian ke depan. Kondisi kekeringan ini saat musim kemarau akan mendominasi wilayah Indonesia sampai akhir bulan September," paparnya.',
            'Sementara itu, Deputi Bidang Klimatologi BMKG, Ardhasena Sopaheluwakan menyampaikan hingga dasarian II Mei 2024, pemantauan terhadap anomali iklim global di Samudera Pasifik menunjukkan indeks ENSO sebesar +0.21 atau dalam kondisi netral. Kondisi indeks ENSO sudah berada pada level netral selama dua dasarian, dan diprediksi akan terus netral sampai periode Juni-Juli 2024. Selanjutnya, pada periode Juli-Agustus-September 2024, ENSO Netral diprediksi akan beralih menuju fase La Nina lemah yang akan bertahan hingga akhir tahun 2024. Fenomena La Nina lemah ini diprediksi tidak berdampak pada musim kemarau yang akan segera hadir. Sedangkan di Samudera Hindia, pemantauan suhu muka laut menunjukkan kondisi IOD Netral namun ada kecenderungan beralih ke fase IOD Positif.',
            'Melihat fakta tersebut, lanjut dia, maka daerah dengan potensi curah hujan bulanan sangat rendah dengan kategori kurang dari 50mm per bulan perlu mendapatkan perhatian khusus untuk mitigasi dan antisipasi dampak kekeringan. Adapun daerah tersebut meliputi sebagian besar Pulau Sumatra, Pulau Jawa, Kalimantan Barat, Kalimantan Utara, Bali dan Nusa Tenggara, sebagian Pulau Sulawesi, dan sebagian Maluku dan Papua.',
            'Adapun dari hasil monitoring hotspot yang dilakukan dengan satelit, menunjukkan telah munculnya beberapa hotspot awal pada daerah-daerah rawan kebakaran hutan dan lahan (karhutla) sehingga diperlukan perhatian khusus untuk mengantisipasi terjadinya kebakaran di sepanjang musim kemarau.',
            '"Memperhatikan dinamika atmosfer jangka pendek terkini, masih terdapat jendela waktu yang sangat singkat yang bisa dimanfaatkan secara optimal sebelum memasuki peride pertengahan musim kemarau," ujarnya.',
            'Pelaksana Tugas (Plt.) Deputi Bidang Modifikasi Cuaca, Tri Handoko Seto mengatakan bahwa berkaca dari hal tersebut maka BMKG memberikan sejumlah rekomendasi teknis yang bisa dilakukan sebagai langkah mitigasi dan antisipasi. Di antaranya, penerapan teknologi modifikasi cuaca untuk pengisian waduk-waduk di daerah yang berpotensi mengalami kondisi kering saat musim kemarau dan membasahi dan menaikkan muka air tanah pada daerah yang rawan mengalami karhutla ataupun pada lahan gambut.',
            'Agar upaya modifikasi cuaca dapat terlaksana dengan efektif dan efisien dalam memitigasi potensi bencana kekeringan, lanjut Seto, BMKG berharap agar Kementerian Pekerjaan Umum dan Perumahan Rakyat serta Kementerian Pertanian dapat memastikan koneksitas jaringan irigasi dari waduk ke kawasan yang terdampak kekeringan benar-benar memadai.',
            'Lebih lanjut, Kepala BMKG Dwikorita Karnawati menuturkan, kepada pemerintah daerah, BMKG merekomendasikan agar daerah yang masih mengalami hujan atau transisi dari musim hujan ke musim kemarau, untuk dapat segera mengoptimalkan secara lebih masif upaya untuk memanen air hujan. Pemanenan dapat dilakukan melalui tandon-tandon/ tampungan-tampungan air, embung-embung, kolam-kolam retensi, sumur-sumur resapan, dan lain sebagainya seiring dengan upaya mitigasi dampak kejadian ekstrem hidrometeorologi basah yang sedang dilakukan.', 
            '"Terkait pertanian, maka pola dan waktu tanam untuk iklim kering pada wilayah terdampak dapat menyesuaikan. Karenanya, BMKG akan melakukan koordinasi lebih lanjut dengan Menteri Pertanian dan Gubernur Provinsi terdampak," imbuhnya.',
            'Dwikorita mengungkapkan bahwa BMKG berharap informasi peringatan dini kesiap-siagaan musim kemarau tersebut dapat dimanfaatkan secara efektif oleh pemerintah pusat dan daerah. (*)',
        ],
        dokumentasi: null
    },
    {
        id: 's8',
        image:'https://cdn.bmkg.go.id/Web/Screenshot_20240526_115253_Drive-250x150.jpg',
        title: 'Kepala BMKG: Atasi Krisis Air Butuh Komitmen Kuat Antar Negara',
        link: '/profil/publikasi-dan-informasi/siaran_pers/view/s8', // Contoh link
        tgl: "26 Mei 2024",
        penulis: " Rama Aditya",
        paragraf: [
            'BALI (23 Mei 2024) ',
            ' - Kepala Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) Dwikorita Karnawati menyebut butuh komitmen bersama yang kuat untuk mengatasi krisis air akibat perubahan iklim. Komitmen tersebut, kata dia, harus dilakukan seluruh negara tanpa terkecuali mengingat persoalan air menjadi ancaman serius bagi seluruh negara di dunia.',
            '"Masalah air menjadi masalah seluruh negara. Semua terdampak sehingga setiap negara harus bekerja lebih cerdas dari apa yang sudah dilakukan sebelumnya untuk menghadapi laju perubahan iklim. Seperti mengintegrasikan ilmu pengetahuan dan teknologi ke dalam proses politik dan juga regional tanpa mengabaikan kearifan lokal setiap negara," ungkap Dwikorita dalam High Level Panel bertajuk Bandung Spirit di agenda World Water Forum (WWF) di Bali, Kamis (23/5).',
            'Dwikorita memaparkan sejumlah fakta perubahan iklim, diantaranya yaitu bahwa berdasarkan data analisis peta global menunjukkan bahwa debit rata-rata air sungai pada tahun 2022 yang dikategorikan pada posisi normal hanya 38%. Sementara itu banyak debit air sugai yang keluar menuju laut berada pada level di bawah normal atau jauh di bawah normal yang artinya daerah tersebut mengalami kekeringan. Di lain sisi, lanjut dia, terdapat daerah di dunia yang memiliki debit air sungai melampaui normal atau surplus sedang terjadi kebanjiran.',
            'Dwikorita menyebut perubahan iklim mencakup berbagai aspek, termasuk peningkatan suhu global, perubahan pola curah hujan, kenaikan permukaan air laut, serta dampaknya terhadap lingkungan dan manusia. Apabila penanganan persoalan ini tidak disertai komitmen politik yang kuat, maka dampaknya akan sangat besar karena dapat memicu terjadinya konflik yang berimplikasi terhadap stabilitas ekonomi, politik, dan keamanan.',
            '"Tentunya kami berharap, dengan *Bandung Spirit atau Spirit Kerjasama (Gotong Royong) yang terbangun sejak Konferensi Asia Afrika di Bandung tahun 1955 tersebut dapat secara lebih dahsyat mendorong komitmen politik seluruh negara, untuk mengatasi krisis air global secara bersama-sama. Komitmen politik tersebut harus juga disertai tindakan politik yang berbasis ilmu pengetahuan dan teknologi tanpa mengabaikan kearifan lokal," imbuhnya.',
            'Lebih lanjut, Dwikorita mengajak seluruh peserta untuk belajar dari apa yang telah dilakukan oleh The Intergovernmental Oceanographic Commission (IOC) UNESCO. Di mana selama 20 tahun telah berhasil mengatasi ketakutan akan bahaya tsunami yang dapat melanda setiap negara. Hal tersebut dapat tercapai karena adanya upaya integrasi sains dan teknologi ke dalam proses politik dan regional. Mekanisme ini dianggap relevan dan kerjasama holistic seluruh pihak akan membuat isu-isu iklim dan krisis air dapat dicari solusinya sehingga menghasilkan sebuah upaya bersama di setiap negara.',
            'Dwikorita menegaskan, dalam menghadapi tsunami tentunya tidak boleh melupakan kearifan lokal di setiap daerah dan negara. Ia berharap, dengan pendekatan di dalam pemerintahan dapat menjadi pendorong yang lebih kuat untuk negara-negara anggota dalam menindaklanjuti segala kebijakan yang telah dibuat demi kepentingan bersama.',
            '"Sementara itu, bagaimana dengan di luar pemerintahan? Kami menyarankan agar penempatan pusat-pusat keunggulan di setiap wilayah benar-benar dapat dipertimbangkan lebih lanjut seperti apa yang telah dijelaskan oleh seruan kami dari Afrika. Jadi sebenarnya pendirian ini bukanlah pusat baru, ini berperan sebagai "aliansi" dari pusat-pusat yang sudah ada, sehingga hanya koordinasi di antara pusat-pusat yang sudah ada agar lebih sinergis dan efektif langkahnya," pungkasnya. (***)',
        ],
        dokumentasi: null
    },
    {
        id: 's9',
        image:'https://cdn.bmkg.go.id/Web/H08_EH_Indonesia-13-250x150.png',
        title: 'BMKG: Potensi Hujan dengan Intensitas Tinggi Masih Dapat Terjadi di Jabodetabek',
        link: '/profil/publikasi-dan-informasi/siaran_pers/view/s9', // Contoh link
        tgl: "25 Mei 2024",
        penulis: " Rama Aditya",
        paragraf: [
            'Jakarta, 25 Mei 2024',
            '- Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) mencatat terjadinya hujan dengan intensitas di atas 100 mm di wilayah Jabodetabek pada Jumat (24/5).',
            'Deputi Bidang Meteorologi Guswanto menjelaskan hujan dengan intensitas di atas 100 mm terpantau di Kec. Kemang, Bogor sebesar 155 mm, Kec. Bogor Barat sebesar 146.6 mm, Kec. Dramaga sebesar 123.8 mm, Kec. Leuwiliang sebesar 118.2 mm, dan Kec. Cisarua sebesar 108.0 mm.',
            '"Faktor pemicu hujan dengan intensitas tinggi tersebut yaitu aktivitas Madden Julian Oscillation (MJO) yang berada di kuadran 3 (Samudra Hindia), aktifnya gelombang Rossby Equatorial di sekitar Samudra Hindia Barat Sumatra perairan barat dan pesisir selatan Banten dan Jawa Barat," kata Guswanto di Jakarta, Sabtu (25/5).',
            'Tidak hanya itu faktor pemicu lainnya adalah pola pertemuan angin di wilayah Sumatera bagian Selatan hingga Samudera Hindia, suhu muka laut yang hangat pada perairan wilayah sekitar Selat Sunda dan Laut Jawa, labilitas atmosfer yang tinggi serta terpantaunya adveksi dingin dari selatan Jawa sehingga menyebabkan kelembapan yang tinggi cukup bertahan di wilayah pulau Jawa.',
            'Sebelumnya, BMKG telah merilis Prakiraan Musim Kemarau tahun 2024 dan menjelaskan bahwa sebagian besar wilayah Indonesia akan memasuki periode Awal Musim Kemarau pada bulan Mei hingga Agustus 2024.',
            'Meskipun demikian, Guswanto menyatakan bahwa masyarakat masih perlu waspada akan potensi pertumbuhan awan hujan dan peningkatan curah hujan secara signifikan di beberapa wilayah di Indonesia.',
            '"Meski dalam beberapa hari ke depan intensitas curah hujan di wilayah Jabodetabek diprediksi mulai berkurang, namun perlu diwaspadai potensi hujan yang dapat disertai kilat petir/angin kencang di wilayah Jabodetabek untuk sepekan ke depan," ujarnya.',
            'Di sisi lain, BMKG mengidentifikasi masih adanya potensi peningkatan curah hujan di beberapa wilayah dalam sepekan ke depan secara signifikan. Kondisi dinamika atmosfer yang dapat memicu peningkatan curah hujan tersebut antara lain adalah adanya Bibit Siklon Tropis 99B di Teluk Benggala sebelah timur India serta Bibit Siklon Tropis 93W di Perairan Masbate di sekitar Filipina bagian Tengah.',
            '"Kombinasi pengaruh fenomena-fenomena tersebut diprakirakan menimbulkan potensi hujan dengan intensitas Sedang-Lebat yang disertai kilat/petir dan angin kencang. Kondisi ini berlangsung sebagian wilayah Indonesia hingga 31 Mei 2024," jelas Guswanto.',
            'Sementara itu, Kepala Pusat Meteorologi Publik Andri Ramdhani menambahkan bahwa potensi hujan dengan intensitas Sedang-Lebat yang disertai kilat/petir dan angin kencang pada periode 25-31 Mei 2024 dapat terjadi di sebagian Sumatra, sebagian Jawa bagian barat, sebagian besar Kalimantan, sebagian besar Sulawesi, Maluku, Maluku Utara, dan sebagian besar Papua.',
            'Oleh karenanya, masyarakat khususnya yang bertempat tinggal daerah bertopografi curam/bergunung/tebing agar tetap waspada serta menghindari atau menjauhi lereng-lereng bukit yang rawan longsor.',
            '"Dampak yang dapat ditimbulkan dari cuaca ekstrem seperti banjir, banjir bandang, banjir lahar hujan, tanah longsor, jalan licin, pohon tumbang, dan berkurangnya jarak pandang," jelasnya.',
            'Terakhir, Andri meminta masyarakat untuk mengakses aplikasi InfoBMKG untuk mendapatkan informasi cuaca yang lebih akurat dan informasi perubahan cuaca setiap saat dengan resolusi yang lebih tinggi di setiap kecamatan.',
        ],
        dokumentasi: null
    },
    {
        id: 's10',
        image:'https://cdn.bmkg.go.id/Web/WhatsApp-Image-2024-05-25-at-00.08.57-250x150.jpeg',
        title: 'Ancaman Krisis Air Kian Nyata, BMKG Dorong Keterlibatan Penuh Generasi Muda',
        link: '/profil/publikasi-dan-informasi/siaran_pers/view/s10', // Contoh link
        tgl: " 24 Mei 2024",
        penulis: "  Dwi Herlambang Ade Putra",
        paragraf: [
            'Bali (23 Mei 2024)',
            '- Kepala Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) Dwikorita Karnawati menyebut keterlibatan generasi muda sangat penting dalam mengatasi krisis air dan iklim.',
            'Terminologi generasi muda sendiri terbagi menjadi tiga bagian. Terdiri dari milenial atau generasi Y (lahir tahun 1981-1996), generasi Z (lahir tahun 1997-2012), dan generasi alpha (lahir setelah tahun 2012). Menurutnya, generasi muda di seluruh dunia turut terimbas secara langsung ataupun tidak secara langsung oleh anomali iklim, yang dapat berujung pada krisis air, pangan, energi dan kesehatan.',
            '"Generasi muda harus dibekali dengan pengetahuan, keterampilan, dan sumber daya. Dengan berinvestasi pada generasi muda kami berinvestasi pada masa depan di mana sumber daya air dikelola secara berkelanjutan, inklusif, dan adil untuk semua," ungkap Dwikorita dalam sambutan pembuka Young Water Sustainability Leaders (YWSL), 10th World Water Forum (WWF) di Bali Nusa Dua Convention Center (BNDCC), Bali, Kamis (23/5).',
            'Dwikorita menyampaikan bahwa krisis iklim berpotensi menimbulkan krisis air, krisis pangan, krisis energi, wabah penyakit, penurunan kualitas kesehatan di berbagai belahan dunia. Saat ini, kata dia, kondisi bumi semakin mengkawatirkan. Perubahan iklim mengakibatkan tidak hanya bencana yang secara intensitas dan durasi semakin bertambah, namun juga krisis air yang juga berimbas pada berbagai sektor kehidupan."Dan, berdasarkan penelitian generasi muda lah yang paling terdampak dan akan terus berlanjut pada masa mendatang apabila pemanasan global tidak segera ditekan," imbuhnya.',
            'Dalam diskusi tersebut, Dwikorita turut mengulas Bali Youth Plan yang merupakan gerakan untuk mengakomodasi kiprah generasi muda dalam di World Water Forum (WWF) ke-10. Generasi muda yang diajak terlibat dalam berbagai kegiatan berkenaan dengan air ini adalah mereka yang berada dalam rentang usia 18 hingga 35 tahun, baik yang berasal dari Indonesia maupun dari berbagai negara.',
            'Keterlibatan anak-anak muda ini dilakukan untuk melibatkan mereka sebagai pemangku kepentingan yang setara dalam semua proses Forum Air Dunia ke-10. Para anak muda tersebut difokuskan pada kegiatan yang inklusi untuk berbagi informasi.',
            '"Kegiatan Kepemudaan dlm Forum Air Sedunia ke - 10 tersebut, antara lain mencakup inisiatif seperti lokakarya pengembangan kapasitas, program bimbingan dan proyek kolaboratif yang melibatkan generasi muda dan advokasi kebijakan. Forum tersebut dikoordinir oleh Dr. Neil Andika dari Universitas Gadjah Mada, bersama para pemuda/pemudi dari Indonesia dan berbagai negara," ujarnya.',
            'Lebih lanjut, Dwikorita menjelaskan Bali Youth Plan telah menghasilkan kegiatan yang berdampak sejak Juli 2023. Kegiatan ini menyediakan tempat bagi generasi muda untuk mengatasi masalah sumber daya air dan berpartisipasi dalam dialog komprehensif dengan para ahli.',
            'Lebih lanjut, Dwikorita menegaskan bahwa program ini sangat penting karena anak muda adalah pemimpin, inovator, dan pengambil keputusan di masa depan. Di mana mereka, tambah dia, harus memastikan kepemimpinan yang visioner untuk masa depan, utamanya dalam hal melindungi generasi mendatang dari ancaman krisis air.',
            'Menurut Dwikorita, kedepan kolaborasi multi-pemangku kepentingan yang kuat yang berasal dari generasi muda, termasuk para ahli, akademisi, dan pembuat kebijakan, harus berfokus pada penciptaan sistem pengelolaan sumber daya air yang terintegrasi.',
            'Semua pihak, tandas Dwikorita, harus mengakui bahwa pemanasan global dan perubahan iklim memang terjadi di era ini. Perubahan iklim yang terjadi memperburuk kelangkaan air dan mengakibatkan banyak terjadinya bencana alam hidro-meteorologi.',
            '"Solusi yang luar biasa harus dicari untuk mengatasi masalah ini. Saya percaya bahwa generasi muda, dengan berbagai ide inovatifnya, dapat memastikan kemakmuran generasi sekarang dan generasi yang akan datang, terutama dalam mengatasi kelangkaan air yang disebabkan oleh perubahan iklim," tegasnya.',
            '"Kami berharap generasi muda di seluruh dunia dapat berinovasi untuk menggunakan air secara efisien, mengurangi limbah, memastikan penggunaan air yang berkelanjutan, dan memitigasi bencana yang berkaitan dengan air seperti banjir dan kekeringan," pungkas Dwikorita mengakhiri. (*)',
        ],
        dokumentasi: null
    },
];
