export const bulan = [
  { key: "januari", label: "Januari" },
  { key: "februari", label: "Februari" },
  { key: "maret", label: "Maret" },
  { key: "april", label: "April" },
  { key: "mei", label: "Mei" },
  { key: "juni", label: "Juni" },
  { key: "juli", label: "Juli" },
  { key: "agustus", label: "Agustus" },
  { key: "september", label: "September" },
  { key: "oktober", label: "Oktober" },
  { key: "november", label: "November" },
  { key: "desember", label: "Desember" },
];

export const tahun = [
  { key: "24", label: "2024" },
  // { key: "2", label: "Februari" },
  // { key: "3", label: "Maret" },
  // { key: "4", label: "April" },
  // { key: "5", label: "Mei" },
  // { key: "6", label: "Juni" },
  // { key: "7", label: "Juli" },
  // { key: "8", label: "Agustus" },
  // { key: "9", label: "September" },
  // { key: "10", label: "Oktober" },
  // { key: "11", label: "November" },
  // { key: "12", label: "Desember" },
];

export const dasarian = [
  { key: "dasa-1", label: "Dasarian 1" },
  { key: "dasa-2", label: "Dasarian 2" },
  { key: "dasa-3", label: "Dasarian 3" },
]

export const dinamikaAtmosfir = [
  {
    key: 'dasa-1-juni-24',
    title: 'Analisis Dinamika Atmosfer Dasarian I Juni 2024',
    tgl: '12 Jun 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD:Hasil monitoring indeks IOD dan ENSO Dasarian I Juni 2024, Indek Dipole Mode -0.21 (IOD Netral), dan indeks ENSO 0.19 (Netral). IOD Netral diprediksi berlangsung Juni hingga September 2024. Sementara itu, indeks ENSO diprediksi berpotensi menuju La Nina pada JAS 2024.',
      'Analisis dan Prediksi Angin 850mb:Aliran masa udara pada Dasarian I Juni 2024 didominasi angin timuran. Daerah pertemuan angin (konvergensi) dan belokan angin terjadi di sekitar Kalimantan. Pusat tekanan tinggi terjadi di Sumatera bagian utara. Pada Dasarian II Juni 2024 angin timursn diprediksi mendominasi wilayah Indonesia. Belokan angin di prediksi di sekitar Sumatera bagian tengah.',
      'Analisis OLR:Pada Dasarian I Juni 2024, daerah tutupan awan (OLR < 220 W/m2) dominan di sebagian besar Sumatera, Jawa bagian barat, Kalimantan, dan Sulawesi bagian tengah. Dibandingkan klimatologisnya, tutupan awan relatif lebih luas.',
      'Analisis dan Prediksi MJO:Analisis pada dasarian I Juni 2024 menunjukkan MJO tidak aktif dan diprediksi tetap tidak aktif hingga pertengahan dasarian III Juni 2024. Propagasi MJO dari Indian Ocean ke Wilayah Maritim Indonesia berkaitan dengan potensi peningkatan awan hujan di wilayah yang dilaluinya.',
      'Analisis dan Prediksi Kelembapan Udara (RH):Kelembapan udara permukaan berkisar 60-74% dan diprediksi hingga Dasarian I Juli 2024 berkisar 57-77 %, pada lapisan 850mb diprediksi berkisar 41-78% serta pada lapisan 700 mb umumnya diprediksi 20-76%.',
      'Analisis dan Prediksi Suhu:Suhu rata-rata permukaan berkisar 25-28°C dan diprediksi hingga Dasarian I Juli 2024 berkisar 24-29°C, Prediksi suhu minimum berkisar 22-26°C dan Prediksi suhu maksimum berkisar 30-34°C.',
      'Peringatan Dini Curah Hujan Tinggi:Waspada: Beberapa kabupaten/kota di Provinsi Kalimantan Selatan, Kalimantan Tengah, Kalimantan Utara, Maluku, Papua Tengah, Papua Barat Daya, Sulawesi Barat, Sulawesi Selatan, Sulawesi Tengah, dan Sumatera Selatan; Siaga: Beberapa kabupaten/kota di Provinsi Maluku, Papua Barat Daya, Papua Tengah, dan Sumatera Selatan; Awas : Tidak ada.Peringatan Dini Kekeringan Meteorologis: berlaku untuk Dasarian II Juni 2024 pada klasifikasi: Waspada: Beberapa kabupaten/kota di provinsi Bali, Jawa Timur, Nusa Tenggara Timur; Siaga : Beberapa kabupaten di D.I.Yogyakarta, Jawa Tengah, Jawa Timur, Bali, Nusa Tenggara Timur, dan Nusa Tenggara Barat; Awas: Tidak ada.',
      'Analisis Curah Hujan Dasarian I Juni 2024:Curah hujan pada Dasarian I Juni 2024 bervariasi dari kriteria rendah (25%), menengah (68%) dan tinggi-sangat tinggi (8%). Sifat hujan pada Dasarian I Juni 2024 bervariasi Bawah Normal (25%), Normal (22%) dan Atas Normal (53%).',
      'Analisis Perkembangan Musim Kemarau Dasarian I Juni 2024:Berdasarkan jumlah ZOM, sebanyak 41% wilayah Indonesia masuk musim kemarau. Wilayah yang sedang mengalami musim kemarau meliputi sebagian Aceh, sebagian Sumatera Utara, sebagian Riau, sebagian sumatera Selatan, sebagian Lampung sebagian Banten, sebagian Jawa Barat, sebagian Jawa Tengah, Yogya, Jawa Timur, sebagian Bali, sebagian NTT dan NTB, sebagian Sulawesi Tengah dan Sulawesi Selatan, sebagian Papua Selatan',
      'Prediksi Curah Hujan Dasarian: Jun II - Jul I Tahun 2024:Pada Juni II - Juli I 2024 umumnya diprediksi curah hujan berada di kriteria rendah - menengah (0-150 mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori rendah (<50 mm/dasarian):',
      '1) Pada Juni II 2024 meliputi sebagian besar Aceh, Sumatera Utara, sebagian kecil Riau, Bengkulu, Sumatera Selatan, Lampung, sebagian besar Jawa Barat hingga NTT, sebagian kecil Kalimantan Timur, sebagian kecil Sulawesi Selatan dan Sulawesi Tenggara, sebagian Maluku Selatan, Papua Barat, Papua, Papua Pegunungan dan Papua Selatan.',
      '2) Pada Juni III 2024 meliputi sebagian besar Sumatera, sebagian besar Jawa, hingga NTT, sebagian Kalimantan Barat, Kalimantan Timur, Kalimantan Tengah, Kalimantan Selatan, sebagian besar Sulawesi Utara, Gorontalo, sebagian Sulawesi Tengah bagian utara, Sulawesi Barat bagian utara dan selatan, Sulawesi Selatan bagian selatan, Sulawesi Tenggara, sebagian Maluku dan Maluku Selatan, sebagian Papua Barat, Papua, Papua Pegunungan dan Papua Selatan.',
      '3) Pada Juli III 2024 meliputi Sebagian besar Pulau Sumatera, sebagian besar Jawa hingga NTT, sebagian Kalimantan Timur, Kalimantan Selatan, Kalimantan Tengah, sebagian kecil Sulawesi Utara, Gorontalo, Sulawesi Tengah, Sulawesi Selatan bagian selatan, sebagian Sulawesi Tenggara bagian selatan, sebagian Maluku dan Maluku Selatan, Sebagian Papua Papua Barat, Papua, Papua Pegunungan, dan Papua Selatan.',
      'Prediksi Curah Hujan Kurang Dari 100 mm/Bulan untuk Bulan Juli 2024 - Desember 2024 :',
      '1) Juli - September 2024 curah hujan <100 mm/bulan berpeluang tinggi terjadi di sebagian Sumatera bagian selatan, sebagian besar Pulau Jawa, Bali hingga NTT, sebagian Kalimantan Selatan bagian barat dan utara, sebagian Sulawesi Selatan bagian selatan, sebagian Sulawesi Tenggara bagian selatan, sebagian kecil Papua Pegunungan dan Papua Selatan.',
      '2) Oktober 2024 curah hujan <100 mm/bulan berpeluang tinggi terjadi di sebagian Jawa Barat bagian utara, sebagian kecil Jawa Tengah, sebagian besar NTB dan sebagian NTT bagian selatan dan tenggara.',
      '3) November- Desember 2024 curah hujan < 100 mm/bulan berpeluang kecil untuk dapat terjadi di wilayah Indonesia'
    ],
    link: "https://cdn.bmkg.go.id/Web/Dinat-das-I-Juni-2024.gif",
    pdfLink: "https://cdn.bmkg.go.id/web/16.-Dinamika-Atmosfer-Dasarian-I-Juni-2024.pdf",
  },
  {
    key: 'dasa-3-mei-24',
    title: 'Analisis Dinamika Atmosfer Dasarian III Mei 2024',
    tgl: '02 Jun 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD:Hasil monitoring indeks IOD dan ENSO Dasarian III Mei 2024, Indek Dipole Mode sebesar +0.13 (IOD Netral), sedangkan indeks ENSO sebesar -0.02 (Netral). IOD Positif diprediksi berlangsung Juni hingga September 2024. Sementara itu, indeks ENSO diprediksi bertahan Netral pada Mei - Juni 2024.',
      'Analisis dan Prediksi Angin 850mb:Aliran masa udara pada Dasarian III Mei 2024 didominasi angin timuran. Streamline angin daerah pertemuan angin (konvergensi) dan belokan angin terlihat di sekitar Sumatera bagian tengah. Pusat tekanan rendah terlihat di perairan barat Sumatera. Pada Dasarian I Juni 2024 angin dari timur diprediksi mendominasi wilayah Indonesia. Belokan angin di prediksi di sekitar Sumatera bagian utara dan Kalimantan.',
      'Analisis OLR:Pada Dasarian III Mei 2024, daerah tutupan awan (OLR < 220 W/m2) masih dominan di sebagian besar Sumatera bagian tengah hingga utara, Kalimantan, Sulawesi bagian tengah, Maluku Utara, dan Papua bagian utara. Sementara itu, di wilayah Sumatera bagian selatan, Jawa, Bali, NTB, NTT, dan sebagian Papua, tutupan awan sudah mulai berkurang.',
      'Analisis dan Prediksi MJO:Analisis pada dasarian III Mei 2024 menunjukkan MJO tidak aktif dan diprediksi tidak aktif hingga akhir dasarian I Juni 2024, kemudian kembali aktif di fase 7 (Samudera Pasifik bagiian barat) mulai awal dasarian II Juni 2024. Propagasi MJO dari Indian Ocean ke Wilayah Maritim Indonesia ini berkaitan dengan potensi peningkatan awan hujan di wilayah yang dilaluinya.',
      'Analisis dan Prediksi Kelembapan Udara (RH):Kelembapan udara permukaan berkisar 60-75% dan diprediksi hingga Dasarian III Juni 2024 berkisar 55-75 %, pada lapisan 850mb diprediksi berkisar 50-75% serta pada lapisan 700 mb umumnya diprediksi 30-70%.',
      'Analisis dan Prediksi Suhu:Suhu rata-rata permukaan berkisar 23-29°C dan diprediksi hingga Dasarian III Juni 2024 berkisar 22-29°C, Prediksi suhu minimum berkisar 20-26°C dan Prediksi suhu maksimum berkisar 26-34°C.',
      'Peringatan Dini Curah Hujan Tinggi :Waspada: Beberapa kabupaten/kota di Provinsi Sumatera Selatan, Kalimatan Utara, Sulawesi Selatan, Papua Barat, Papua Barat Daya, Papua Tengah, Papua Selatan, dan Papua; Siaga: Beberapa kabupaten/kota di Provinsi Maluku, Papua Barat Daya, Papua Barat, dan Papua Tengah; Awas :Beberapa kabupaten/kota di Provinsi Maluku. Peringatan Dini Kekeringan Meteorologis berlaku untuk Dasarian I Juni 2024 pada klasifikasi: Waspada: Beberapa kabupaten/kota, di provinsi Jawa Barat, Jawa Tengah, Jawa Timur, Bali, Nusa Tenggara Barat dan Nusa Tenggara Timur; Siaga : Beberapa kabupaten di Jawa Barat, Jawa Tengah, Jawa Timur, Nusa Tenggara Barat dan Nusa Tenggara Timur; Awas: Tidak ada.',
      'Analisis Curah Hujan Dasarian III Mei 2024:Curah hujan pada Dasarian III Mei 2024 bervariasi dari kriteria rendah (21%), menengah (69%) dan tinggi-sangat tinggi (10%). Sifat hujan pada Dasarian III Mei 2024 bervariasi Bawah Normal (23%), Normal (21%) dan Atas Normal (56%).',
      'Analisis Perkembangan Musim Kemarau Dasarian III Mei 2024:Berdasarkan jumlah ZOM, sebanyak 36% wilayah Indonesia masuk musim kemarau. Wilayah yang sedang mengalami musim kemarau meliputi sebagian Aceh, sebagian Sumatera Utara, sebagian Riau, sebagian Kepulauan Riau, sebagian Banten, sebagian Jawa Barat, D.I Yogyakarta, sebagian Jawa Tengah, Jawa Timur, sebagian Bali, sebagian NTB, sebagian NTT, sebagian Sulawesi Tengah, sebagian Sulawesi Tengah, sebagian Gorontalo, dan sebagian Sulawesi Utara.',
      'Prediksi Curah Hujan Dasarian: Juni I - Jun III Tahun 2024:Pada Juni I - Juni III 2024 umumnya diprediksi curah hujan berada di kriteria rendah - menengah (0 - 150 mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori rendah (<50 mm/dasarian) :',
      '1) Pada Juni I 2024 meliputi sebagian besar Sumatera, sebagian besar Jawa, Bali, NTB, NTT, sebagian Kalimantan Barat bagian barat, sebagian kalimantan Tengah bagian timur, sebagian Kalimantan Selatan bagian barat dan utara, sebagian Kalimantan Timur bagian selatan, sebagian Sulawesi Selatan bagian selatan, Kep. Aru, Kep. Tanimbar, sebagian Manokwari Timur, Sebagian Papua bagian utara dan selatan.',
      '2) Pada Juni II 2024 meliputi Sebagian besar Sumatera, sebagian besar Jawa, Bali, NTB, NTT, sebagian Kalimantan Barat bagian barat dan selatan, sebagian kalimantan Tengah bagian timur dan selatan, sebagian besar Kalimantan Selatan, sebagian Kalimantan Timur bagian timur, sebagian kecil Sulawesi Utara, sebagian kecil Gorontalo, sebagian Sulawesi Tengah bagian timur dan barat, Sulawesi Barat bagian utara dan selatan, Sulawesi Selatan bagian selatan, sebagian P. Buru, P. Sula, Kep. Aru, Kep. Tanimbar, sebagian Manokwari Selatan, Fak Fak, Sebagian Papua bagian utara dan selatan.',
      '3) Pada Juni III 2024 meliputi sebagian Sumatera bagian utara dan selatan, sebagian besar Jawa, Bali, NTB, NTT, sebagian Kalimantan Barat bagian barat dan selatan, sebagian kalimantan Tengah bagian timur, sebagian besar Kalimantan Selatan, sebagian Kalimantan Timur bagian timur, sebagian kecil Sulawesi Utara, sebagian kecil Gorontalo, sebagian Sulawesi Selatan bagian selatan, sebagian Sulawesi Tenggara bagian selatan, sebagian P. Buru, Kep. Aru, Kep. Tanimbar, sebagian Manokwari selatan, Fak Fak, Sebagian Papua bagian utara dan selatan.',
      'Prediksi Curah Hujan Lebih Dari 300 mm/Bulan untuk Bulan Juni 2024 - November 2024 :',
      '1) Juni 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Kalimantan Timur, Kalimantan Selatan, sebagian Sulawesi Selatan, Sulawesi Tengah, Sulawesi Utara, sebagian Maluku, Maluku Utara, sebagian Papua Barat Daya, Papua Barat, Papua Tengah, dan Papua Pegunungan.',
      '2) Juli 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian Sumatera Utara, Kalimantan Barat, Kalimantan Utara, Kalimantan Selatan, Sulawesi Selatan, Sulawesi Tengah, Sulawesi Utara, Maluku Utara, Maluku, Papua Barat Daya, papua Barat, Papua Tengah, dan Papua Pegunungan.',
      '3) Agustus 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian kecil Aceh, Sumatera Utara, kalimantan Barat, Maluku, Papua Barat Daya, Papua Barat, dan Papua Tengah.',
      '4) September 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Sumatera Utara, Kalimantan Barat, Maluku, Papua Barat Daya, Papua Barat, dan Papua Tengah.',
      '5) Oktober 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Utara, Jawa Barat, Maluku, Papua Barat Daya, Papua Barat, dan Papua Selatan.',
      '6) November 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Sumatera Barat, Riau, Bengkulu, Bangka belitung, Jawa Barat, Jawa tengah, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Utara, NTB, Sulawesi Selatan, Sulawesi Barat, Papua Barat Daya, Papua Barat dan Papua Selatan.',
    ],
    link: "https://cdn.bmkg.go.id/Web/dinast-das-III-mei-2024.gif",
    pdfLink: "https://cdn.bmkg.go.id/web/15.-Dinamika-Atmosfer-Dasarian-III-Mei-2024.pdf",
  },
  {
    key: 'dasa-2-mei-24',
    title: 'Analisis Dinamika Atmosfer Dasarian II Mei 2024',
    tgl: '24 Mei 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD:Hasil monitoring indeks IOD dan ENSO Dasarian II Mei 2024, Indek Dipole Mode sebesar +0.51 (IOD Netral), sedangkan indeks ENSO sebesar +0.21 (Netral). IOD Positif diprediksi berlangsung hingga September 2024. Sementara itu, indeks ENSO diprediksi bertahan Netral pada Mei - Juli 2024.',
      'Analisis dan Prediksi Angin 850mb:Aliran masa udara pada Dasarian II Mei 2024 didominasi angin timuran. Streamline angin daerah pertemuan angin (konvergensi) dan belokan angin terlihat di sekitar Maluku Utara. Pusat tekanan rendah terlihat di perairan utara Papua. Pada Dasarian III Mei 2024 angin dari timur diprediksi mendominasi wilayah Indonesia. Belokan angin di prediksi di sekitar Sumatera bagian utara.',
      'Analisis OLR:Pada Dasarian II Mei 2024, daerah tutupan awan (OLR < 220 W/m2) tutupan awan masih dominan di sebagian besar Sumatera, Kalimantan Barat dan Papua. Sementara itu, di wilayah Kalimantan bagian utara, Sulawesi Selatan, Jawa, Bali, dan NTB, tutupan awan sudah mulai berkurang.',
      'Analisis dan Prediksi MJO: Analisis pada dasarian II Mei 2024 menunjukkan MJO aktif di fase 3 (Samudera Hindia) dan diprediksi terus aktif hingga awal dasarian I Juni 2024 di fase 4 dan 5 (Benua Maritim Indonesia). Propagasi MJO dari Indian Ocean ke Wilayah Maritim Indonesia ini berkaitan dengan potensi peningkatan awan hujan di wilayah yang dilaluinya.',
      'Analisis dan Prediksi Kelembapan Udara (RH): Kelembapan udara permukaan berkisar 60-75% dan diprediksi hingga Dasarian II Juni 2024 berkisar 55-75 %, pada lapisan 850mb diprediksi berkisar 50-75% serta pada lapisan 700 mb umumnya diprediksi 40-70%.',
      'Analisis dan Prediksi Suhu: Suhu rata-rata permukaan berkisar 24-29°C dan diprediksi hingga Dasarian II Juni 2024 berkisar 23-29°C, Prediksi suhu minimum berkisar 20-25°C dan Prediksi suhu maksimum berkisar 26-36°C.',
      'Peringatan Dini Curah Hujan Tinggi : Waspada: Beberapa kabupaten/kota di Provinsi Jawa Tengah, Kalimantan Selatan, Sulawesi Barat, Sulawesi Selatan, Sulawesi Tengah, Sulawesi Tenggara, Maluku, Papua Barat, Papua Barat Daya, Papua Tengah, dan Papua; Siaga: Beberapa kabupaten/kota di Provinsi Sulawesi Selatan dan Maluku; Awas : Beberapa kabupaten/kota di Provinsi Sulawesi Selatan.',
      'Peringatan Dini Kekeringan Meteorologis: berlaku untuk Dasarian III Mei 2024 pada klasifikasi: Waspada: Jepara, Jawa Tengah dan beberapa kabupaten di Jawa Timur, Nusa Tenggara Barat dan Nusa Tenggara Timur; Siaga : Beberapa kabupaten di Nusa Tenggara Timur; Awas: Tidak ada.',
      'Analisis Curah Hujan Dasarian II Mei 2024: Curah hujan pada Dasarian II Mei 2024 bervariasi dari kriteria rendah (31%), menengah (60%) dan tinggi-sangat tinggi (9%). Sifat hujan pada Dasarian II Mei 2024 bervariasi Bawah Normal (35%), Normal (23%) dan Atas Normal (43%).',
      'Analisis Perkembangan Musim Kemarau Dasarian II Mei 2024: Berdasarkan jumlah ZOM, sebanyak 19% wilayah Indonesia masuk musim kemarau. Wilayah yang sedang mengalami musim kemarau meliputi sebagian Aceh, sebagian Sumatera Utara, sebagian Riau, sebagian Jawa Barat, sebagian D.I Yogyakarta, sebagian Jawa Tengah, sebagian Jawa Timur, sebagian Bali, sebagian NTB, sebagian NTT, sebagian Sulawesi Tengah, sebagian Sulawesi Tengah, sebagian Sulawesi Utara.',
      'Prediksi Curah Hujan Dasarian: Mei III - Jun II Tahun 2024: Pada Mei III - Juni II 2024 umumnya diprediksi curah hujan berada di kriteria rendah - menengah (0 - 150 mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori tinggi - sangat tinggi (>150 mm/dasarian) :',
      '1) Pada Mei III 2024 meliputi Sebagian Sulawesi Selatan, Sebagian Sulawesi Barat, Sebagian Sulawesi Tenggara, Sebagian Maluku dan sebagian Papua Barat.',
      '2) Pada Juni I 2024 meliputi sebagian Maluku, Sebagian Papua Barat dan Sebagian Papua Tengah.',
      '3) Pada Juni II 2024 meliputi sebagian Sulawesi Selatan, Sebagian Sulawesi Tengah, Sebagian Maluku dan Sebagian Papua Barat.',
      'Prediksi Curah Hujan Lebih Dari 300 mm/Bulan untuk Bulan Juni 2024 - November 2024 :',
      '1) Juni 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian Kalimantan Timur, Kalimantan Selatan, sebagian Sulawesi Selatan, Sulawesi Tengah, Sulawesi Utara, sebagian Maluku, Maluku Utara, sebagian Papua Barat Daya, Papua Barat, Papua Tengah, dan Papua Pegunungan.',
      '2) Juli 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian Sumatera Utara, Kalimantan Barat, Kalimantan Utara, Kalimantan Selatan, Sulawesi Selatan, Sulawesi Tengah, Sulawesi Utara, Maluku Utara, Maluku, Papua Barat Daya, papua Barat, Papua Tengah, dan Papua Pegunungan.',
      '3) Agustus 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian kecil Aceh, Sumatera Utara, kalimantan Barat, Maluku, Papua Barat Daya, Papua Barat, dan Papua Tengah.',
      '4) September 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Sumatera Utara, Kalimantan Barat, Maluku, Papua Barat Daya, Papua Barat, dan Papua Tengah.',
      '5) Oktober 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Utara, Jawa Barat, Maluku, Papua Barat Daya, Papua Barat, dan Papua Selatan.',
      '6) November 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Sumatera Barat, Riau, Bengkulu, Bangka belitung, Jawa Barat, Jawa tengah, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Utara, NTB, Sulawesi Selatan, Sulawesi Barat, Papua Barat Daya, Papua Barat dan Papua Selatan.',
    ],
    link: "https://cdn.bmkg.go.id/Web/Dinat-Das-II-Mei-2024.gif",
    pdfLink: "https://cdn.bmkg.go.id/web/14.-Dinamika-Atmosfer-Dasarian-II-Mei-2024.pdf",
  },
  {
    key: 'dasa-1-mei-24',
    title: 'Analisis Dinamika Atmosfer Dasarian I Mei 2024',
    tgl: '13 Mei 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan PrediksiENSO dan IOD:Hasil monitoring indeks IOD dan ENSO Dasarian I Mei 2024, Indek Dipole Mode sebesar +0.22 (IOD Netral), sedangkan indeks ENSO sebesar +0.41 (Netral). IOD Positif diprediksi berlangsung hingga September 2024. Sementara itu, indeks ENSO diprediksi turun secara gradualmenuju Netral padaMei- Juni 2024.',
      'Analisis dan Prediksi Angin 850mb:Aliran masa udara pada Dasarian I Mei 2024 didominasi angin timuran. Streamline angin daerah pertemuan angin (konvergensi) dan belokan angin terlihat di sekitar Sumatera bagian utara dan Maluku Utara. Pusat tekanan rendah terlihat di perairan barat Sumatera. Pada Dasarian II Mei 2024 angin dari timur diprediksi mendominasi wilayah Indonesia. Belokan angin di prediksi di sekitar Maluku Utara dan Papua Barat. Pertemuan angin diprediksi di sekitar Maluku Utara dan Papua Barat.',
      'Analisis OLR:Pada Dasarian I Mei 2024, daerah tutupan awan (OLR < 220 W/m2) terlihat di hampir seluruh wilayah Indonesia, kecuali wilayah Sumatera bagian selatan, Kalimantan bagian selatan, Jawa, Bali, NTB, dan NTT. Tutupan awan di sebagian besar wilayah Indonesia bagian timur umumnya lebih banyak dibandingkan klimatologisnya. Sementara itu, di wilayah Sumatera bagian utara dan selatan, Jawa, Bali, dan NTB, tutupan awan lebih sedikit.',
      'Analisis dan Prediksi MJO: Analisis pada dasarian I Mei 2024 menunjukkan MJO tidak aktif dan diprediksi tidak aktif hingga dasarian II Mei 2024 kemudian akan aktif di fase 4 (Benua Maritim Indonesia) pada awal dasarian III Mei 2024. Pergerakan MJO ini berkaitan dengan potensi peningkatan awan hujan di wilayah yang dilaluinya.',
      'Analisis dan Prediksi Kelembapan Udara(RH): Kelembapan udara permukaan berkisar 63-72% dan diprediksi hingga Dasarian I Juni 2024 berkisar 57-77 %, pada lapisan 850mb diprediksi berkisar 48-79% serta pada lapisan 700 mbumumnya diprediksi34-76%.',
      'Analisis dan Prediksi Suhu: Suhu rata-rata permukaan berkisar 24-28°C dan diprediksi hingga Dasarian III Mei 2024 berkisar 23-29°C, Prediksi suhu minimum berkisar 20-26°C dan Prediksi suhu maksimum berkisar 29 33°C.',
      'Peringatan Dini Curah Hujan Tinggi: Waspada: Beberapa kabupaten/kota di Provinsi Aceh, Sumatera Utara, Sumatera Selatan, Kalimantan Selatan, Sulawesi Barat, Sulawesi Selatan, Sulawesi Tenggara, Maluku dan Papua; Siaga: Beberapa kabupaten/kota di Provinsi Sumatera Selatan danSulawesi Selatan; Awas : Beberapa kabupaten/kota di Provinsi Sulawesi Selatan.',
      'Peringatan Dini Kekeringan Meteorologis: berlaku untuk DasarianII Mei 2024pada klasifikasi: Waspada: Kab. Jepara, Jawa Tengah; Siaga : Tidak Ada;Awas: Tidak ada',
      'Analisis Curah Hujan Dasarian I Mei2024: Curah hujan pada Dasarian I Mei 2024 bervariasi dari kriteria rendah(18%), menengah(58%) dan tinggi-sangat tinggi(23%). Sifat hujan pada Dasarian I Mei 2024 bervariasi Bawah Normal(24%), Normal(18%) dan Atas Normal(58%).',
      'Analisis Perkembangan Musim Kemarau Dasarian I Mei 2024: Berdasarkan jumlah ZOM, sebanyak 14% wilayah Indonesia masuk musim kemarau. Wilayah yang sedang mengalami musim kemarau meliputi sebagian Aceh, sebagian Sumatera Utara, sebagian Riau, sebagian Jawa Barat, sebagian D.I Yogyakarta, sebagian Jawa Tengah, sebagian JawaTimur, sebagian Bali, sebagian NTB, sebagian NTT, sebagian Kalimantan Utara, dansebagianSulawesi Tengah.',
      'Prediksi Curah Hujan Dasarian Mei II- Jun I Tahun 2024: PadaMei II-Juni I 2024 umumnya diprediksi curah hujan berada di kriteria rendah- menengah (0- 150 mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori tinggi-sangat tinggi (>150 mm/dasarian):',
      '1) Pada Mei II 2024 meliputi sebagian kecil sebagian kecil Aceh, sebagian kecil Sumartra Utara, sebagian Sumatra Barat, sebagian kecil Bengkulu, sebagian kecil Kep. Bangka Belitung, sebagian kecil Kalimantan Barat, sebagian kecil Kalimantan Timur, sebagian Sulawesi Selatan bagian timur, sebagian kecil Sulawesi Barat bagian selatan, sebagian kecil Sulawesi Tenggarabagian utara, sebagian kecil Papua Tengah .',
      '2) Pada Mei II 2024 meliputi sebagian kecil Sulawesi Selatan, sebagian kecil Maluku, dan sebagian kecil Papua Barat.',
      '3) Pada Juni I 2024 meliputi sebagian kecil Sulawesi Selatan, sebagian kecil NTT, sebagian kecil Maluku, sebagian Papua Barat, dan sebagian kecil Papua Tengah.',
      'Prediksi Curah Hujan Lebih Dari 300mm/Bulan untuk Bulan Juni 2024- November 2024:',
      '1) Juni 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian Kalimantan Timur, Kalimantan Selatan, sebagian Sulawesi Selatan, Sulawesi Tengah, Sulawesi Utara, sebagian Maluku, Maluku Utara, sebagian Papua Barat Daya, Papua Barat, Papua Tengah, dan Papua Pegunungan.',
      '2) Juli 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian Sumatera Utara, Kalimantan Barat, Kalimantan Utara, Kalimantan Selatan, Sulawesi Selatan, Sulawesi Tengah, Sulawesi Utara, Maluku Utara, Maluku, Papua Barat Daya, papua Barat, Papua Tengah, dan Papua Pegunungan.',
      '3) Agustus 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian kecil Aceh, Sumatera Utara, kalimantan Barat, Maluku, Papua Barat Daya, Papua Barat, dan Papua Tengah.',
      '4) September 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Sumatera Utara, Kalimantan Barat, Maluku, Papua Barat Daya, Papua Barat, dan Papua Tengah.',
      '5) Oktober 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Utara, Jawa Barat, Maluku, Papua Barat Daya, Papua Barat, dan Papua Selatan.',
      '6) November 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Sumatera Barat, Riau, Bengkulu, Bangka belitung, Jawa Barat, Jawa tengah, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Utara, NTB, Sulawesi Selatan, Sulawesi Barat, Papua Barat Daya, Papua Barat dan Papua Selatan.',
    ],
    link: "https://cdn.bmkg.go.id/Web/dinat-das-I-mei-2024.gif",
    pdfLink: "https://cdn.bmkg.go.id/web/2024.05.11_Update-Informasi-Iklim-Dasarian-I-Mei-2024.pdf",
  },
  {
    key: 'dasa-3-april-24',
    title: 'Analisis Dinamika Atmosfer Dasarian III April 2024',
    tgl: '02 Mei 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD: Hasil monitoring indeks IOD dan ENSO Dasarian III April 2024, Indek Dipole Mode sebesar +0.21 (IOD Netral), sedangkan indeks ENSO sebesar +0.78 (El Nino lemah). IOD kategori Netral diprediksi bertahan hingga 5 bulan ke depan. Sementara itu, indeks ENSO diprediksi turun secara gradual menuju Netral pada Mei-Juni 2024.',
      'Analisis dan Prediksi Angin 850mb: Aliran masa udara pada Dasarian III April 2024 didominasi angin timuran. Streamline angin daerah pertemuan angin (konvergensi), belokan angin, dan pusat tekanan rendah terlihat di perairan barat Sumatera. Pada Dasarian I Mei 2024 angin dari timur diprediksi mendominasi wilayah Indonesia. Belokan angin diprediksi di sekitar Sumatera dan Maluku. Pertemuan angin diprediksi di sekitar Sumatera dan Maluku. Pusat tekanan rendah diprediksi terjadi di perairan utara Sumatera dan Kalimantan.',
      'Analisis OLR: Pada Dasarian III April 2024, daerah tutupan awan (OLR < 220 W/m2) terlihat di hampir seluruh wilayah Indonesia, kecuali wilayah Sumatera bagian utara, Kalimantan bagian timur, Sulawesi bagian utara, Jawa bagian timur, dan Bali. Tutupan awan di sebagian besar wilayah Indonesia bagian timur, umumnya lebih banyak dibandingkan klimatologisnya. Sementara itu, di wilayah Sumatera bagian utara, Jawa bagian barat, dan Kalimantan bagian timur, tutupan awan lebih sedikit.',
      'Analisis dan Prediksi MJO: Analisis pada dasarian III April 2024 menunjukkan MJO aktif pada fase 4 (benua maritim Indonesia) dan diprediksi aktif pada fase 4 dan 5 (benua maritim Indonesia) hingga pertengahan Dasarian II Mei 2024. Pergerakan MJO ini berkaitan dengan potensi peningkatan awan hujan di wilayah yang dilaluinya.',
      'Analisis dan Prediksi Kelembapan Udara(RH): Kelembapan udara permukaan berkisar 63-72% dan diprediksi hingga Dasarian III Mei 2024 berkisar 57-77%, pada lapisan 850mb diprediksi berkisar 48-79% serta pada lapisan 700mb umumnya diprediksi 34-76%.',
      'Analisis dan Prediksi Suhu: Suhu rata-rata permukaan berkisar 24-28°C dan diprediksi hingga Dasarian III Mei 2024 berkisar 24-29°C. Prediksi suhu minimum berkisar 23-28°C sedangkan suhu maksimum berkisar 29-35°C.',
      'Peringatan Dini Curah Hujan Tinggi: Waspada Beberapa kabupaten/kota di Provinsi Aceh, Kep. Bangka Belitung, Sumatera Selatan, Kalimantan Tengah, Kalimantan Timur, Kalimantan Selatan, Sulawesi Utara, Sulawesi Tengah, Sulawesi Barat, Sulawesi Selatan, Sulawesi Tenggara, Maluku, Maluku Utara, Papua Barat, dan Papua; Siaga Beberapa kabupaten/kota di Provinsi Aceh, Sumatera Selatan, Kalimantan Tengah, Kalimantan Timur, Sulawesi Barat, Sulawesi Selatan, dan Maluku; Awas Beberapa kabupaten/kota di Provinsi Kalimantan Tengah dan Sulawesi Selatan.',
      'Peringatan Dini Kekeringan Meteorologis: berlaku untuk Dasarian III April 2024 pada klasifikasi: Waspada Tidak ada; Siaga Tidak Ada; Awas Tidak ada.',
      'Analisis Curah Hujan Dasarian III April 2024: Curah hujan pada Dasarian III April 2024 bervariasi dari kriteria rendah (21%), menengah (63%), dan tinggi (16%); Sifat hujan pada Dasarian III April 2024 bervariasi Bawah Normal (37%), Normal (20%), dan Atas Normal (43%).',
      'Analisis Perkembangan Musim Kemarau Dasarian III April 2024: Berdasarkan jumlah ZOM, sebanyak 8% wilayah Indonesia masuk musim kemarau. Wilayah yang sedang mengalami musim kemarau meliputi sebagian Aceh, sebagian Sumatera Utara, Riau bagian utara, sekitar Pangandaran Jawa Barat, sebagian Sulawesi Tengah dan sebagian Maluku Utara.',
      'Prediksi Curah Hujan Dasarian Mei I - Mei III 2024 umumnya berada di kriteria rendah menengah (0-150 mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori tinggi-sangat tinggi (>150 mm/dasarian):',
      '1) Pada Mei I 2024 meliputi sebagian kecil Aceh, sebagian kecil Sumatera Barat, sebagian kecil Sumatera Selatan, sebagian kecil Bangka Belitung, sebagian Banten, sebagian Jawa Barat, sebagian Kalimantan Timur, sebagian Sulawesi Selatan, sebagian Sulawesi Barat, sebagian kecil Sulawesi Tenggara, sebagian Sulawesi tenggara, sebagian Maluku dan sebagian kecil Papua Barat.',
      '2) Pada Mei II 2024 meliputi sebagian kecil Sumatera Utara, sebagian Sulawesi Selatan, dan sebagian Papua Barat.',
      '3) Pada Mei III 2024 meliputi sebagian kecil Kalimantan Timur, sebagian Sulawesi Selatan, sebagian Sulawesi Barat, sebagian Sulawesi Tenggara, sebagian Maluku, dan sebagian kecil Papua Barat.',
      'Prediksi Curah Hujan Lebih Dari 300 mm/bulan untuk Bulan Mei - Oktober 2024:',
      '1) Mei 2024 curah hujan> 300 mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Sumatera Barat, Kep. Riau, Bengkulu, Kep. Bangka Belitung, sebagian besar Kalimantan Barat, Kalimantan Tengah, sebagian Kalimantan Timur, Kalimantan Selatan, Kalimantan Utara, sebagian besar Sulawesi Selatan, Sulawesi Barat, sebagian Sulawesi Tengah, Sulawesi Tenggara, Sulawesi Utara, Maluku, Maluku Utara, Papua Barat, Papua Tengah, Papua dan Papua Selatan.',
      '2) Juni - Juli 2024 curah hujan >300 mm/bulan berpeluang tinggi terjadi di sebagian Kalimantan Barat, Kalimantan Selatan, Kalimantan Timur, Kalimantan Utara, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku Utara, Maluku, Papua Barat, Papua Tengah, Papua dan Papua Selatan.',
      '3) Agustus - September 2024 curah hujan >300mm/bulan berpeluang tinggi terjadi di sebagian kecil Sumatera Utara, Kalimantan Barat, Maluku, sebagian Papua Barat, Papua Tengah, Papua dan Papua Selatan.',
      '4) Oktober 2024 curah hujan >300 mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Utara, Papua Barat, Papua Tengah dan Papua Selatan.',
    ],
    link: "https://cdn.bmkg.go.id/Web/dinat-das-III-apr-2024.jpg",
    pdfLink: "https://cdn.bmkg.go.id/Web/2024.05.01_Update-Informasi-Iklim-Dasarian-III-April-2024.pdf",
  },
  {
    key: 'dasa-2-april-24',
    title: 'Analisis Dinamika Atmosfer Dasarian II April 2024',
    tgl: '23 Apr 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD:Hasil monitoring indeks IOD dan ENSO Dasarian II April 2024,Indek Dipole Modesebesar+0.31 (IOD Netral), sedangkan indeks ENSO sebesar+0.93 (El Nino lemah).IOD kategori Netral diprediksi bertahan hingga 5 bulan kedepan. Sementara itu, indeks ENSO diprediksi turun secara gradual menuju Netral pada Mei Juni 2024.',
      'Analisis dan Prediksi Angin 850mb:Aliran masa udara pada Dasarian II April 2024 didominasi angin timuran. Streamline angin daerah pertemuan angin (konvergensi) terjadidi sekitar Sumatera dan Sulawesi. Belokan angin terjadidi sekitar Maluku. Pusat tekanan rendah terlihat di perairan barat Sumatera dan perairan utara Papua. Pada Dasarian III April 2024 angin dari timur diprediksi mendominasi wilayah Indonesia. Belokan angin di prediksi di sekitar Sumatera. Pertemuan angin diprediksi di sekitar Sumatera. Pusat tekanan rendah diprediksi terjadi di Laut Cina Selatan.',
      'Analisis OLR:Pada Dasarian II April 2024, daerah tutupan awan (OLR < 220 W/m2) terlihat di hampir seluruh wilayah Indonesia, kecuali wilayah Sumatera bagian utara, Kalimantan bagian timur, Jawa bagian timur, dan Bali. Tutupan awan di sebagian besar wilayah Indonesia bagian timur umumnyalebih banyak dibandingkan klimatologisnya. Sementara itu, di wilayah Sumatera bagian utara, Jawa bagian barat, dan Kalimantan bagian timur, tutupan awan lebih sedikit.',
      'Analisis dan Prediksi MJO:Analisis pada dasarianII April2024menunjukkan MJO tidak aktif dan diprediksi tidak aktif hingga akhir dasarian III April 2024.',
      'Analisis dan Prediksi Kelembapan Udara(RH):Kelembapan udara permukaan berkisar 60-72% dan diprediksi hingga Dasarian II Mei 2024 berkisar 60-80 %, pada lapisan 850mb diprediksi berkisar 60-80% serta pada lapisan 700 mbumumnya diprediksi 50-70%.',
      'Analisis danPrediksi Suhu:Suhu rata-rata permukaan berkisar 23-28°C dan diprediksi hingga Dasarian II Mei 2024 berkisar 23-29°C, Prediksisuhu minimum berkisar 20-26°C dan Prediksi suhu maksimum berkisar 26-32°C.',
      'Peringatan Dini Curah Hujan Tinggi:Waspada:Beberapa kabupaten /kota di Provinsi Aceh Jawa Barat Jawa Tengah D I Yogyakarta, Nusa Tenggara Timur Kalimantan Barat Kalimantan Tengah Sulawesi Barat dan Sulawesi Selatan. Siaga: Beberapa kabupaten /kota di Provinsi Sumatera Selatan Banten Jawa Barat Jawa Tengah Sulawesi Selatan dan Papua. Awas Tidak Ada',
      'Peringatan Dini Kekeringan Meteorologis:berlaku untuk Dasarian III April 2024 pada klasifikasi Waspada Tidak ada Siaga: Aceh Awas Tidak ada.',
      'Analisis Curah Hujan Dasarian II April 2024:',
      '1) Curah hujan pada Dasarian IIII April 2024 bervariasi dari kriteria rendah 18 menengah 65 dan tinggi 17',
      '2) Sifat hujan pada Dasarian III April 2024 bervariasi Bawah Normal 34 Normal 21 dan Atas Normal 45Analisis Perkembangan Musim Kemarau Dasarian II April 2024:Berdasarkan jumlah ZOM, sebanyaksebanyak8 wilayah Indonesia masuk musim kemarau Wilayah yang sedang mengalami musim kemarau meliputi sebagian Aceh, sebagian Sumatera Utara, Riau bagian utara, sekitar Pangandaran Jawa Barat, sebagian Sulawesi Tengah dan sebagian Maluku UtaraPrediksi Curah Hujan Dasarian Dasarian:April Dasarian III Mei II Tahun 2024: Pada April III- Mei II 2024 umumnya diprediksi curah hujan berada di kriteria rendah menengah 0 150 mm/dasarian) Wilayah yang diprediksi mengalami hujan kategori tinggi- sangat tinggi((>150 mm/dasarian):',
      '3) Pada April III 2024 meliputi sebagian kecil Bengkulu, sebagian kecil Jambi, sebagian kecil Sumatera Selatan, sebagian Banten,sebagianJawa Barat,sebagiankecilJawa Tengah,sebagianSulawesi Selatan,sebagian kecil Sulawesi Tenggara,sebagian kecil NTT,sebagian kecil Papua Tengah .',
      '4) Pada Mei I 2024 meliputi sebagian Kalimantan Timur,sebagian Sulawesi Selatan,sebagianMaluku,sebagianPapua Barat,sebagianPapua Tengah.',
      '5) Pada Mei II 2024 meliputi sebagian kecil Sulawesi Selatan,sebagian kecil Papua Tengah',
      'Prediksi Curah Hujan Lebih Dari 300 mm/Bulan untuk Bulan BulanMei 2024 Oktober 2024:',
      '1) Mei 2024 curah hujan> 300 mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Sumatera Barat, Kep. Riau, Bengkulu, Kep. Bangka Belitung, sebagian besar Kalimantan Barat, Kalimantan Tengah, sebagian Kalimantan Timur, Kalimantan Selatan, Kalimantan Utara, sebagian besar Sulawesi Selatan, Sulawesi Barat, sebagian Sulawesi Tengah, Sulawesi Tenggara, Sulawesi Utara, Maluku, Maluku Utara, Papua Barat, Papua Tengah, Papua dan Papua Selatan.',
      '2) Juni - Juli 2024 curah hujan> 300 mm/bulan berpeluang tinggi terjadi di sebagian Kalimantan Barat, Kalimantan Selatan, Kalimantan Timur, Kalimantan Utara, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku Utara, Maluku, Papua Barat, Papua Tengah, Papua dan Papua Selatan.',
      '3) Agustus - September 2024 curah hujan>300mm/bulan berpeluang tinggi terjadi di sebagian kecil Sumatera Utara, Kalimantan Barat, Maluku, sebagian Papua Barat, Papua Tengah, Papua dan Papua Selatan.',
      '4) Oktober 2024 curah hujan> 300 mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Utara, Papua Barat, Papua Tengah dan Papua Selatan',
    ],
    link: "https://cdn.bmkg.go.id/Web/dinat-das-II-apr-2024.jpg",
    pdfLink: "https://cdn.bmkg.go.id/Web/2024.04.21_Update-Informasi-Iklim-Dasarian-II-April-2024.pdf",
  },
  {
    key: 'dasa-1-april-24',
    title: 'Analisis Dinamika Atmosfer Dasarian I April 2024',
    tgl: '13 Apr 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD:Hasil monitoring indeksIOD dan ENSO Dasarian I April 2024,Indek Dipole Modesebesar+0.24 (IOD Netral), sedangkan indeks ENSO sebesar+1.28 (El Nino Moderate).IOD diprediksi pada kategori Netral danterus bertahan hingga 5 bulan kedepan.Sementara itu, indeks ENSO diprediksi diprediksi turun secara gradual menuju Netral pada Juni2024',
      'Analisis dan Prediksi Angin 850mb:Aliran masa udara pada Dasarian I April 2024 didominasi angin baratan. Streamline angin daerah pertemuan angin (konvergensi) terjadidi sekitar Sumatera, Laut Jawa, dan Laut Banda. Belokan angin terjadidi sekitar wilayah ekuator. Pada Dasarian II April 2024 angin dari Australia diprediksi mulai memasuki wilayah Indonesia. Belokan angin di prediksi di sekitar Sumatera dan Maluku. Pertemuan angin diprediksi di sekitar Sulawesi dan Laut Banda.',
      'Analisis OLR:Pada Dasarian III Maret 2024, daerah tutupan awan (OLR < 220 W/m2) terlihat di hampir seluruh wilayah Indonesia, kecuali wilayah Sumatera bagian utara, Kalimantan bagian timur, dan NTT. Tutupan awan di sebagian besar wilayah Indonesia bagian timur umumnya lebih banyak dibandingkan klimatologisnya. Sementara itu, di wilayah Sumatera bagian utara, Jawa bagian barat, dan Kalimantan bagian timur, tutupan awan lebih sedikit.',
      'Analisis danPrediksi MJO:Analisis pada dasarianI April2024menunjukkan MJO aktif di fase4 (Maritime Continent). MJO diprediksi aktif di fase 4 (benua maritim Indonesia) dan 3 (Samudera Hindia bagian timur) pada awal dasarian II April kemudian tidak aktif hingga awal dasarian III April. MJO berkaitan dengan potensi peningkatan awan hujan di wilayah yang dilewati.',
      'Analisis dan Prediksi Kelembapan Udara(RH):Kelembapan udara permukaan berkisar 62-72% dan diprediksi hingga Dasarian I Mei 2024 berkisar 60-77 %, pada lapisan 850mb diprediksi berkisar 60-78% serta pada lapisan 700 mbumumnya diprediksi 50-77%.',
      'Analisis danPrediksi Suhu:Suhu rata-rata permukaan berkisar 23-28°C dan diprediksi hingga Dasarian I Mei 2024 berkisar 20-29°C, Prediksi suhu minimum berkisar 20-26°C dan Prediksi suhu maksimum berkisar 23-32°C.',
      'Peringatan Dini Curah Hujan Tinggi: Waspada:Beberapa kabupaten/kota di Provinsi Aceh, Sumatera Utara, Sumatera Barat, Banten, Jawa Barat, Jawa Tengah, D I Yogyakarta, Jawa Timur, Kalimantan Tengah, Sulawesi Selatan, Papua dan Papua Barat Siaga Beberapa kabupaten/kota di Provinsi Aceh, Sumatera Selatan, Jawa Barat, dan Papual Awas Tidak Ada; Peringatan Dini Kekeringan Meteorologis: berlaku untuk Dasarian III Maret 2024 pada klasifikasiWaspada:Aceh, Sumatra Utara dan Jawa Tengah Siaga Aceh Awas Tidak ada Analisis',
      'Analisis Curah Hujan Dasarian I April 2024: ',
      '1) Curah hujan pada Dasarian I April 2024 bervariasi dari kriteria rendah 11 menengah 76 dan tinggi 13',
      '2) Sifat hujan pada Dasarian I April 2024 bervariasi Bawah Normal 23 Normal 29 dan Atas Normal 48',
      'AnalisisPerkembangan Musim Kemarau Dasarian III Maret 2024:',
      '1) Berdasarkan jumlah ZOM, sebanyak 7 wilayah Indonesia masuk musim kemarau Wilayah yang sedang mengalami musim kemarau meliputi sebagian Aceh, sebagian Sumatera Utara, Riau bagian utara, sekitar Pangandaran Jawa Barat, sebagian Sulawesi Tengah dan sebagian Maluku Utara',
      'Prediksi Curah Hujan Dasarian: April Dasarian I April - April Dasarian III Tahun 2024:Pada April I-III 2024 umumnya diprediksi curah hujan berada di kriteria rendah menengah 0 150 mm/dasarian) Wilayah yang diprediksi mengalami hujan kategori tinggi sangat tinggi 150 mm/dasarian):',
      '1) Pada April I 2024 meliputi Sebagian kecil Aceh bagian Barat, Sebagian kecil SumateSumatera Utara, Sumbar bagian Barat, Jambi, Sumatera Selatan, Lampung bagian Selatan, Sebagian Banten, Jawa Barat, Jawa Tengah bagian Utara, Jawa Timur, Bali, NTB, sebagian besar NTT, sebagian kecil Kalimantan Tengah, Sulawesi Selatan, Sulawesi Tenggara, dan Papua Tengah',
      '2) Pada April II 2024 meliputi sebagian Aceh bagian Barat, sebagian kecil Jawa Barat, Jawa Tengah, NTB, NTT, Sulawesi Selatan dan Sebagian Papua Tengah',
      '3) Pada April III 2024 meliputi sebagian kecil Banten, Jawa Barat, Jawa Tengah, Kalimantan Barat, Kalimantan Timur, Sulawesi Selatan, dan sebagian Papua Tengah',
      'Prediksi Curah Hujan Lebih Dari 300 mm/Bulan untuk Bulan Bulan Mei 2024 Oktober 2024:',
      '1) Mei 2024curahhujan> 300 mm/bulanberpeluangtinggiterjadidisebagian Aceh, Sumatera Utara, Sumatera Barat, Kep. Riau, Bengkulu, Kep. Bangka Belitung, sebagian besar Kalimantan Barat, Kalimantan Tengah, sebagian Kalimantan Timur, Kalimantan Selatan, Kalimantan Utara, sebagian besar Sulawesi Selatan, Sulawesi Barat, sebagian Sulawesi Tengah, Sulawesi Tenggara, Sulawesi Utara, Maluku, Maluku Utara, Papua Barat, Papua Tengah, Papua dan Papua Selatan.',
      '2) Juni - Juli 2024curahhujan> 300 mm/bulanberpeluangtinggiterjadidisebagian Kalimantan Barat, Kalimantan Selatan, Kalimantan Timur, Kalimantan Utara, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku Utara, Maluku, Papua Barat, Papua Tengah, Papua dan Papua Selatan.',
      '3) Agustus - September 2024curahhujan> 300 mm/bulanberpeluangtinggiterjadidisebagian kecil Sumatera Utara, Kalimantan Barat, Maluku, sebagian Papua Barat, Papua Tengah, Papua dan Papua Selatan.',
      '4) Oktober 2024curahhujan> 300 mm/bulanberpeluangtinggiterjadidisebagian Aceh, Sumatera Utara, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Utara, Papua Barat, Papua Tengah dan Papua Selatan',
    ],
    link: "https://cdn.bmkg.go.id/Web/dinat-das-I-april-2024.jpg",
    pdfLink: "https://cdn.bmkg.go.id/Web/2024.04.11_Update-Informasi-Iklim-Dasarian-I-April-2024.pdf",
  },
  {
    key: 'dasa-3-maret-24',
    title: 'Analisis Dinamika Atmosfer Dasarian III Maret 2024',
    tgl: '02 Apr 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD:Hasil monitoring indeks IOD dan ENSO Dasarian III Maret 2024, Indek Dipole Mode sebesar +0.22 (IOD Netral), sedangkan indeks ENSO sebesar +1.39 (El Nino Moderate). IOD diprediksi pada kategori Netral dan terus bertahan hingga 5 bulan kedepan. Sementara itu, indeks ENSO diprediksi turun secara gradual menuju Netral pada Mei 2024.',
      'Analisis dan Prediksi Angin 850mb:Aliran masa udara pada Dasarian III Maret 2024 didominasi angin timuran. Streamline angin daerah pertemuan angin (konvergensi) terjadi di sekitar Laut Jawa. Belokan angin terjadi di sekitar Bali. Pada Dasarian I April 2024 angin dari Australia diprediksi mulai memasuki wilayah Indonesia. Belokan angin di prediksi di sekitar Maluku. Pertemuan angin diprediksi di sekitar Sumatera bagian tengah, Laut Jawa, dan Maluku. Pola tekanan rendah diprediksi di sekitar perairan barat Sumatera, Selat Karimata, dan Selat Makassar.',
      'Analisis OLR:Pada Dasarian III Maret 2024, daerah tutupan awan (OLR < 220 W/m2) terlihat di sekitar pesisir barat Sumatera, Kalimantan bagian barat, Sulawesi bagian tengah, dan Papua bagian tengah hingga selatan. Tutupan awan di Sebagian besar wilayah Indonesia umumnya lebih sedikit dibandingkan klimatologisnya.',
      'Analisis dan Prediksi MJO: Analisis pada dasarian III Maret 2024 menunjukkan MJO aktif di fase 7, 8 dan 1. Kemudian MJO diprediksi aktif di wilayah maritim Indonesia pada akhir dasarian I hingga dasarian II April. (MJO berkaitan dengan potensi peningkatan awan hujan di wilayah yang dilewati).',
      'Analisis dan Prediksi Kelembapan Udara (RH): Kelembapan udara permukaan berkisar 60-70% dan diprediksi hingga Dasarian III April 2024 berkisar 55-80 %, pada lapisan 850mb diprediksi berkisar 44-80% serta pada lapisan 700 mb umumnya diprediksi 30-70%.',
      'Analisis dan Prediksi Suhu: Suhu rata-rata permukaan berkisar 23-27°C dan diprediksi hingga Dasarian III April 2024 berkisar 22-29°C, Prediksi suhu minimum berkisar 20-24°C dan Prediksi suhu maksimum berkisar 26-33°C.',
      'Peringatan Dini Curah Hujan Tinggi : Waspada: Beberapa kabupaten/kota di Provinsi Aceh, Bali, Banten, Jambi, Jawa Barat, Jawa Tengah, Jawa Timur, Kalimantan Tengah, Lampung, Maluku, Nusa Tenggara Barat, Papua, Sulawesi Selatan, Sulawesi Tenggara Siaga: Beberapa kabupaten/kota di Provinsi Bali, Jawa Barat, Papua, Sulawesi Selatan, Sumatra Selatan Awas : Tidak Ada Peringatan Dini Kekeringan Meteorologis: berlaku untuk Dasarian III Maret 2024 pada klasifikasi: Waspada: Aceh, Sumatra Utara , Siaga : Aceh, Sumatra Utara , Awas: Tidak ada',
      'Analisis Curah Hujan Dasarian III Maret 2024: Curah hujan pada Dasarian III Maret 2024 bervariasi dari kriteria rendah (19%), menengah (64%) dan tinggi (18%). Sifat hujan pada Dasarian III Maret 2024 bervariasi Bawah Normal (45%), Normal (20%) dan Atas Normal (35%).',
      'Analisis Perkembangan Musim Kemarau Dasarian III Maret 2024: Berdasarkan jumlah ZOM, sebanyak 7% wilayah Indonesia masuk musim kemarau. Wilayah yang sedang mengalami musim kemarau meliputi sebagian Aceh, sebagian Sumatera Utara, Riau bagian utara, sekitar Pangandaran Jawa Barat, sebagian Sulawesi Tengah dan sebagian Maluku Utara.',
      'Prediksi Curah Hujan Dasarian: April Dasarian I - April Dasarian III Tahun 2024 Pada April I - III 2024 umumnya diprediksi curah hujan berada di kriteria rendah - menengah (0 - 150 mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori tinggi - sangat tinggi (>150 mm/dasarian) :',
      '1) Pada April I 2024 meliputi Sebagian kecil Aceh bagian Barat, Sebagian kecil Sumatera Utara, Sumbar bagian Barat, Jambi, Sumatera Selatan, Lampung bagian Selatan, Sebagian Banten, Jawa Barat, Jawa Tengah bagian Utara, Jawa Timur, Bali, NTB, sebagian besar NTT, sebagian kecil Kalimantan Tengah, Sulawesi Selatan, Sulawesi Tenggara, dan Papua Tengah.',
      '2) Pada April II 2024 meliputi sebagian Aceh bagian Barat, sebagian kecil Jawa Barat, Jawa Tengah, NTB, NTT, Sulawesi Selatan dan Sebagian Papua Tengah.',
      '3) Pada April III 2024 meliputi sebagian kecil Banten, Jawa Barat, Jawa Tengah, Kalimantan Barat, Kalimantan Timur, Sulawesi Selatan, dan sebagian Papua Tengah.',
      'Prediksi Curah Hujan Lebih Dari 300 mm/Bulan untuk Bulan April 2024 - September 2024 :',
      '1) April - Mei 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Sumatera Barat, Riau, Jambi, Bengkulu, Sumatera Selatan, Bangka Belitung, Lampung, Banten, Jawa Barat, Jawa Tengah, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Selatan, Kalimantan Utara, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku, Maluku Utara, Papua Barat dan Papua.',
      '2) Juni - Juli 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian Sumatera Utara, Sumatera Barat, Kalimantan Barat, Kalimantan Selatan, Kalimantan Timur, Kalimantan Utara, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku Utara, Maluku, Papua Barat dan Papua bagian tengah.',
      '3) Agustus - September 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di Sebagian Sumatera Utara, Kalimantan Barat, Kalimantan Utara, Maluku, Papua Barat dan Papua bagian tengah.',
    ],
    link: "https://cdn.bmkg.go.id/Web/dinat-das-III-mar-2024.gif",
    pdfLink: "https://cdn.bmkg.go.id/Web/09.-Dinamika-Atmosfer-Dasarian-III-Maret-2024.pdf",
  },
  {
    key: 'dasa-2-maret-24',
    title: 'Analisis Dinamika Atmosfer Dasarian II Maret 2024',
    tgl: '25 Mar 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD:Hasil monitoring indeks IOD dan ENSO Dasarian II Maret 2024, Indek Dipole Mode sebesar +1.12 (IOD Positif), sedangkan indeks ENSO sebesar +1.21 (El Nino Moderate). IOD diprediksi pada kategori Netral dan terus bertahan hingga 5 bulan kedepan. Sementara itu, indeks ENSOdiprediksi turun secara gradual menuju Netral pada Mei 2024.',
      'Peringatan Dini:',
      '1) Peringatan Dini Curah Hujan Tinggi pada klasifikasiWaspada: Beberapa kabupaten/kota di Provinsi Kalimantan Barat, Kalimantan Tengah, Papua, Sumatra Selatan, Sulawesi Selatan;Siaga: Beberapa kabupaten/kota di Provinsi Aceh, Papua, Sumatra Selatan;Awas :Tidak ada.',
      '2) Peringatan Dini Kekeringan Meteorologis:Waspada: Aceh;Siaga: Tidak ada; Awas: Tidak ada',
      'Analisis Curah Hujan Dasarian II Maret 2024:',
      '1) Curah hujan pada Dasarian II Maret 2024 bervariasi dari kriteria rendah(65%), menengah(15%) dan tinggi(21%).',
      '2) Sifat hujan pada Dasarian II Maret 2024 bervariasi Bawah Normal(42%), Normal(21%) dan Atas Normal(7%).',
      'Analisis Perkembangan Musim Kemarau Dasarian II Maret 2024:Berdasarkan jumlah ZOM,sebanyak 8% wilayah Indonesia masuk musim kemarau. Wilayah yang sedang mengalami musim kemarau meliputi sebagian Aceh, sebagian Sumatera Utara,Riau bagian utara,sekitar Pangandaran JawaBarat, sebagian kecil Sulawesi Selatan,sebagian Sulawesi Tengah, sebagian Maluku Utara dan sebagian kecil Maluku.',
      'Prediksi Curah Hujan Dasarian :Maret Dasarian III-April Dasarian II Tahun 2024 Pada Maret III- April II 2024 umumnya diprediksi curah hujan berada di kriteria rendah-menengah(0-150mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori tinggi- sangat tinggi(>150mm/dasarian):',
      '1) Pada Maret III 2024 meliputi sebagian Aceh bagian barat, sebagian kecil Sumatera Utara, sebagian kecil Sumatera Barat, sebagian kecil Jawa Barat bagian tengah,sebagian kecil NTT,sebagian Kalimantan Barat bagian tengah, Kalimantan Tengah bagian tengah,sebagian kecil Kalimantan Timur, sebagian Sulawesi Selatan dan sebagian Papua.',
      '2) Pada April I 2024 meliputi sebagian Aceh bagian barat, Sumatra Utara bagian barat, Sumatra Barat bagian barat, sebagian kecil Banten, Sebagian Jawa Barat bagian tengah, Jawa Tengah bagian tengah, sebagian Jawa Timur bagian tengah, sebagian Bali, sebagian NTT, sebagian Kalimantan Barat, sebagian Kalimantan Tengah, sebagian Kalimantan Timur, sebagian Sulawesi Tengah,sebagian Sulawesi Selatan,sebagian Sulawesi Tenggara,sebagian Maluku dan sebagian Papua.',
      '3) Pada April II 2024 meliputi sebagian kecil Aceh bagian barat, sebagian kecil Sumatra Utara,sebagian kecil Sumatra Selatan,sebagian kecil Banten,sebagian Jawa Barat bagian tengah, Jawa Tengah bagian tengah, Jawa Timur bagian tengah, sebagian Bali,sebagian kecil NTB,sebagian NTT,sebagian kecil Kalimantan Timur, sebagian Sulawesi Selatan, sebagian Maluku,sebagian Papua Barat dan sebagian Papua.',
      'Prediksi Curah Hujan Lebih Dari 300mm/Bulan untuk Bulan April 2024- September 2024:',
      '1) April - Mei 2024 curah hujan> 300 mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Sumatera Barat, Riau, Jambi, Bengkulu, Sumatera Selatan, Bangka Belitung, Lampung,Banten, Jawa Barat, Jawa Tengah, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Selatan, Kalimantan Utara, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku, Maluku Utara, Papua Barat dan Papua.',
      '2) Juni - Juli 2024curahhujan> 300 mm/bulan berpeluang tinggi terjadi di sebagian Sumatera Utara, Sumatera Barat, Kalimantan Barat, Kalimantan Selatan, Kalimantan Timur, Kalimantan Utara, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku Utara, Maluku, Papua Barat dan Papua bagian tengah.',
      '3) Agustus - September 2024curahhujan> 300 mm/bulan berpeluang tinggi terjadi di Sebagian Sumatera Utara, Kalimantan Barat, Kalimantan Utara, Maluku, Papua Barat dan Papua bagian tengah',
    ],
    link: "https://cdn.bmkg.go.id/Web/Dinat-Das-II-Mar-2024.gif",
    pdfLink: "https://cdn.bmkg.go.id/Web/2024.03.21_Update-Informasi-Iklim-Dasarian-II-Maret-2024.pdf",
  },
  {
    key: 'dasa-1-maret-24',
    title: 'Analisis Dinamika Atmosfer Dasarian I Maret 2024',
    tgl: '13 Mar 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD:Hasil monitoring indeks IOD dan ENSO Dasarian I Maret 2024, Indek Dipole Mode sebesar 0.19 (IOD Netral), sedangkan indeks ENSO sebesar +1.59 (El Nino Moderate). IOD Netral diprediksi terus bertahan hingga 5 bulan kedepan. Sementara itu, indeks ENSO diprediksi turun secara gradual menuju Netral pada Mei 2024.',
      'Peringatan Dini:',
      '1) Peringatan Dini Curah Hujan Tinggi pada klasifikasiWaspada: Beberapa kabupaten/kota di Provinsi Bengkulu, Banten, DI Yogyakarta, Jawa Barat, Jawa Tengah, Jawa Timur, Kalimantan Selatan, Kalimantan Tengah, Maluku, Nusa Tenggara Barat, Nusa Tenggara Timur, Papua, Sumatra Utara, Sulawesi Tenggara;Siaga: Beberapa kabupaten/kota di Provinsi Banten, Jawa Barat, Nusa Tenggara Timur;Awas :Tidak ada.',
      '2) Peringatan Dini Kekeringan Meteorologis:Waspada: Tidakada; Siaga: Tidak ada; Awas: Tidak ada',
      'Analisis Curah Hujan Dasarian I Maret 2024: Curah hujan pada Dasarian I Maret 2024 bervariasi dari kriteria rendah (6%), menengah (60%) dan tinggi (34%). Sifat hujan pada Dasarian I Maret 2024 bervariasi Bawah Normal (11%), Normal (14%) dan Atas Normal (76%).',
      'Analisis Perkembangan Musim Hujan Dasarian I Maret 2024: Berdasarkan jumlah ZOM, sebanyak 78% wilayah Indonesia masuk musim hujan. Wilayah yang sedang mengalami musim hujan meliputi sebagian Aceh, sebagian Sumatera Utara, Riau hingga Lampung, Banten, sebagian besar Jawa Barat, Jawa Tengah, DIY, Jawa Timur, Bali, NTB, NTT, sebagian besar Pulau Kalimantan, Sulawesi Utara, Gorontalo, sebagian Sulawesi Tengah, Sulawesi Barat, sebagian besar Sulawesi Selatan, Sulawesi Tenggara, sebagian Maluku Utara, Maluku, dan Pulau Papua. Beberapa ZOM di wilayah Aceh dan Sumatera Utara sudah memasuki periode musim kemarau kembali sesuai dengan pola iklim normalnya.',
      'Prediksi Curah Hujan Dasarian: Maret Dasarian II - April Dasarian I Tahun 2024 Pada Maret II - April I 2024 umumnya diprediksi curah hujan berada di kriteria rendah - menengah (0 - 150 mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori tinggi - sangat tinggi (>150 mm/dasarian) :',
      '1) Pada Maret II 2024 meliputi sebagian Banten, sebagian Jawa Barat, Jawa Tengah bagian tengah, sebagian Jawa Timur, sebagian Bali, sebagian NTB, sebagian NTT, sebagian Sulawesi Selatan, sebagian Maluku dan sebagian Papua.',
      '2) Pada Maret III 2024 meliputi sebagian Aceh bagian barat, Sumatra Utara bagian barat, Sumatra Barat bagian barat, sebagian Banten, Sebagian Jawa Barat, Jawa Tengah bagian tengah, sebagian Jawa Timur, sebagian Bali, sebagian NTT, sebagian Kalimantan Barat, Kalimantan Tengah bagian tengah, sebagian Kalimantan Timur, sebagian Sulawesi Selatan dan sebagian Papua.',
      '3) Pada April I 2024 meliputi sebagian Aceh bagian barat, Sumatra Utara bagian barat, Sumatra Barat bagian barat, sebagian Banten, sebagian Jawa Barat, Jawa Tengah bagian tengah, Jawa Timur bagian tengah, sebagian Bali, sebagian NTT, sebagian Sulawesi Selatan, Sulawesi Tengah bagian tengah dan Papua bagian tengah.',
      'Prediksi Curah Hujan Lebih Dari 300 mm/Bulan untuk Bulan April 2024 - September 2024 :',
      '1) April - Mei 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Sumatera Barat, Riau, Jambi, Bengkulu, Sumatera Selatan, Bangka Belitung, Lampung, Banten, Jawa Barat, Jawa Tengah, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Selatan, Kalimantan Utara, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku, Maluku Utara, Papua Barat dan Papua.',
      '2) Juni - Juli 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian Sumatera Utara, Sumatera Barat, Kalimantan Barat, Kalimantan Selatan, Kalimantan Timur, Kalimantan Utara, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku Utara, Maluku, Papua Barat dan Papua bagian tengah.',
      '3) Agustus - September 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di Sebagian Sumatera Utara, Kalimantan Barat, Kalimantan Utara, Maluku, Papua Barat dan Papua bagian tengah.',
    ],
    link: "https://cdn.bmkg.go.id/Web/dinat-mar-I-2024.gif",
    pdfLink: "https://cdn.bmkg.go.id/Web/2024.03.11_Update-Informasi-Iklim-Dasarian-I-Maret-2024.pdf",
  },
  {
    key: 'dasa-3-februari-24',
    title: 'Analisis Dinamika Atmosfer Dasarian III Februari 2024',
    tgl: '02 Mar 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD: Hasil monitoring indeks IOD dan ENSO Dasarian III Februari 2024, Indeks Dipole Mode sebesar -0.43 (IOD Netral), sedangkan indeks ENSO Dasarian III Februari menunjukkan nilai sebesar +1.4 (El Nino Moderate). IOD Netral diprediksi terus bertahan hingga 5 bulan kedepan. Sementara itu, indeks ENSO diprediksi turun secara gradual menuju Netral pada April 2024.',
      'Peringatan Dini Curah Hujan Tinggi :',
      '1) Waspada : Beberapa kabupaten/kota di Provinsi Bali, Bengkulu, Banten, DI Yogyakarta, Jawa Barat, Jawa Tengah, Jawa Timur, Kalimantan Barat, Kalimantan Selatan, Kalimantan Tengah, Nusa Tenggara Barat, Nusa Tenggara Timur, Papua, Papua Barat, Sulawesi Selatan, Sumatera Barat.',
      '2) Siaga : Beberapa kabupaten/kota di Provinsi Aceh, Bali, Banten, Jawa Barat, Jawa Tengah, Jawa Timur, Nusa Tenggara Barat, Nusa Tenggara Timur, Papua, Sulawesi Selatan.',
      '3) Awas : Tidak ada.',
      'Peringatan Dini Kekeringan Meteorologis :Waspada : Kab. Aceh Utara (Aceh)Siaga : Tidak ada.Awas : Tidak ada.',
      'Analisis Curah Hujan Dasarian III Februari 2024: Curah hujan pada Dasarian III Februari 2024 bervariasi dari kriteria rendah (30%), menengah (62%) dan tinggi (9%). Sifat hujan pada Dasarian III Februari 2024 bervariasi Bawah Normal (35%), Normal (24%) dan Atas Normal (41%).',
      'Analisis Perkembangan Musim Hujan Dasarian III Februari 2024: Berdasarkan jumlah ZOM, sebanyak 76% wilayah Indonesia masuk musim hujan. Wilayah yang sedang mengalami musim hujan meliputi sebagian Aceh, sebagian Sumatera Utara, Riau hingga Lampung, Banten hingga NTT, seluruh Pulau Kalimantan, sebagian besar Sulawesi Utara, sebagian Sulawesi Tengah, Sulawesi Barat, sebagian Sulawesi Selatan, sebagian besar Sulawesi Tenggara, sebagian Maluku Utara, dan sebagian besar Maluku, dan Pulau Papua. Beberapa ZOM di wilayah Sumatera bagian utara sudah memasuki periode musim kemarau kembali sesuai dengan pola iklim normalnya.',
      'Prediksi Curah Hujan Dasarian: Maret Dasarian I - III Tahun 2024:Pada Maret I - III 2024 umumnya diprediksi curah hujan berada di kriteria rendah - menengah (0 - 150 mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori tinggi - sangat tinggi (>150 mm/dasarian) :',
      '1) Pada Maret I 2024 meliputi sebagian Aceh, sebagian Lampung, Banten, sebagian Jawa Barat, sebagian Jawa Tengah, sebagian Jawa Timur, sebagian Bali, sebagian NTB, sebagian NTT, sebagian Kalimantan Barat, sebagian Kalimantan Tengah, sebagian Kalimantan Selatan, sebagian Sulawesi Selatan dan sebagian Papua',
      '2) Pada Maret II 2024 meliputi sebagian kecil Lampung, sebagian Banten, sebagian Jawa Barat, Jawa Tengah bagian tengah, sebagian Jawa Timur, sebagian Bali, sebagian NTB, sebagian NTT, sebagian Sulawesi Selatan dan sebagian Papua.',
      '3) Pada Maret III 2024 meliputi sebagian Aceh bagian barat, Sumatra Utara bagian barat, Sumatra Barat bagian barat, sebagian Banten, Sebagian Jawa Barat, Jawa Tengah bagian tengah, sebagian Jawa Timur, sebagian Bali, sebagian NTT, sebagian Kalimantan Barat, Kalimantan Tengah bagian tengah, sebagian kecil Kalimantan Timur, sebagian Sulawesi Selatan, sebagian Maluku dan sebagian Papua',
      'Prediksi Curah Hujan Lebih Dari 300 mm/Bulan untuk Bulan Maret 2024 - Agustus 2024 :',
      '1) Maret - April 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Sumatera Barat, Riau, Jambi, Bengkulu , Sumatera Selatan, Bangka Belitung, Lampung, sebagian besar Pulau Jawa, Bali, NTB, NTT, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Selatan, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku, Papua Barat dan Papua.',
      '2) Mei 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Utara, sebagian Kalimantan Selatan, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku Utara, Maluku, Papua Barat dan Papua bagian tengah .',
      '3) Juni - Juli 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di Kalimantan Timur, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Sulawesi Utara, Maluku Utara, Maluku, Papua Barat dan Papua bagian tengah.',
      '4) Agustus 2024 curah hujan > 300mm/bulan berpeluang tinggi terjadi di sebagian Kalimantan Barat, Maluku Utara, Maluku, Papua Barat dan Papua bagian tengah.',
    ],
    link: "https://cdn.bmkg.go.id/Web/dinat-feb-III-2024.gif",
    pdfLink: "https://cdn.bmkg.go.id/Web/2024.03.01_Update-Informasi-Iklim-Dasarian-III-Februari-2024.pdf",
  },
  {
    key: 'dasa-2-februari-24',
    title: 'Analisis Dinamika Atmosfer Dasarian II Februari 2024',
    tgl: '23 Feb 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD:Hasil monitoring indeks IOD dan ENSO Dasarian II Februari 2024, Indek Dipole Mode sebesar -0.21 (IOD Netral), sedangkan indeks ENSO Dasarian II Februari menunjukkan nilai sebesar +1.5 (El Nino Moderate). IOD Netral diprediksi terus bertahan hingga 5 bulan kedepan. Sementara itu, indeks ENSO diprediksi turun secara gradual menuju Netral pada April 2024.',
      'Analisis dan Prediksi Angin 850mb:Aliran masa udara didominasi angin baratan. Streamline angin menunjukkan belokan angin terjadi di sepanjang ekuator. Sistem tekanan rendah terlihat perairan selatan Jawa. Pada Dasarian III Februari 2024 aliran massa udara di wilayah Indonesia diprediksi akan didominasi oleh angin baratan. Daerah belokan angin diprediksi terjadi di sepanjang ekuator. Sistem tekanan rendah terlihat perairan barat Sumatera.',
      'Analisis OLR:Daerah tutupan awan (OLR =220 W/m2) pada dasarian II Februari 2024 menunjukkan MJO tidak aktif dan diprediksi akan tidak aktif hingga pertengahan dasarian III Februari 2024 kemudian diprakiraan aktif pada fase 4 dan 5 (Maritim Indonesia) hingga awal dasarian I Maret 2024. MJO berkaitan dengan potensi pengurangan awan hujan di wilayah Indonesia.',
      'Analisis dan Prediksi MJO:Analisis pada dasarian II Februari 2024 menunjukkan MJO tidak aktif dan diprediksi akan tidak aktif hingga pertengahan dasarian III Februari 2024 kemudian diprakiraan aktif pada fase 4 dan 5 (Maritim Indonesia) hingga awal dasarian I Maret 2024. MJO berkaitan dengan potensi pengurangan awan hujan di wilayah Indonesia.',
      'Analisis dan Prediksi Kelembapan Udara (RH):Kelembapan udara permukaan berkisar 55-75% dan diprediksi hingga Dasarian I Maret 2024 berkisar 55-80 %, pada lapisan 850mb diprediksi berkisar 50-80% serta pada lapisan 700 mb umumnya diprediksi 45-80%.',
      'Analisis dan Prediksi Suhu:Suhu rata-rata permukaan berkisar 22-28°C dan diprediksi hingga Dasarian I Maret 2024 berkisar 22-28°C, Prediksi suhu minimum berkisar 20-25°C dan Prediksi suhu maksimum berkisar 26-34°C.',
      'Peringatan Dini:Peringatan Dini Curah Hujan Tinggi pada klasifikasi Waspada: Beberapa kabupaten/kota di Provinsi Kalimantan Tengah, Jawa Timur, Sulawesi Selatan dan Papua. Peringatan Dini Kekeringan Meteorologis : Waspada: Kab. Aceh Utara (Aceh) dan Deliserdang (Sumut) Siaga: Bireuen (Aceh). Awas: Tidak ada',
      'Analisis Curah Hujan Dasarian II Februari 2024:Curah hujan pada Dasarian II Februari 2024 bervariasi dari kriteria rendah (29%) hingga menengah (60%); Sifat hujan pada Dasarian II Februari 2024 bervariasi Bawah Normal (47%) hingga Normal (18%).',
      'Analisis Perkembangan Musim Hujan Dasarian II Februari 2024:Berdasarkan jumlah ZOM, sebanyak 76% (531 ZOM) wilayah Indonesia masuk musim hujan. Wilayah yang sedang mengalami musim hujan meliputi Aceh, sebagian Sumatera Utara, Riau, Kepulauan Riau, Sumatera Barat, Jambi, Bengkulu, Sumatera Selatan, Bangka Belitung, Lampung, Banten, DKI Jakarta, sebagian besar Jawa Barat, Jawa Tengah, sebagian Jawa Timur, seluruh Pulau Kalimantan, sebagian besar Sulawesi Utara, sebagian Sulawesi Tengah, Sulawesi Barat, sebagian Sulawesi Selatan, sebagian besar Sulawesi Tenggara, sebagian Bali, sebagian NTT, sebagian besar NTB, sebagian Maluku Utara, dan sebagian besar Maluku, seluruh Pulau Papua. Beberapa ZOM di wilayah Sumatera bagian utara sudah memasuki periode musim kemarau kembali sesuai dengan pola iklim normalnya.',
      'Prediksi Curah Hujan Dasarian: Februari Dasarian III- Maret Dasarian II Tahun 2024:Pada Februari III - Mar II 2024 umumnya diprediksi curah hujan berada di kriteria rendah - menengah (0 - 150 mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori tinggi - sangat tinggi (>150 mm/dasarian) :',
      '1) Pada Februari III 2024 meliputi sebagian Jawa Barat, sebagian Jawa Tengah, sebagian Kalimantan Barat, sebagian Sulawesi Selatan, sebagian NTT dan sebagian Papua.',
      '2) Pada Maret I 2024 meliputi sebagian Jawa Barat, sebagian Jawa Tengah, sebagian Jawa Timur, sebagian Kalimantan Barat, sebagian kalimantan Tengah, sebagian Sulawesi Selatan, sebagian NTT dan sebagian Papua',
      '3) Pada Maret II 2024 meliputi sebagian kecil Lampung, sebagian Pulau Jawa, sebagian Kalimantan Barat, sebagian Sulawesi Selatan, sebagian NTT dan sebagian Papua.',
      'Prediksi Curah Hujan Lebih Dari 300 mm/Bulan untuk Bulan Maret 2024 -Agustus 2024 :',
      '1) Maret - April 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Sumatera Barat, Riau, Jambi, Bengkulu , Sumatera Selatan, Bangka Belitung, Lampung, sebagian besar Pulau Jawa, Bali, NTB, NTT, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Selatan, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku, Papua Barat dan Papua.',
      '2) Mei 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Utara, sebagian Kalimantan Selatan, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku Utara, Maluku, Papua Barat dan Papua bagian tengah .',
      '3) Juni - Juli 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di Kalimantan Timur, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Sulawesi Utara, Maluku Utara, Maluku, Papua Barat dan Papua bagian tengah.',
      '4) Agustus 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Kalimantan Barat, Maluku Utara, Maluku, Papua Barat dan Papua bagian tengah .',
    ],
    link: "https://cdn.bmkg.go.id/Web/dinat-das-II-Feb-2024.gif",
    pdfLink: "https://cdn.bmkg.go.id/Web/05.-Dinamika-Atmosfer-Dasarian-II-Februari-2024.pdf",
  },
  {
    key: 'dasa-1-februari-24',
    title: 'Analisis Dinamika Atmosfer Dasarian I Februari 2024',
    tgl: '12 Feb 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD:Hasil monitoring indeks IOD dan ENSO Dasarian I Februari 2024, Indek Dipole Mode sebesar +0.22 (Netral) (IOD Netral), sedangkan indeks ENSO Dasarian I Februari menunjukkan nilai sebesar +1.9 (Moderat). (El nino Moderate). IOD Netral diprediksi terus bertahan hingga 3 bulan kedepan. Sementara itu, indeks ENSO diprediksi turun secara gradual menuju Netral pada April 2024.',
      'Analisis dan Prediksi Angin 850mb:Aliran masa udara didominasi angin baratan, belokan angin terjadi di sepanjang ekuator. Sistem tekanan rendah terlihat di perairan barat Sumatera. Pada Dasarian II Februari 2024 aliran massa udara di wilayah Indonesia diprediksi masih didominasi oleh angin baratan. Daerah belokan angin diprediksi terjadi di sepanjang ekuator. Pertemuan angin terlihat di perairan selatan Jawa.',
      'Analisis OLR:Daerah tutupan awan (OLR =220 W/m2) pada dasarian I Februari 2024 terlihat di hampir seluruh wilayah Indonesia, kecuali di wilayah Sumatera bagian utara, NTB, NTT, dan Maluku Utara. Tutupan awan umumnya lebih sedikit dibandingkan klimatologisnya.',
      'Analisis dan Prediksi MJO:Analisis dasarian I Februari 2024 menunjukkan MJO aktif di fase 7 dan di prediksi akan tetap aktif di fase 8 dan 7 hingga awal dasarian II Februari 2024 kemudian diprakiraan tidak aktif hingga awal dasarian III Februari 2024. MJO berkaitan dengan potensi pengurangan awan hujan di wilayah Indonesia.',
      'Analisis dan Prediksi Kelembapan Udara (RH):Kelembapan udara permukaan berkisar 60- 75% dan diprediksi hingga Dasarian III Februari 2024 berkisar 55 - 80 %, pada lapisan 850mb diprediksi berkisar 50 - 80% serta pada lapisan 700 mb umumnya diprediksi 45 - 75%.',
      'Analisis dan Prediksi Suhu:Suhu rata-rata permukaan berkisar 23 - 28°C dan diprediksi hingga Dasarian III Februari 2024 berkisar 22-28°C, Prediksi suhu minimum berkisar 20- 24°C dan Prediksi suhu maksimum berkisar 26-34°C.',
      'Peringatan Dini:Peringatan Dini Curah Hujan Tinggi pada klasifikasi Waspada: Beberapa kabupaten kota di Provinsi Aceh, Sumatera Utara, Sumatera Selatan, Jawa Barat, Jawa Tengah, Jawa Timur, Kalimantan Selatan, Kalimantan Barat, Papua, Sulawesi Selatan, Sulawesi Tenggara. Siaga: Beberapa kabupaten kota di Provinsi Jawa Barat, Jawa Tengah, Kalimantan Barat, Papua, Sulawesi Selatan. Awas : Tidak ada. Peringatan Dini Kekeringan Meteorologis : Waspada: Tidak ada. Siaga: Tidak ada. Awas: Tidak ada',
      'Analisis Curah Hujan Dasarian I Februari 2024:- Curah hujan pada Dasarian I Februari 2024 bervariasi dari kriteria rendah, menengah dan tinggi. Sifat hujan pada Dasarian I Februari 2024 bervariasi Bawah Normal, Normal dan Atas Normal.',
      'Analisis Perkembangan Musim Hujan Dasarian I Februari 2024:Berdasarkan jumlah ZOM, sebanyak 76% wilayah Indonesia masuk musim hujan. Wilayah yang sedang mengalami musim hujan meliputi Aceh, sebagian Sumatera Utara, Riau, Kepulauan Riau, Sumatera Barat, Jambi, Bengkulu, Sumatera Selatan, Bangka Belitung, Lampung, Banten, DKI Jakarta, sebagian besar Jawa Barat, Jawa Tengah, sebagian Jawa Timur, seluruh Pulau Kalimantan, sebagian besar Sulawesi Utara, sebagian Sulawesi Tengah, Sulawesi Barat, sebagian Sulawesi Selatan, sebagian besar Sulawesi Tenggara, sebagian Bali, sebagian NTT, sebagian besar NTB, sebagian Maluku Utara, dan sebagian besar Maluku, seluruh Pulau Papua.',
      'Prediksi Curah Hujan Dasarian: Februari Dasarian II - Maret Dasarian I Tahun 2024:Pada Februari II - Mar I 2024 umumnya diprediksi curah hujan berada di kriteria rendah - menengah (0 - 150 mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori tinggi - sangat tinggi(>150 mm/dasarian) :',
      '1) Pada Februari II 2024 meliputi sebagian Jawa Barat, sebagian Jawa Tengah , sebagian Kalimantan Barat, sebagian Sulawesi Selatan, sebagian NTT dan sebagian Papua .',
      '2) Pada Februari III 2024 meliputi sebagian Sulawesi Selatan.',
      '3) Pada Maret I 2024 meliputi sebagian Lampung, sebagian Pulau Jawa, sebagian Kalimantan Barat, sebagian Kalimantan Tengah , sebagian Sulawesi Selatan, sebagian NTT dan sebagian Papua.',
      'Prediksi Curah Hujan Lebih Dari 300 mm/Bulan untuk Bulan Maret 2024 -Agustus 2024 :',
      '1) Maret - April 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Aceh, Sumatera Utara, Sumatera Barat, Riau, Jambi, Bengkulu , Sumatera Selatan, Bangka Belitung, Lampung, sebagian besar Pulau Jawa, Bali, NTB, NTT, Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Selatan, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku, Papua Barat dan Papua.',
      '2) Mei 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Kalimantan Barat, Kalimantan Tengah, Kalimantan Timur, Kalimantan Utara, sebagian Kalimantan Selatan, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Maluku Utara, Maluku, Papua Barat dan Papua bagian tengah .',
      '3) Juni - Juli 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di Kalimantan Timur, Sulawesi Selatan, Sulawesi Barat, Sulawesi Tengah, Sulawesi Tenggara, Sulawesi Utara, Maluku Utara, Maluku, Papua Barat dan Papua bagian tengah.',
      '4) Agustus 2024 curah hujan > 300 mm/bulan berpeluang tinggi terjadi di sebagian Kalimantan Barat, Maluku Utara, Maluku, Papua Barat dan Papua bagian tengah .',
    ],
    link: "https://cdn.bmkg.go.id/Web/dinat-das-I-Feb-2024.gif",
    pdfLink: "https://cdn.bmkg.go.id/Web/04.-Dinamika-Atmosfer-Dasarian-I-Februari-2024.pdf",
  },
  {
    key: 'dasa-3-januari-24',
    title: 'Analisis Dinamika Atmosfer Dasarian III Januari 2024',
    tgl: '02 Feb 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD:Hasil monitoring indeks IOD dan ENSO Dasarian III Januari 2024, Indek Dipole Mode sebesar +0.43, sedangkan indeks ENSO Dasarian III Januari menunjukkan nilai sebesar +1.66, IOD Netral terus beratahan hingga 3 bulan kedepan. Sementara itu, indeks ENSO diprediksi turun secara gradual menuju Netral pada April 2024.',
      'Analisis dan Prediksi Angin 850mb:Aliran masa udara didominasi angin baratan, belokan angin terjadi di sepanjang garis ekuator, sistem tekanan rendah terlihat pada perairan di barat Sumatera. Pada Dasarian I Februari 2024 aliran massa udara di wilayah Indonesia diprediksi masih terus didominasi oleh angin baratan, daerah belokan angin diprediksi terjadi di sepanjang garis ekuator, sistem tekanan rendah akan terjadi di Kalimantan bagian utara dan perairan di barat Sumatera.',
      'Analisis OLR:Daerah tutupan awan (OLR =220 W/m2) pada dasarian III Januari 2024 terlihat di hampir seluruh wilayah Indonesia. Tutupan awan umumnya mendekati klimatologisnya.',
      'Analisis dan Prediksi MJO:Analisis dasarian III Januari 2024 menunjukkan MJO aktif di fase 7 dan di prediksi akan tetap aktif di fase 6 dan 7 hingga awal dasarian II Februari 2024, MJO fase 6 dan 7 berkaitan dengan fase kering di wilayah Indonesia bagian barat.',
      'Analisis dan Prediksi Kelembapan Udara (RH):Kelembapan udara permukaan berkisar 60- 72% dan diprediksi hingga Dasarian II Februari 2024 berkisar 55 - 80 %, pada lapisan 850mb diprediksi berkisar 50 - 80% serta pada lapisan 700 mb umumnya diprediksi 45 - 75%.',
      'Analisis dan Prediksi Suhu:Suhu rata-rata permukaan berkisar 23 - 28°C dan diprediksi hingga Dasarian II Februari 2024 berkisar 22-28°C, Prediksi suhu minimum berkisar 20 - 26°C dan Prediksi suhu maksimum berkisar 26-34°C.',
      'Peringatan Dini:Peringatan Dini Curah Hujan Tinggi pada klasifikasi Waspada: Beberapa kabupaten kota di Provinsi Banten, DIY, DKI Jakarta, Jambi, Jawa Barat, Jawa Tengah, Jawa Timur, Kalimantan Selatan, Kalimantan Tengah, Kalimantan Timur, Kalimantan Utara, Lampung, Papua, Sulawesi Selatan, Sulawesi Utara, Sumatera Selatan, Sulawesi Tenggara. Siaga: Beberapa kabupaten kota di Provinsi Jawa Barat, Jawa Tengah, Kalimantan Timur, Papua, Sulawesi Selatan. Awas : Beberapa kabupaten kota di Provinsi Sulawesi Selatan. Peringatan Dini Kekeringan Meteorologis : Waspada: Kab. Bireuen di Prov. Aceh. Siaga: Tidak ada. Awas: Tidak ada',
      'Analisis Curah Hujan Dasarian III Januari 2024:Curah hujan pada Dasarian III Januari 2024 bervariasi dari kriteria rendah, menengah dan tinggi. Sifat hujan pada Dasarian III Januari 2024 bervariasi Bawah Normal, Normal dan Atas Normal.',
      'Analisis Perkembangan Musim Hujan Dasarian III Januari 2024:Berdasarkan jumlah ZOM, sebanyak 76% wilayah Indonesia masuk musim hujan. Wilayah yang sedang mengalami musim hujan meliputi Aceh, Sumatera Utara, Riau, Kepulauan Riau, Sumatera Barat, Jambi, Bengkulu, Sumatera Selatan, Bangka Belitung, Lampung, Banten, DKI Jakarta, sebagian besar Jawa Barat, Jawa Tengah, Jawa Timur, seluruh Pulau Kalimantan, Sebagian besar Sulawesi Utara, sebagian Sulawesi Tengah, Sulawesi Barat, sebagian Sulawesi Selatan, sebagian besar Sulawesi Tenggara, sebagian Bali, sebagian NTT, sebagian besar NTB, sebagian Maluku Utara, dan sebagian besar Maluku, seluruh Pulau Papua.',
      'Prediksi Curah Hujan Dasarian: Februari Dasarian I - III Tahun 2024:Pada Februari I - III Tahun 2024 umumnya diprediksi curah hujan berada di kriteria rendah - menengah (0 - 150 mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori tinggi - sangat tinggi (>150 mm/dasarian) :',
      '1) Pada Februari I meliputi sebagian sebagian Jambi, sebagian Sumatra Selatan, sebagian Lampung, Banten bagian Barat, sebagian Jawa Barat, Jawa Tengah bagian Utara, sebagian kecil Jawa Timur, sebagian NTT, Kalimantan Timur bagian utara, sebagian Sulawesi Selatan, sebagian Sulawesi Tenggara dan sebagian Papua bagian Tengah.',
      '2) Pada Februari II meliputi sebagian DKI Jakarta, sebagian Jawa Barat, Jawa Tengah bagian utara, sebagian kecil Jawa Timur, sebagian Kalimantan Barat, sebagian Sulawesi Selatan, sebagian kecil Sulawesi tenggara dan sebagian Papua bagian Tengah.',
      '3) Pada Februari III meliputi Jawa Tengah bagian utara, sebagian Sulawesi Selatan dan sebagian Papua.',
      'Prediksi Curah Hujan Lebih Dari 300 mm/Bulan untuk Bulan Februari 2024 - Juli 2024 :',
      '1) Februari 2024 diprediksi terjadi di sebagian Sumatera Bagian Selatan, sebagian Kalimantan Barat, sebagian besar Kalimantan Tengah, sebagian Kalimantan Selatan, sebagian Banten, sebagian Jawa Barat, sebagian Jawa Tengah, sebagian Jawa Timur, sebagian Bali, sebagian NTB, sebagian NTT, sebagian Sulawesi Selatan, sebagian Maluku, sebagian Papua Barat, dan sebagian Papua.',
      '2) Maret - April 2024 diprediksi terjadi sebagian Aceh, sebagian Bengkulu, sebagian Jambi, sebagian Sumatera Selatan, sebagian Lampung, sebagian besar Pulau Kalimantan, sebagian Pulau Jawa, sebagian Bali, sebagian NTB, sebagian NTT, sebagian Sulawesi Barat, sebagian Sulaswesi Selatan, sebagian besar Papua Barat dan sebagian besar Papua.',
      '3) Mei 2024 diprediksi terjadi di sebagian Kalimantan Barat, sebagian Kalimantan Tengah, sebagian Kalimantan Utara, sebagian Kalimantan Timur, sebagian kecil Kalimantan Selatan, sebagian Sulawesi Barat, sebagian besar Sulaswesi Selatan, sebagian Sulaswesi Tengah, sebagian kecil Suawesi Tenggara, sebagian Maluku, sebagian Maluku Utara, sebagian Papua Barat, dan sebagian Papua.',
      '4) Juni - Juli 2024 diprediksi terjadi di sebagian kecil di Pulau Kalimantan, pesisir timur Sulawesi Selatan, sebagian Sulawesi Tengah, sebagian besar Maluku, sebagian Maluku Utara, sebagian besar Papua Barat, dan sebagian Papua.',
    ],
    link: "https://cdn.bmkg.go.id/Web/dinat-das-III-jan-2024.gif",
    pdfLink: "https://cdn.bmkg.go.id/Web/03.-Dinamika-Atmosfer-Dasarian-III-Januari-2024.pdf",
  },
  {
    key: 'dasa-2-januari-24',
    title: 'Analisis Dinamika Atmosfer Dasarian II Januari 2024',
    tgl: '24 Jan 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'Analisis dan Prediksi ENSO dan IOD:Hasil monitoring indeks IOD dan ENSO Dasarian II Januari 2024, Indek Dipole Mode sebesar (+0.76), sedangkan indeks ENSO Dasarian II Januari menunjukkan indeks (+1.79), IOD diprediksi memasuki kondisi Netral mulai Januari 2024. Sementara itu, indeks ENSO diprediksi turun secara gradual menuju Netral mulai April 2024.',
      'Analisis dan Prediksi Angin 850mb:Aliran masa udara didominasi angin dari barat. Streamline angin menunjukkan belokan angin terjadi di sepanjang garis ekuator. Sistem tekanan rendah terlihat di Kalimantan bagian barat. Aliran massa udara di wilayah Indonesia pada Dasarian III Januari 2024 diprediksi didominasi oleh angin baratan. Daerah pertemuan dan belokan angin diprediksi terjadi di sepanjang garis ekuator.',
      'Analisis OLR:Daerah tutupan awan (OLR =220 W/m2) pada dasarian II Januari 2024 terlihat di hampir seluruh wilayah Indonesia. Tutupan awan umumnya lebih tinggi dibandingkan klimatologisnya.',
      'Analisis dan Prediksi MJO:Analisis dasarian II Januari 2024 menunjukkan MJO aktif di fase 5 dan di prediksi akan tetap aktif di fase 5 dan 6 hingga awal dasarian I Februari 2024, MJO berkaitan dengan peningkatan konveksi/potensi awan hujan di wilayah Indonesia bagian barat.',
      'Analisis dan Prediksi Kelembapan Udara (RH):Kelembapan udara permukaan berkisar 60- 73% dan diprediksi hingga Dasarian II Februari 2024 berkisar 58 - 77 %, pada lapisan 850mb diprediksi berkisar 55 - 77% serta pada lapisan 700 mb umumnya diprediksi 49 - 76%.',
      'Analisis dan Prediksi Suhu:Suhu rata-rata permukaan berkisar 23 - 28°C dan diprediksi hingga Dasarian II Februari 2024 berkisar 22-28°C, Prediksi suhu minimum berkisar 10 - 27°C dan Prediksi suhu maksimum berkisar 26-32°C.',
      'Peringatan Dini:Peringatan Dini Curah Hujan Tinggi pada klasifikasi Waspada: Beberapa Kabupaten di Provinsi Lampung, Banten, Jawa Barat, Jawa Tengah, D.I Yogyakarta, Jawa Timur, Nusa Tenggara Timur, Sulawesi Utara, Sulawesi Selatan, Sulawesi Tenggara, Papua Barat dan Papua. Siaga: Beberapa Kabupaten di Provinsi Jawa Barat, Jawa Tengah, Nusa Tenggara Barat, Sulawesi Selatan, dan Papua. Awas : Beberapa Kabupaten di Provinsi Nus Tenggara Barat dan Sulawesi Selatan. Peringatan Dini Kekeringan Meteorologis : Tidak ada',
      'Analisis Curah Hujan Dasarian II Januari 2024:Curah hujan pada Dasarian II Januari 2024 umumnya berada di kriteria menengah - Tinggi (50 - 300 mm/dasarian). Sifat hujan pada Dasarian II Januari 2024 umumnya Normal hingga Atas Normal.',
      'Analisis Perkembangan Musim Hujan Dasarian II Januari 2024:Berdasarkan jumlah ZOM, sebanyak 70% wilayah Indonesia masuk musim hujan. Wilayah yang sedang mengalami musim hujan meliputi Aceh, Sumatera Utara, Riau, Kepulauan Riau, Sumatera Barat, Jambi, Bengkulu, Sumatera Selatan, Bangka Belitung, Lampung, sebagian Banten, sebagian besar Jawa Barat, Jawa Tengah, Jawa Timur, seluruh Pulau Kalimantan, Sulawesi Utara, sebagian Sulawesi Tengah, sebagian Sulawesi Barat, sebagian Sulawesi Selatan, sebagian Sulawesi Tenggara, sebagian Bali, sebagian NTT, sebagian NTB, sebagian Maluku Utara, dan sebagian Maluku.',
      'Prediksi Curah Hujan Dasarian: Januari Dasarian III - Februari Dasarian II 2024:Pada Januari III - Februari II 2024 umumnya diprediksi curah hujan berada di kriteria rendah - menengah (0 - 150 mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori tinggi - sangat tinggi (>150 mm/dasarian) :',
      '1) Pada Januari III 2024 meliputi sebagian Aceh bagian tengah, sebagian kecil Lampung, Banten bagian Barat, Jawa Barat bagian Timur, pesisir Utara Jawa Tengah, sebagian kecil Jawa Timur, sebagian sebagian NTB, NTT, Sulawesi Selatan bagian Selatan, Sulawesi Tenggara dan sebagian Papua bagian Tengah.',
      '2) Pada Februari I 2024 meliputi sebagian Banten bagian Barat, Jawa Barat bagian Timur, Jawa Tengah bagian Utara, sebagian kecil Jawa Timur, sebagian NTT, sebagian Sulawesi Selatan dan sebagian Papua bagian Tengah.',
      '3) Pada Februari II 2024 meliputi sebagian Jawa Barat, Jawa Tengah bagian Utara, sebagian kecil Jawa Timur, sebagian Sulawesi Selatan, sebagian kecil Sulawesi tenggara dan sebagian Papua bagian Tengah.',
      'Prediksi Curah Hujan Lebih Dari 300 mm/Bulan untuk Bulan Februari 2024 - Juli 2024 :',
      '1) Februari 2024 diprediksi terjadi di sebagian Sumatera Bagian Selatan, sebagian Kalimantan Barat, sebagian besar Kalimantan Tengah, sebagian Kalimantan Selatan, sebagian Banten, sebagian Jawa Barat, sebagian Jawa Tengah, sebagian Jawa Timur, sebagian Bali, sebagian NTB, sebagian NTT, sebagian Sulawesi Selatan, sebagian Maluku, sebagian Papua Barat, dan sebagian Papua.',
      '2) Maret - April 2024 diprediksi terjadi sebagian Aceh, sebagian Bengkulu, sebagian Jambi, sebagian Sumatera Selatan, sebagian Lampung, sebagian besar Pulau Kalimantan, sebagian Pulau Jawa, sebagian Bali, sebagian NTB, sebagian NTT, sebagian Sulawesi Barat, sebagian Sulaswesi Selatan, sebagian besar Papua Barat dan sebagian besar Papua.',
      '3) Mei 2024 diprediksi terjadi di sebagian Kalimantan Barat, sebagian Kalimantan Tengah, sebagian Kalimantan Utara, sebagian Kalimantan Timur, sebagian kecil Kalimantan Selatan, sebagian Sulawesi Barat, sebagian besar Sulaswesi Selatan, sebagian Sulaswesi Tengah, sebagian kecil Suawesi Tenggara, sebagian Maluku, sebagian Maluku Utara, sebagian Papua Barat, dan sebagian Papua.',
      '4) Juni - Juli 2024 diprediksi terjadi di sebagian kecil di Pulau Kalimantan, pesisir timur Sulawesi Selatan, sebagian Sulawesi Tengah, sebagian besar Maluku, sebagian Maluku Utara, sebagian besar Papua Barat, dan sebagian Papua.',
    ],
    link: "https://cdn.bmkg.go.id/Web/dinat-das-II-jan-2024.gif",
    pdfLink: "https://cdn.bmkg.go.id/Web/02.-Dinamika-Atmosfer-Dasarian-II-Januari-2024.pdf",
  },
  {
    key: 'dasa-1-januari-24',
    title: 'Analisis Dinamika Atmosfer Dasarian I Januari 2024',
    tgl: '12 Jan 2024',
    penulis: 'Kukuh Prasetyaningtyas',
    descriptions: [
      'AAnalisis dan Prediksi ENSO dan IOD:Hasil monitoring indeks IOD dan ENSO Dasarian I Januari 2024, Indek Dipole Mode bulanan sebesar (+0.64), sedangkan indeks ENSO Dasarian I Januari menunjukkan indeks (+2.11), IOD diprediksi memasuki kondisi Netral mulai Januari 2024. Sementara itu, indeks ENSO diprediksi turun secara gradual menuju Netral mulai April 2024.',
      'Analisis dan Prediksi Angin 850mb:Strealmine angin menunjukkan adanya belokan angin dan sistem tekanan rendah di sekitar Laut Natuna Utara, Laut Jawa, Laut Banda, dan Laut Arafuru. Pada dasarian II Januari,aliran massa udara di wilayah Indonesia akan didominasi oleh angin baratan. Daerah pertemuan dan belokan angin diprediksi terjadi di Sumatera bagian Tengah, Kalimantan Utara, Maluku Utara, dan Papua bagian utara.',
      'Analisis OLR:Daerah tutupan awan (OLR =220 W/m2) pada dasarian I Januari 2024 umumnya lebih tinggi dibandingkan klimatologisnya, khususnya di sekitar Lampung dan Jawa bagian barat. Di wilayah NTT, Sulawesi bagian timur, dan Maluku, tutupan awan umumnya lebih rendah dibandingkan klimatologisnya.',
      'Analisis dan Prediksi MJO:Analisis dasarian I Januari 2024 menunjukkan MJO aktif di fase 2 (S. Hindia bagian Barat) dan diprediksi aktif di fase 3, 4 dan 5 hingga awal dasarian III Januari 2024, MJO berkaitan dengan peningkatan konveksi/potensi awan hujan di wilayah Indonesia bagian barat.',
      'Analisis dan Prediksi Kelembapan Udara (RH):Kelembapan udara permukaan berkisar 60- 80% dan diprediksi hingga Dasarian I Februari 2024 berkisar 60 - 80 %, pada lapisan 850mb diprediksi berkisar 60- 80% serta pada lapisan 700 mb umumnya diprediksi 50 - 80%.',
      'Analisis dan Prediksi Suhu:Suhu rata-rata permukaan berkisar 23 - 28°C dan diprediksi hingga Dasarian I Februari 2024 berkisar 22-28°C, Prediksi suhu minimum berkisar 10 - 24°C dan Prediksi suhu maksimum berkisar 26-34°C.',
      'Peringatan Dini:Peringatan Dini Curah Hujan Tinggi pada klasifikasi Waspada: Beberapa Kabupaten di Provinsi Aceh, Banten, DKI Jakarta, Jambi, Jawa Barat, Jawa Tengah, Kalimantan Barat, Kalimantan Selatan, Kepulauan Bangka Belitung, Lampung, Maluku, Papua, Riau, Sulawesi Selatan, Sulawesi Tenggara, Sulawesi Utara, Sumatera Barat, Sumatera Selatan, Sumatera Utara. Siaga: Beberapa Kabupaten di Provinsi Jawa Barat, Jawa Tengah, Sulawesi Selatan, Sulawesi Tenggara, Sulawesi Utara. Awas : Beberapa Kabupaten di Provinsi Sulawesi Selatan. Peringatan Dini Kekeringan Meteorologis : Tidak ada',
      'Analisis Curah Hujan Dasarian I Januari 2024:Curah hujan pada Dasarian I Januari 2024 umumnya berada di kriteria menengah - Tinggi (50 - 300 mm/dasarian). Sifat hujan pada Dasarian I Januari 2024 umumnya Normal hingga Atas Normal.',
      'Analisis Perkembangan Musim Hujan Dasarian I Januari 2024:Berdasarkan jumlah ZOM, sebanyak 64% wilayah Indonesia masuk musim hujan. Wilayah yang sedang mengalami musim hujan meliputi Pulau Sumatera kecuali Lampung bagian selatan, sebagian Banten, sebagian besar Jawa Barat, sebagian besar Jawa Tengah, DIY, sebagian Jawa Timur, Pulau Kalimantan, Sulawesi Utara, sebagian Sulawesi Tengah, sebagian Sulawesi Barat, sebagian Sulawesi Selatan, sebagian Bali, sebagian Nusa Tenggara Barat, sebagian Nusa Tenggara Timur, sebagian Maluku Utara, Maluku dan Pulau Papua.',
      'Prediksi Curah Hujan Dasarian: Januari Dasarian II - Februari Dasarian I 2024:Pada Januari II - Februari III 2024 umumnya diprediksi curah hujan berada di kriteria rendah - menengah (0 - 150 mm/dasarian). Wilayah yang diprediksi mengalami hujan kategori tinggi - sangat tinggi (>150 mm/dasarian) :',
      '1) Pada Januari II 2024 meliputi sekitar Aceh Barat, Sumatera Utara bagian barat, Sumatera barat bagian barat dan utara, Riau bagian barat dan utara, sekitar Pekan Baru, Jambi bagian tengah, Sumatera Selatan bagian barat, Belitung, sekitar Lamping Utara, Banten bagian barat, Wilayah Utara Jawa Barat bagian barat dan timur, Pesisir Utara Jawa Tengah, sekitar Bima, Kalimantan Barat bagian utara, Kalimantan Tengah bagian tengah, Kalimantan Selatan bagian selatan, Pesisir Utara Sulawesi Utara, Sulawesi Selatan bagian selatan, Sulawesi Tenggara bagian utara dan Papua bagian barat dan tengah.',
      '2) Pada Januari III 2024 meliputi sebagian Lampung Tengah, Banten bagian selatan, Jawa Barat bagian timur, Pesisir Utara Jawa Tengah, Jawa Timur bagian tengah, sekitar Bima, sekitar Sambas, Sulawesi Selatan bagian selatan, Sulawesi Tenggara bagian utara dan Papua bagian tengah.',
      '3) Pada Februari I 2024 meliputi sekitar Pandeglang, Jawa Barat bagian barat dan timur, Pesisir Utara Jawa Tengah, sekitar Malang, Pasuruan, Sambas, Palangkaraya, Kutai Barat, Sulawesi Selatan bagian selatan, Konawe Utara dan Papua bagian tengah.',
      'Prediksi Curah Hujan Lebih Dari 300 mm/Bulan untuk Bulan Januari 2024 - Juni 2024 :',
      '1) Februari 2024 diprediksi terjadi di sebagian Sumatera Bagian Selatan, sebagian Kalimantan Barat, sebagian besar Kalimantan Tengah, sebagian Kalimantan Selatan, sebagian Banten, sebagian Jawa Barat, sebagian Jawa Tengah, sebagian Jawa Timur, sebagian Bali, sebagian NTB, sebagian NTT, sebagian Sulawesi Selatan, sebagian Maluku, sebagian Papua Barat, dan sebagian Papua.',
      '2) Maret - April 2024 diprediksi terjadi sebagian Aceh, sebagian Bengkulu, sebagian Jambi, sebagian Sumatera Selatan, sebagian Lampung, sebagian besar Pulau Kalimantan, sebagian Pulau Jawa, sebagian Bali, sebagian NTB, sebagian NTT, sebagian Sulawesi Barat, sebagian Sulaswesi Selatan, sebagian besar Papua Barat dan sebagian besar Papua.',
      '3) Mei 2024 diprediksi terjadi di sebagian Kalimantan Barat, sebagian Kalimantan Tengah, sebagian Kalimantan Utara, sebagian Kalimantan Timur, sebagian kecil Kalimantan Selatan, sebagian Sulawesi Barat, sebagian besar Sulaswesi Selatan, sebagian Sulaswesi Tengah, sebagian kecil Suawesi Tenggara, sebagian Maluku, sebagian Maluku Utara, sebagian Papua Barat, dan sebagian Papua.',
      '4) Juni - Juli 2024 diprediksi terjadi di sebagian kecil di Pulau Kalimantan, pesisir timur Sulawesi Selatan, sebagian Sulawesi Tengah, sebagian besar Maluku, sebagian Maluku Utara, sebagian besar Papua Barat, dan sebagian Papua.',
    ],
    link: "https://cdn.bmkg.go.id/Web/dinat-das-II-jan-2024.gif",
    pdfLink: "https://cdn.bmkg.go.id/Web/02.-Dinamika-Atmosfer-Dasarian-II-Januari-2024.pdf",
  },
]