export const data = [
    { key: "1", name: "John Brown", age: 32, address: "New York No. 1 Lake Park" },
    { key: "2", name: "Jim Green", age: 42, address: "London No. 1 Lake Park" },
    { key: "3", name: "Joe Black", age: 32, address: "Sydney No. 1 Lake Park" },
    { key: "4", name: "Jim Red", age: 32, address: "London No. 2 Lake Park" },
    { key: "5", name: "Jane White", age: 29, address: "Tokyo No. 1 Lake Park" },
    { key: "6", name: "Jack Brown", age: 36, address: "New York No. 2 Lake Park" },
    { key: "7", name: "Jill Green", age: 40, address: "London No. 3 Lake Park" },
    { key: "8", name: "James Black", age: 34, address: "Sydney No. 2 Lake Park" },
    { key: "9", name: "Jenny Red", age: 28, address: "Tokyo No. 2 Lake Park" },
    { key: "10", name: "Johnny Blue", age: 38, address: "Paris No. 1 Lake Park" },
    { key: "11", name: "Jerry Brown", age: 30, address: "New York No. 3 Lake Park" },
    { key: "12", name: "Jessie Green", age: 44, address: "London No. 4 Lake Park" },
    { key: "13", name: "Jordan Black", age: 32, address: "Sydney No. 3 Lake Park" },
    { key: "14", name: "Joy Red", age: 26, address: "Tokyo No. 3 Lake Park" },
    { key: "15", name: "Jacob Blue", age: 39, address: "Paris No. 2 Lake Park" },
    { key: "16", name: "Julia Brown", age: 35, address: "New York No. 4 Lake Park" },
    { key: "17", name: "Jasmine Green", age: 41, address: "London No. 5 Lake Park" },
    { key: "18", name: "Jasper Black", age: 33, address: "Sydney No. 4 Lake Park" },
    { key: "19", name: "Jade Red", age: 27, address: "Tokyo No. 4 Lake Park" },
    { key: "20", name: "Joel Blue", age: 37, address: "Paris No. 3 Lake Park" },
    { key: "21", name: "Jody Brown", age: 31, address: "New York No. 5 Lake Park" },
    { key: "22", name: "Jenny Green", age: 43, address: "London No. 6 Lake Park" },
    { key: "23", name: "Justin Black", age: 32, address: "Sydney No. 5 Lake Park" },
    { key: "24", name: "June Red", age: 25, address: "Tokyo No. 5 Lake Park" },
    { key: "25", name: "Jay Blue", age: 40, address: "Paris No. 4 Lake Park" },
    { key: "26", name: "Jesse Brown", age: 36, address: "New York No. 6 Lake Park" },
    { key: "27", name: "Jenna Green", age: 42, address: "London No. 7 Lake Park" },
    { key: "28", name: "Jackson Black", age: 34, address: "Sydney No. 6 Lake Park" },
    { key: "29", name: "Janet Red", age: 29, address: "Tokyo No. 6 Lake Park" },
    { key: "30", name: "Jake Blue", age: 38, address: "Paris No. 5 Lake Park" },
  ];

  export const intensitasHujan = [
    {key: "1", kategori_intensitas_hujan: "Hujan ringan (light rain)", nilai_dbz: "25 s/d 35", mm_jam: "1 s/d 5"},
    {key: "2", kategori_intensitas_hujan: "Hujan sedang (moderate rain)", nilai_dbz: "35 s/d 45", mm_jam: "5 s/d 10"},
    {key: "3", kategori_intensitas_hujan: "Hujan lebat (heavy rain)", nilai_dbz: "45 s/d 55", mm_jam: "10 s/d 20"},
    {key: "4", kategori_intensitas_hujan: "Hujan sangat lebat (very heavy rain)", nilai_dbz: "> 55", mm_jam: "> 20"},
  ];
  