export const provinces = [
    { key: 'indonesia', label: 'Indonesia' },
    { key: 'aceh', label: 'Aceh' },
    { key: 'sumatera-utara', label: 'Sumatera Utara' },
    { key: 'sumatera-barat', label: 'Sumatera Barat' },
    { key: 'riau', label: 'Riau' },
    { key: 'jambi', label: 'Jambi' },
    { key: 'sumatera-selatan', label: 'Sumatera Selatan' },
    { key: 'bengkulu', label: 'Bengkulu' },
    { key: 'lampung', label: 'Lampung' },
    { key: 'kepulauan-bangka-belitung', label: 'Kepulauan Bangka Belitung' },
    { key: 'kepulauan-riau', label: 'Kepulauan Riau' },
    { key: 'dki-jakarta', label: 'DKI Jakarta' },
    { key: 'jawa-barat', label: 'Jawa Barat' },
    { key: 'jawa-tengah', label: 'Jawa Tengah' },
    { key: 'di-yogyakarta', label: 'DI Yogyakarta' },
    { key: 'jawa-timur', label: 'Jawa Timur' },
    { key: 'banten', label: 'Banten' },
    { key: 'bali', label: 'Bali' },
    { key: 'nusa-tenggara-barat', label: 'Nusa Tenggara Barat' },
    { key: 'nusa-tenggara-timur', label: 'Nusa Tenggara Timur' },
    { key: 'kalimantan-barat', label: 'Kalimantan Barat' },
    { key: 'kalimantan-tengah', label: 'Kalimantan Tengah' },
    { key: 'kalimantan-selatan', label: 'Kalimantan Selatan' },
    { key: 'kalimantan-timur', label: 'Kalimantan Timur' },
    { key: 'kalimantan-utara', label: 'Kalimantan Utara' },
    { key: 'sulawesi-utara', label: 'Sulawesi Utara' },
    { key: 'sulawesi-tengah', label: 'Sulawesi Tengah' },
    { key: 'sulawesi-selatan', label: 'Sulawesi Selatan' },
    { key: 'sulawesi-tenggara', label: 'Sulawesi Tenggara' },
    { key: 'gorontalo', label: 'Gorontalo' },
    { key: 'sulawesi-barat', label: 'Sulawesi Barat' },
    { key: 'maluku', label: 'Maluku' },
    { key: 'maluku-utara', label: 'Maluku Utara' },
    { key: 'papua', label: 'Papua' },
    { key: 'papua-barat', label: 'Papua Barat' },
    { key: 'papua-selatan', label: 'Papua Selatan' },
    { key: 'papua-pegunungan', label: 'Papua Pegunungan' },
    { key: 'papua-tengah', label: 'Papua Tengah' },
    { key: 'kalimantan-selatan', label: 'Kalimantan Selatan' },
  ];

  export const times = [
    { key: 'hari-ini', label: 'Hari ini' },
    { key: 'besok', label: 'Besok' },
    { key: 'lusa', label: 'Lusa' },
  ];

  export const daftarDataPrakiraan = [
    { key: 'indonesia+hari-ini', src: 'https://cdn.bmkg.go.id/DataMKG/MEWS/ibf/00_indonesia_00.png?31676dipv2ip4uy8gd2afeg' },
    { key: 'indonesia+besok', src: 'https://cdn.bmkg.go.id/DataMKG/MEWS/ibf/00_indonesia_24.png?33267boat3v7vxpzyrc1es7' },
    { key: 'indonesia+lusa', src: 'https://cdn.bmkg.go.id/DataMKG/MEWS/ibf/00_indonesia_48.png?40684ffn0t4c0208zf9jufg' },
  ]
  